### ISSUE TITLE
python-liblarch fails to configure

### ISSUE THREAD

**Issue by jakubbrindza** [getting-things-gnome/gtg#101]
THIS IS A REFERENCED BUG FROM LAUNCHPAD. 
DESCRIPTION BELOW. 
FOR FULL CONVERSATION, LOOK AT https://bugs.launchpad.net/gtg/+bug/1275642

I appear to be having a problem configuring the python-liblarch (2.2.0.r157~ubuntu12.04.1) package on 12.04.1, which appears to be coming from the GTG PPA (gtg-daily).

I went to install something and saw:

The following partially installed packages will be configured:
  python-liblarch

apparently left over from a prior update. When it got to the step of configuring python-liblarch, I see:

Setting up python-liblarch (2.2.0.r157~ubuntu12.04.1) ...
SyntaxError: ('invalid syntax', ('/usr/lib/python2.7/dist-packages/liblarch/tree.py', 423, 30, " print(output, end=' ')\n"))

dpkg: error processing python-liblarch (--configure):
 subprocess installed post-installation script returned error exit status 101
No apport report written because MaxReports is reached already
                                                              dpkg: dependency problems prevent configuration of gtg:
 gtg depends on python-liblarch (>= 2.1.0); however:
  Package python-liblarch is not configured yet.

I tried following the suggestion in bug 1038466 of removing python-liblarch (that bug was actually about python-liblarch_gtk) and then reinstalling gtg, but that just triggered the same error when python-liblarch was attempted to be configured again.

**Comment by nekohayo** [comment]
Reopen if still an issue with current git master of everything.
