### ISSUE TITLE
Sorting does not set an arrow/triangle (such as ▼/▲) to indicate the sorting order in the popover menu

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#1021]
Since the GTK4 port, we don't have a treeview header area anymore, but we have a sorting popover menubutton.

The state and direction of sorting should be reflected within that menu, on startup and when it is changed by the user.

**Comment by diegogangl** [comment]
This would actually need a way to reverse the sorting. The sorting direction is always the same ATM, just changing the value used to sort
