### ISSUE TITLE
Search feature is not intuitive

### ISSUE THREAD

**Issue by ePaulo** [getting-things-gnome/gtg#104]
Make search feature more easily discoverable:
- [x] icon in the head bar
- [x] CTRL+F shortcut to start searching
- [x] separate search bar

Original text:

> A simple search tool would be helpful. I have accumulated a long list of tasks for one project and a search tool to find all tasks with a specific keyword or phrase would be nice.

**Comment by izidormatusov** [comment]
You can search directly from task browser:

![screen shot 2015-05-07 at 09 06 05](https://cloud.githubusercontent.com/assets/98588/7510035/6057bc9a-f498-11e4-9b18-9cd2f05c3b3b.png)

Start typing into quick add bar and then select search. UI is not intuitive right now but @jakubbrindza is going to fix that over the summer.

**Comment by nekohayo** [comment]
Merged in master.
