### ISSUE TITLE
Newly created tasks have "Undismiss" instead of "Dismiss" in their menu

### ISSUE THREAD

**Issue by kocio-pl** [getting-things-gnome/gtg#1043]
Task menu for a new task contains "Undismiss" item, which makes no sense for me, since it was never dismissed in the first place. The same is true for the first run tutorial tasks.

Selecting this item does nothing.

**Comment by nekohayo** [comment]
As per version 0.6, the correct/expected behavior would be the reverse state: newly created tasks should have the "Dismiss" action available in that menu, instead of "Undismiss". Maybe just an accidentally inverted boolean variable somewhere?
