### ISSUE TITLE
NetworkManager not listed as a dependency for running the dev version of GTG

### ISSUE THREAD

**Issue by gazeek** [getting-things-gnome/gtg#105]
After doing everything that is written in the README.md when I run ./gtg.sh i get this: http://pastebin.com/g0j02Rwe

I don't know what the problem is.

I am running Ubuntu 15.04 64-bit.

**Comment by izidormatusov** [comment]
You're missing a dependency, try to install the following package:

    sudo apt-get install gir1.2-networkmanager-1.0

Does it solve your problem?

**Comment by gazeek** [comment]
Yes, thank you.

**Comment by izidormatusov** [comment]
We should add networkmanager as our dependency

**Comment by nekohayo** [comment]
Ploum recently fixed NM support via commit 83324a8ef9 ; if NM is still going to be relevant for use in GTG in the future, then to close this task all that would left to be done is to mention the dependency in the readme/elsewhere if not done already?

**Comment by ploum** [comment]
@nekohayo > You can modify the README and close it ;-)

**Comment by diegogangl** [comment]
We're using Gio.NetworkMonitor now so no dependency needed
