### ISSUE TITLE
Fix run-tests errors

### ISSUE THREAD

**Issue by kocio-pl** [getting-things-gnome/gtg#1053]
After big refactoring `run-tests` fails with errors. It can run with ` ./run-tests --continue-on-collection-errors` and there can be many things to change, but I think it would be good to have at least basic form of testing working properly out of the box.

After some plumbing I have now only 2 types of errors left, which looks to be some specific Python quirks:

1. The file is `info.py.in`, not `info.py`:
 
GTG/core/datastore.py:37: in <module>
    import GTG.core.info as info
E   ModuleNotFoundError: No module named 'GTG.core.info'

2. Using `from GTG.gtk.browser.modify_tags import parse_tag_list` is not able to import name `parse_tag_list`

How can I get rid of them?

**Comment by SqAtx** [comment]
The first issue is interesting - I run into it locally as well, but GHA doesn't. It collects the tests as normal. See https://github.com/getting-things-gnome/gtg/actions/runs/8118410410/job/22192600382 for #1036.

As for the second one, the method has moved, so the tests will have to move as well. A temporary solution could be to remove the import and ignore the tests, which is what I had in #999. When we get a green test run, we can come back to these tests and put them in the correct place.

The good news is that there are several people working on getting a green test suite again :) You can check out #1036 and #967. That said, there are still individual test failures. I'm currently looking at fixing `test_saved_search.py`.

**Comment by kocio-pl** [comment]
> As for the second one, the method has moved, so the tests will have to move as well. 

The problem is that it is a new location.

> The good news is that there are several people working on getting a green test suite again :) 

Great! :+1:

**Comment by kocio-pl** [comment]
Hm, this is still not fixed - `./run-tests` still fails:

> collected 135 items / 3 errors / 132 selected

**Comment by SqAtx** [comment]
For better or for worse, we now have to run `meson install` before running the tests. See how GHA does it at https://github.com/getting-things-gnome/gtg/blob/master/.github/workflows/unit_tests.yml, and @picsel2 's explanation in #1036
