### ISSUE TITLE
Extra tags after tag renaming

### ISSUE THREAD

**Issue by gycsaba96** [getting-things-gnome/gtg#1058]
Renaming a tag that is a prefix of another tag adds unwanted tags to other tasks.

Steps to reproduce:
1. Create a task with an `@apple` tag.
2. Create a task with an `@applepie` tag.
3. Rename the `@apple` tag using the sidebar's _"Edit..."_ feature to `@orange`.
4. Open the second task and observe the unwanted `@orangepie` tag.

The main cause is possibly that the [corresponding method](https://github.com/getting-things-gnome/gtg/blob/2ecc997d3fb3f6d102615dafa83bda765cebd420/GTG/core/tasks.py#L361) uses a simple search-and-replace for tag renaming. (The code should ensure that it replaces only whole tag names.)

**Comment by nekohayo** [comment]
Hmm, I wonder if this might be an explanation for the long-standing super annoying tags duplication issue, #605 ?

It would be awesome if you could try fixing both your issue and that one (if they are not exactly the same) simultaneously :)

**Comment by gycsaba96** [comment]
I think the unwanted tags appear for different reasons in the two cases. Here, we have a faulty renaming. In #605, the tag parsing kicks in too early. (There, we could consider preventing the processing of the current word [when parsing the tags](https://github.com/getting-things-gnome/gtg/blob/083353fd9160c7afb05b8ea2925ce61589b08b80/GTG/gtk/editor/taskview.py#L222).)

Nevertheless, I can take a look at both of them. :)

**Comment by nekohayo** [comment]
Does this also get fixed by your PR #1062, or that one was only meant for 605?

**Comment by gycsaba96** [comment]
No, this is still a work in progress. PR 1062 was only for 605.
