### ISSUE TITLE
Outdated meson.build

### ISSUE THREAD

**Issue by kocio-pl** [getting-things-gnome/gtg#1061]
I'm using Ubuntu 22.04. Trying to check current dependencies in meson.build I have tried `gtksourceview-5` instead of 4 and it shows "OK", but `gtk+-4.0` instead of 3 shows "NO (tried pkgconfig and cmake)" even if I can launch current code.

**Comment by diegogangl** [comment]
This was fixed for another reason recently. `meson.build` now has `dep_gtk4 = dependency('gtk4', version: '>= 4.10')`
