### ISSUE TITLE
TypeError: '>' not supported between instances of 'NoneType' and 'NoneType'

### ISSUE THREAD

**Issue by SqAtx** [getting-things-gnome/gtg#1068]
(this report is a bit rushed because it happened while I was in the middle of something)

Not 100% sure what I was doing.

I clicked on a tag, created an issue (tag got added automatically), set it due to "soon", then toggled between Open and Actionable because the sidebar was showing 3 issues for that tag, but the Actionable pane showed 2 and the Open pane showed 0 (not even the one I just created).

Then I got the "GTG has crashed dialog" but clicking on the "Details" link did not work (might be a separate issue there). I found this in the logs:
```
Gtk-Message: 10:32:20.575: GtkDialog mapped without a transient parent. This is discouraged.
Traceback (most recent call last):
  File "<< path to GTG >>/.local_build/install/lib/python3/dist-packages/GTG/core/sorters.py", line 73, in do_compare
    if first > second:
       ^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'NoneType' and 'NoneType'
```

**Comment by gycsaba96** [comment]
I managed to reproduce the crash:

1. Add a few tasks without a due date using the quick add line.
2. Sort them by a due date using the "Change Sorting" button.
3. Observe the crash.
4. (!) If you reopen GTG, the newly created tasks are no longer there.

**Comment by SqAtx** [comment]
Awesome, thank you!
