### ISSUE TITLE
Relative due dates don't update when the date changes

### ISSUE THREAD

**Issue by SqAtx** [getting-things-gnome/gtg#1073]
Today is 2024-03-26. I have two tasks due 2024-03-25, but they are marked as due today:
![image](https://github.com/getting-things-gnome/gtg/assets/4351932/db239644-af0b-4c0a-9910-e65c7967970d)

Note that GTG has stayed open overnight.

I only managed to fix it by restarting GTG:
![image](https://github.com/getting-things-gnome/gtg/assets/4351932/fd511991-c8db-4795-90ef-823a94411130)

**Comment by diegogangl** [comment]
We probably need to refresh all panes to `app.timer`, instead of the active one
