### ISSUE TITLE
AttributeError: 'Date' object has no attribute 'year'

### ISSUE THREAD

**Issue by SqAtx** [getting-things-gnome/gtg#1116]
Click on the "Closed on" date picker of a closed task.

![image](https://github.com/getting-things-gnome/gtg/assets/4351932/fe41d466-91f6-491d-bf8f-1733a9343da9)

Not sure why the bug report says GTG 0.6 - this is on 13870ddc99d29d578a857ee25a71b69207dccd60 (master from April).

**Context:** Global generic exception

```python-traceback
Traceback (most recent call last):
  File "/home/kguillaumond/src/gtg/.local_build/install/lib/python3/dist-packages/GTG/gtk/editor/editor.py", line 292, in show_popover_closed
    gtime = GLib.DateTime.new_local(closed_date.year, closed_date.month, closed_date.day, 0, 0, 0)
                                    ^^^^^^^^^^^^^^^^
AttributeError: 'Date' object has no attribute 'year'
```

**GTG:** 0.6.0-13870ddc
**Flatpak:** False
**Snap:** False
**Display Name:** wayland-0
**Desktop:** GNOME

**lxml:** True
**caldav:** False
**liblarch:** False
**Cheetah3:** False
**dbus-python:** True
**pdflatex:** False
**pypdftk:** False

**OS:** Debian GNU/Linux 12 (bookworm)
**Python:** CPython 3.11.2
**GLib:** 2.74.4
**PyGLib:** 3.42.2
**PyGObject:** 3.42.2
**GTK:** 4.3.8

**Comment by mattmcadoo** [comment]
Happens for me also using the version listed in #1115    Commit: https://github.com/getting-things-gnome/gtg/commit/c501ff800e4517f66b3254f373d41bf9afd861fa

**Comment by diegogangl** [comment]
Looks like GH didn't get the "fix" keyword, closing this manually then
