### ISSUE TITLE
Acting on tasks in Closed Task list acts on open task if selected simultaneously

### ISSUE THREAD

**Issue by olantwin** [getting-things-gnome/gtg#116]
### Affects:

Current master 28fd75c
### Steps to reproduce:
- Select a task in the task-view
- Open closed task list
- Try to un-dismiss, un-close, delete a task in the closed-task list via right-click menu
### Expected result:
- Closed task that the menu was opened on is un-dismissed, un-closed, deleted
### Actual result:
- Open task selected is dismissed, closed, deleted

(For completeness, current master, using Arch Linux and gtg-git from the AUR)

**Comment by diegogangl** [comment]
Fixed in PR #223
