### ISSUE TITLE
Be able to sync issues from more issue trackers

### ISSUE THREAD

**Issue by tkdchen** [getting-things-gnome/gtg#118]
Bugzilla synchronization can synchronize bug information from various Bugzilla services. It will be good to extend this to support multiple issue trackers, for example, JIRA, Github, BitBucket or something else. That would benefit a wider range of GTG users that might use a different issue tracker to manage their tasks instead of Bugzilla.

**Comment by izidormatusov** [comment]
Synchronization from different sources should be implemented as separate synchronisation services. Please file a separate ticket for each type of service. (Be aware that there is no plan to work on it until GTG 0.4 is released unless somebody contributes PRs)
