### ISSUE TITLE
Cannot quit by Ctrl+q

### ISSUE THREAD

**Issue by tkdchen** [getting-things-gnome/gtg#119]
This is a normal feature for all applications. Affects current dev code.

**Comment by jakubbrindza** [comment]
Hi, thank you for pointing this out.

I had to comment out this accelerator because the widget file_quit has been removed from the taskbrowser.ui as I was implementing header bar.

I will fix this ASAP, sorry for any inconvenience :worried:

**Comment by izidormatusov** [comment]
Sorry for inconvenience, I'm working on it as part of converting GTG to use GtkApplication. You can expect that it will be fixed by the end of the next week after I return from my travel.

**Comment by jakubbrindza** [comment]
@izidormatusov has this been addressed or solved already? If yes, we can close this bug.

**Comment by izidormatusov** [comment]
Still working on this
