### ISSUE TITLE
Plugin should not be marked enabled if there is an error while enabling it.

### ISSUE THREAD

**Issue by tkdchen** [getting-things-gnome/gtg#121]
If a plugin is marked enabled with errors, GTG will fail to launch next time.

**Comment by izidormatusov** [comment]
How would you implement that? Currently it actually imports the plugin and finds out if any issue occurred or not. Testing enabling plugin is not easy (and it usually should work on every machine)

**Comment by tkdchen** [comment]
Oh, not testing. Just import enough. If failed to import a plugin, do not append it to `enabled` list in `plugins` section within `$HOME/.config/gtg/gtg.conf`. Make sense?

**Comment by izidormatusov** [comment]
We're already doing that: https://github.com/getting-things-gnome/gtg/blob/master/GTG/core/plugins/engine.py#L118-L141

**Comment by tkdchen** [comment]
Great. Thanks :)

**Comment by izidormatusov** [comment]
Closing this issue as it is already implemented.
