### ISSUE TITLE
Zoom in, zoom out, and recover to original font size in task editor

### ISSUE THREAD

**Issue by tkdchen** [getting-things-gnome/gtg#122]
Just as the subject, this is a simple feature request.

**Comment by izidormatusov** [comment]
Can you provide use case when you would like to do that?

**Comment by tkdchen** [comment]
I'm using Thinkpad T440s with high resolution. I've already set DPI to 120 in my desktop environment, but the text in task editor is still small to my eyes. Thus, if I can zoom text in, it'll be much comfortable for my eyes.

**Comment by izidormatusov** [comment]
You can change the font for editor in preferences. When selecting font, you specify the size of that font. Does it satify your need?

**Comment by izidormatusov** [comment]
Taking it as yes.

**Comment by tkdchen** [comment]
Hi, the answer is yes. Thanks :)
