### ISSUE TITLE
Drag/Drop doesn't reorder tasks

### ISSUE THREAD

**Issue by DiagonalArg** [getting-things-gnome/gtg#124]
Try to drag/drop the subtasks of "Getting started with GTG" to change their order within that task. It won't work. I'm not sure what it's doing, but it may be ordering according to when the task was last edited. (I edited one of the "Getting Started with GTG" tasks, and it appears at, will not move from, the end of the list.)

Ubuntu 12.04

**Comment by izidormatusov** [comment]
Ordering of the tasks by the user preference is not yet implemented and we don't have it on our roadmap. (It's surprising hard to do if you allow any filtering by tags/search, etc).
