### ISSUE TITLE
Only the last occurrence of a tag gets highlighted in the task editor

### ISSUE THREAD

**Issue by DiagonalArg** [getting-things-gnome/gtg#125]
Notice that in a task, only the last reference to a tag is highlighted.  (This may be a bug in itself?)

Delete that last (highlighted) reference to the tag (keeping the previous ones).   Now no reference to that tag is highlighted.  Close out the tag [**Edit**: I meant "task"], and if that is the only task with that tag, the tag will disappear from the tag list.  Now reopen that task, and the last reference to the tag will be highlighted.  Close it out and the tag will reappear in the list.

Ubuntu 12.04

**Comment by diegogangl** [comment]
Not happening in Master anymore
