### ISSUE TITLE
Creating tag after creating subtask, then editing subtask, crashes gtg.

### ISSUE THREAD

**Issue by DiagonalArg** [getting-things-gnome/gtg#127]
Start in a task and create a subtask.  Then immediately add a tag.    Like this:

```
- NewSubtask

@NewTag
```

Now, try to edit the subtask by double clicking or right click >> Edit.  It will crash gtg.

Ubuntu 12.04

**Comment by izidormatusov** [comment]
I can't reproduce this. Do you mind to record a screencast what you do and share it with us?
