### ISSUE TITLE
Please Add Integration with Gnote, in Addition to Tomboy (if exists, I can't find it).

### ISSUE THREAD

**Issue by DiagonalArg** [getting-things-gnome/gtg#130]
Please add integration with Gnote in addition to TomBoy.  TomBoy is freaky slow.

**Comment by izidormatusov** [comment]
There is already integration with Gnote. It is in Synchronization Services dialog (just next to TomBoy).

@jakubbrindza is going to rework preferences, plugins and synchronisation services settings to make it easier to find.
