### ISSUE TITLE
Please add bold/italics to task editor

### ISSUE THREAD

**Issue by DiagonalArg** [getting-things-gnome/gtg#131]
Please allow us to use bold/italics, etc as with TomBoy/Gnote.  Or even better, add some markdown syntax.  This would necessitate changing the `-` for subnotes to maybe `&` or `->` (or something else).

**Comment by izidormatusov** [comment]
@jakubbrindza and I will add bold and italic over the summer.

There is no plan for supporting markdown as the editor is using custom format for storing tasks. That might change in the longer time period.

Links already work when you paste them into the editor.

**Comment by nekohayo** [comment]
Due to our limited resources and the need to focus, I will close this ticket for now. If you still want to see this happen, please contribute code (or bring in someone who can) to the project for this purpose. Thanks!
