### ISSUE TITLE
Please provide a search function for tasks.

### ISSUE THREAD

**Issue by DiagonalArg** [getting-things-gnome/gtg#132]
(Posted this request with a different title and in reverse order.  That's because it includes two requests.)

Please provide a search function (including regexp), to search through all the tasks.

Please allow us to use bold/italics, etc as with TomBoy/Gnote.  Or even better, add some markdown syntax.  This would necessitate changing the `-` for subnotes to maybe `&` or `->` (or something else).

If you do both of these, you will have a nice integrated task & notes manager.  I wouldn't ever have to leave gtg for Gnote/TomBoy.

**Comment by izidormatusov** [comment]
We already have a search functionality, see #104. @jakubbrindza is working on it. 

Closing as duplicate
