### ISSUE TITLE
Please allow export to HTML

### ISSUE THREAD

**Issue by DiagonalArg** [getting-things-gnome/gtg#133]
Please allow export to HTML.

Notice that if you add in the search function and the capacity to add bold/italics/links (or maybe markdown) you will have a complete note manager, in addition to task manager.  And, given the tag hierarchy in gtg, it would be better than either Tomboy or Gnote.

**Comment by izidormatusov** [comment]
Is that export of a single task only? Or all/some of the tasks?

There is already an [export plugin](https://github.com/getting-things-gnome/gtg/tree/master/GTG/plugins/export) that might satisfy your needs. (Though it might be currently broken on master)

**Comment by DiagonalArg** [comment]
Well, both could be good, but I was particularly focused on exporting all tasks.  

Not clear on how to install this plugin, but will poke around.  Thanks.

**Comment by izidormatusov** [comment]
The plugin is already installed with your GTG, you only need to satisfy it's external dependencies:

> Installable on Debian-based system via:
>    $ sudo apt-get install python3-cheetah pdftk pdfjam texlive-latex-base

**Comment by huangyuyao** [comment]
I am installing GTG using flatpak under Linux Mint. How shall I install the dependencies?

```
~ » sudo apt install python3-cheetah pdftk pdfjam                                                                                                                  hyuyao@DragonFly
[sudo] password for hyuyao:  
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package pdftk is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package python3-cheetah is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python3-cheetah' has no installation candidate
E: Package 'pdftk' has no installation candidate
E: Unable to locate package pdfjam
```

**Comment by nekohayo** [comment]
We don't know (see https://github.com/getting-things-gnome/gtg/issues/222#issuecomment-616140952), and someone new (other than us) would need to figure out the status of those dependencies, or work on a new plugin that doesn't depend on all that stuff (issue #299).
