### ISSUE TITLE
[RFE] Command line interface

### ISSUE THREAD

**Issue by shtrom** [getting-things-gnome/gtg#135]
I'd like to script task manipulation from other tools. The best would be a CLI for gtg.
Here's a strawman, all user input is prefixed with $, except for the here-document, between the '''<EOF''' and '''^D''':

    $ gtg --list-tasks
    ID1 do things @cat1 @cat2
    ID2 `- do more things @cat3
    $ gtg --show-task ID1
    Task: do things
    Categories: @cat1 @cat2
    Description:
     -> ID2 do more things @cat3
     bla bla bla
    $ gtg --delete-task ID2
    $ gtg --add-task < EOF
    task title
    @cat3 @cat4
    bla
    ^D
    ID3
    $ gtg --add-task other task title, @cat3 @cat5 other description
    ID4    
    $ gtg --list-tasks
    ID1 do things @cat1 @cat2
    ID3 task title @cat3 @cat4
    ID4 other task title @cat3 @cat5
    $

**Comment by izidormatusov** [comment]
Have you seen [gtcli](https://github.com/getting-things-gnome/gtg/blob/master/GTG/gtcli)?

**Comment by shtrom** [comment]
Obviously not (:

**Comment by izidormatusov** [comment]
Don't forget that GTG exports DBus interface, that gives you even more ways to interact with GTG: 
https://github.com/getting-things-gnome/gtg/blob/master/GTG/gtk/dbuswrapper.py
