### ISSUE TITLE
Add mark as done button in header bar

### ISSUE THREAD

**Issue by shtrom** [getting-things-gnome/gtg#136]
This button used to be in the old toolbar. It has however not gotten into the new header bar.

**Comment by izidormatusov** [comment]
@jakubbrindza works on his GSoC until the end of summer, sorry for having master broken :)

The plan is to not have mark as done button in headerbar for the task browser. Instead, there will be two way how to close task:

1) checkbox next to the task, something similar as in the following mock:
![mock screen](http://i.imgur.com/VlMoQ.png)

2) we will provide selection mode, where you can edit bulk edit your tasks. You select tasks and you can mark them as done, add/remove tags for all of them, set start date or due date.

**Comment by shtrom** [comment]
Ahoy,

On Sun, Jun 14, 2015 at 10:07:58PM -0700, Izidor Matušov wrote:
> @jakubbrindza works on his GSoC until the end of summer, sorry for
> having master broken :)
> 
> The plan is to not have mark as done button in headerbar for the task
> browser. Instead, there will be two way how to close task:
> 
> 1) checkbox next to the task, something similar as in the following
> mock: ![mock screen](http://i.imgur.com/VlMoQ.png)

Ah, right. I like this one. It makes more sense than a global button
requiring a selection.

> 2) we will provide selection mode, where you can edit bulk edit your
> tasks. You select tasks and you can mark them as done, add/remove tags
> for all of them, set start date or due date.

Cool. I think this one can be done effectively with the context menu.

-- 
Olivier Mehani <shtrom@ssji.net>
PGP fingerprint: 4435 CF6A 7C8D DD9B E2DE  F5F9 F012 A6E2 98C6 6655
Confidentiality cannot be guaranteed on emails sent or received unencrypted.

**Comment by izidormatusov** [comment]
> Cool. I think this one can be done effectively with the context menu.

Yes, but there are some limitations to that. It's not possible to set date to something that's not predefined to many tasks. Applying tags to many tasks requires a dialog window. Those problems will be solved by selection mode.
