### ISSUE TITLE
Separate search field and add task field

### ISSUE THREAD

**Issue by sametmax** [getting-things-gnome/gtg#140]
Right new you can't  quick search easily, you need to type, then wait for the pop up to be display, the navigate to search. It's slow and get in the way of quickly organizing your day.

Having two separate would make it ways faster. If there is not enought space to display the search field, you can just display a search button and display the field hover the UI.

**Comment by jakubbrindza** [comment]
This is a feature I've been working on for the past week or so and the pull request is ready to be merged already. 
See #137 --> I have separated the quick add (which is now in the bottom of the window, always present) and the search bar (which pops up when you click on the search icon from the header bar). The search updates the view after each key stroke, which is better for the user. The code, however, is not yet fully optimised as to offer the speed we would like it to have. This will be solved by the end of the summer, but the functionality is there.

Take a look at the PR, it should be merged shortly, once @izidormatusov  reviews it.

**Comment by sametmax** [comment]
Nice. TY.
