### ISSUE TITLE
Add a "(un)fold all" button or context menu entry

### ISSUE THREAD

**Issue by sametmax** [getting-things-gnome/gtg#141]
If you have complexe hierarchy, it's easy to get lost in the tree of your tasks. For a quick scan, you'll want to have the tree folded, but right now it's always expended by default. The level of folding should be saved between screens.

**Comment by nekohayo** [comment]
If someone wants to have a go at implementing this for the hamburger menu (rather than a right-click menu, I think) in the git version, this could be interesting. Otherwise I don't think this would be on the development priorities list.

**Comment by tizianasellitto** [comment]
I've given a shot to this in #563. The change adds two new buttons to either expand or collapse all tasks.

I'm still not 100% sure this is what this issue was all about but that's what I actually needed (and it's my first patch around here :sweat_smile: ) :smile:
