### ISSUE TITLE
More control over search history

### ISSUE THREAD

**Issue by sametmax** [getting-things-gnome/gtg#143]
Sometime I just want to delete all searches, and right now i have to click on any of them.

Also, most searches are not something I want to search again. So you may want to clear searches after one day, unless I ask for it to be saved explicitly.

(Sorry, i realized I'm opening a lot of feature request ticket, it's just i had these issues in mind for a long time and i took the time to report it only today. I love gtd, you are doing a great work, i know you have limited ressources and I'm not expecting anything. I'm just raising the issue in case you find them interesting as well).

**Comment by izidormatusov** [comment]
Jakub is working on this. With his recent PR #137, you will have to click on a button to save the search into history. Search will happen as you type (though we still work on the performance of that)
