### ISSUE TITLE
Add a way to tell if a task has content or not

### ISSUE THREAD

**Issue by sametmax** [getting-things-gnome/gtg#147]
Right now you can't tell if a task is just a title, or has information in it. You may delete it, missing the fact you added an address or a phone number in the task body.

Adding a color, an pictogram or a font to show that a task holds some content can prove useful.

**Comment by izidormatusov** [comment]
Hey, GTG has an option to show the snippets of the task, you can set it in [preferences](https://github.com/getting-things-gnome/gtg/blob/e68c5d45831e281c2509cbbd1589f57d339b4bdc/GTG/gtk/preferences.ui#L149)

This adds gmail-like snippets next to the title of the task.

**Comment by sametmax** [comment]
Fantastic, thanks.
