### ISSUE TITLE
Setting Autostart and "New Task" shortcut in preferences not working

### ISSUE THREAD

**Issue by jakubbrindza** [getting-things-gnome/gtg#154]
In current preferences window, when trying to set GTG to autostart on log in or to set the New Task shortcut, the system seems not to remember my decision in this.

I set it to "ON" (a.k.a activate the check button), close the preferences window, open it again, and it is set to "OFF" (a.k.a. check button de-activated). This means that I can actually never set these two settings to active and make them functional.

Maybe some dependencies required for them which I'm missing? 
If not dependencies, this needs to be addressed anyway for #153 or its descendants...

**Comment by izidormatusov** [comment]
I can confirm that this is an issue on Fedora 22

**Comment by nekohayo** [comment]
Why would anyone want to launch GTG automatically on desktop session login, and why would this be the responsibility of GTG's codebase? This is creating technical debt / a maintenance burden for GTG, and users who care about this could just use gnome-tweak-tool (or whatever desktop settings UI) to tell the desktop to launch GTG on startup.

Unless I'm misunderstanding something, I would advise to actually remove this code entirely from GTG.

**Comment by izidormatusov** [comment]
This is a feature of GTG that had been present for a long time but I
believe Jakub's work might have temporary broken it.

**Comment by diegogangl** [comment]
> Why would anyone want to launch GTG automatically on desktop session login, and why would this be the responsibility of GTG's codebase? This is creating technical debt / a maintenance burden for GTG, and users who care about this could just use gnome-tweak-tool (or whatever desktop settings UI) to tell the desktop to launch GTG on startup.
> 
> Unless I'm misunderstanding something, I would advise to actually remove this code entirely from GTG.

+1. You can make things load on startup using Tweaks (or XDG autostart) nowadays.
On the other hand, the shortcut to quickly add a task could be handy, and it looks like it's only a bug in the ui code.
