### ISSUE TITLE
GTG & liblarch conflict

### ISSUE THREAD

**Issue by brrrrain** [getting-things-gnome/gtg#163]
GTG using python2 and of course wrote using python2 syntax. But liblarch using python3 and wrote using python3 syntax. And when i'm trying run GTG using python2 i'm getting eror from liblarch

> File "/usr/local/lib/python2.7/dist-packages/liblarch/tree.py", line 417
>    print(output, end=' ')

And it's clear, python2 does not support «end» argument because it available only in python3.

When i'm trying to run GTG using python3 i'm getting error from GTG:
>  File "gtg", line 74
>    print "GTG (Getting Things GNOME!)", info.VERSION

And it's also clear, because in python3 print function should be used with parentheses.

**Comment by izidormatusov** [comment]
Hey, about 1-2 years ago we switched to Python3 and Gtk3. If you look at our master, you can find the print statement was modified to run with python 3: https://github.com/getting-things-gnome/gtg/blob/373f2961d0a70fc63e9fc685b47d2bc16fd149c5/GTG/gtg#L159

Please grab the latest codebase if you are planning to hack on GTG.
