### ISSUE TITLE
 Synchronize to Google Tasks using the new API  (reported 2011.05.26)

### ISSUE THREAD

**Issue by heyakyra** [getting-things-gnome/gtg#164]
This would bring GTG into compatibility with all the other major task apps, so that people can easily migrate to GTG and/or have GTG for desktop while having another app for mobile. 

https://bugs.launchpad.net/gtg/+bug/788564/

https://developers.google.com/google-apps/tasks/?hl=en

progress was being made here: https://code.launchpad.net/~gtg-contributors/gtg/google_tasks

**Comment by nekohayo** [comment]
I'm not sure encouraging the use of Google services is so desireable these days... nonetheless, if someone cares enough to provide a pull request of a working and up-to-API-date code branch and then swear to maintain it, then why n—oh wait, https://www.androidpolice.com/2019/02/05/all-roads-lead-to-gmail-google-is-shutting-down-the-classic-tasks-web-ui/
