### ISSUE TITLE
Periodic / repeating / recurring tasks

### ISSUE THREAD

**Issue by ghost** [getting-things-gnome/gtg#169]
It would be cool if periodic tasks were implemented in Getting Things GNOME. For example I have many tasks that must be carried out every week. So people like me need a new option for setting the period (1 week). When clicking the "Mark as done" button two things should happen then:
1. The task should be copied in the Closed tasks tab
2. The task's start and end dates should be automatically changed according to the period set (1 week), but the task must otherwise stay in the Active tasks tab

With the current version of Getting Things GNOME instead I have to do the following things:
1. Manually create an identical task and mark it as done (for record keeping)
2. Manually change the start and end dates of the main task without marking it as done

What do you think?

**Comment by fturco** [comment]
Oops, I just found [this](https://wiki.gnome.org/Apps/GTG/blueprints/repeated_tasks) related blueprint on GNOME wiki.

**Comment by nekohayo** [comment]
As a user myself I would love to have this. Someone needs to step forward to implement the feature, patches welcome, otherwise I don't know when/if that will happen.

**Comment by diegogangl** [comment]
Some thoughts on this based on @leio's idea in the chat.

- Only start _or_ due can be set to repeat, but not both at the same time
- We can add this as separate properties to a task in the xml (`repeat-type` and `repeat-interval` or something like that)
- The UI for this should be separated from the start/due fields to avoid confusion
- Also, this means we can auto-set a due or start date but the user can later change it without affecting the repeating tasks
- We can also have a UI to modify how the task repeats without affecting due/start
- When the task is set to done or dismisses, we shift to the next date and make a copy with a `closed` status to keep track
- We should have an option in the menu to "stop repeating" the task
- If the task isn't done by the time it should repeat, we clone the task and remove the repeat in the original. 
- If it gets deleted it stops repeating
- Once we have ported the sidebar to a listview we could add a section or a filter for repeating tasks

**Comment by zeddo123** [comment]
Hi,

I'm almost done with the implementation of repeating tasks.
However, the current blueprint does not say anything about subtasks of repeating tasks. Should they automatically be repeating and have the same repeating period?

**Comment by diegogangl** [comment]
Great news! 

> However, the current blueprint does not say anything about subtasks of repeating tasks. Should they automatically be repeating and have the same repeating period?

Yes. Subtasks are usually steps in a bigger task, so if you have to do the task again you probably need to go through all the steps too.

**Comment by diegogangl** [comment]
The basics of this feature are now in master thanks to @zeddo123's work, however it's only available to the quick add input. The next step should be plugging this into the GUI. There's two places to do this IMO:

1. **The task browser context menu**. We could have another submenu after "Set Due Date >" where we display the most common recurrencies (is that a word?): every day, every other day, every week, every month, every year.

2. **The task editor**. We could have an extra option in the 3-dots menu after delete. Something like "Make repeatable". This would bring a subpopup menu with the same settings as the context menu. Another option would be adding these settings to the due date calendar popup. We should do some rough mockups before jumping in.


Even more Future work:

- It would be nice to be able to set tasks to repeat every Nth days/weeks/months/years (for instance repeat something every 3 days). This could be really useful for habit related tasks.
- It would also be nice to set an end date for the repetition. So for instance, you could repeat tasks every X days until a certain date. This would need another XML attribute.


Anyways, these are some random notes. This is all open to discuss.

**Comment by zeddo123** [comment]
For the task editor, I was thinking about something like this ( a button to enable/disable the repeating task as well as a "date picker" ).
That said, this comes with some issues. How can the user choose for instance **every day of the week** _(Monday,..)_ or **even a day and a month** _(09/09,..)_ as a calendar wouldn't help due to the year field.

What could be done is to parse the editor as we do for the quick add input. Would it be too slow?

![Screenshot from 2020-09-15 13-53-10](https://user-images.githubusercontent.com/34837535/93312791-e776bf00-f807-11ea-8dfa-f5070226eca7.png)

**Comment by zeddo123** [comment]
Hi everyone,

I teamed up with @Maistrox9 to make the GUI frontend for the repeating tasks. We would really appreciate your feedback,
if there are any issues with the GNOME Human Interface Guidelines or anything else.

![2020-09-25_19-59](https://user-images.githubusercontent.com/34837535/94302013-d3e7f880-ff6b-11ea-800d-34fb5ceeef8b.png)

![2020-09-25_19-58_1](https://user-images.githubusercontent.com/34837535/94302043-dfd3ba80-ff6b-11ea-816b-db87aa4989ab.png)

![2020-09-25_19-58_2](https://user-images.githubusercontent.com/34837535/94302049-e3ffd800-ff6b-11ea-8c59-a53fdda44507.png)

**Comment by Maistrox9** [comment]
Hey @diegogangl, thank you for your detailed reply. After considering each of your points one by one, here is some screenshots showing the new GUI for the repeating tasks:

[task_browser](https://user-images.githubusercontent.com/35756997/94364359-8f21a600-00c0-11eb-8e5e-7865b3e8ed9c.png)

[taskeditor_notrepeating](https://user-images.githubusercontent.com/35756997/94364361-947ef080-00c0-11eb-8352-96c8007055cb.png)

[popup_notrepeating](https://user-images.githubusercontent.com/35756997/94364376-b5474600-00c0-11eb-99cf-2ebb46da8cdb.png)

[popupweekly_notrepeating](https://user-images.githubusercontent.com/35756997/94364384-baa49080-00c0-11eb-88af-57c3db7f7e34.png)

[popupmonthly_notrepeating](https://user-images.githubusercontent.com/35756997/94364388-c001db00-00c0-11eb-8f05-f2693891325c.png)

[popupyearly_notrepeating](https://user-images.githubusercontent.com/35756997/94364392-c4c68f00-00c0-11eb-9a0a-ba18ff1164f3.png)

[taskeditor_repeating](https://user-images.githubusercontent.com/35756997/94364363-9c3e9500-00c0-11eb-8653-fe5446536b5e.png)

[popup_repeating](https://user-images.githubusercontent.com/35756997/94364397-d019ba80-00c0-11eb-9ae8-e86f0c7932c2.png)

- The repeating symbol in the task browser is indeed Unicode, and we do prepend it to the title.
- We removed the Unicode symbol from the title int task editor.
- We removed the icon from the title of the window in the task editor.
- We colored the repeating icon blue to notify the user that a task is recurring, however we would prefer to make the color adaptive to the user's theme, but we couldn't figure out how to do this. If you do know how to do it, we would appreciate you telling us how.

As for the popup, we did everything you said except for the fourth point, which we are considering to do in the near future.

Regarding, the monthly and weekly submenus, we couldn't figure out a better way to do it then using gtk calendars. Let us know your thoughts on this.

**Comment by diegogangl** [comment]
This is looking really good!

Two more ideas:

- I would hide the "Every:" label if repeat is not enabled. Also I'd remove the : and use bold to differentiate, like this: "Every **Monday** " (I'm guessing that's what that label does)
- We should use one of Gnome's symbolic icons for consistency with the other buttons (in the editor). I think either `view-refresh-symbolic` or `media-playlist-repeat-symbolic` would fit. The first one would probably be better. This would make the icons look different in the browser and editor, but we can solve that in the future when we redesign the browser.


> As for the popup, we did everything you said except for the fourth point, which we are considering to do in the near future.

No prob, it was more of a possible alternative

**Comment by Maistrox9** [comment]
Hey, thank for your helpful input.

> I would hide the "Every:" label if repeat is not enabled. Also I'd remove the : and use bold to differentiate, like this: "Every Monday " (I'm guessing that's what that label does)

Here is some screenshots:
![popup_notrepeating2](https://user-images.githubusercontent.com/35756997/94422147-88f1ff00-017e-11eb-9e5b-ce8f306238c6.png)
![popup_repeating3](https://user-images.githubusercontent.com/35756997/94424693-8beeee80-0182-11eb-9c12-ab5be07e1ba0.png)


> We should use one of Gnome's symbolic icons for consistency with the other buttons (in the editor). I think either view-refresh-symbolic or media-playlist-repeat-symbolic would fit. The first one would probably be better. This would make the icons look different in the browser and editor, but we can solve that in the future when we redesign the browser.

I believe, the icon we are currently using is actually one of Gnome's symbolic icons, and its named `emblem-synchronizing-symbolic`.

[Here is](https://user-images.githubusercontent.com/35756997/94422887-abd0e300-017f-11eb-80b3-7d995c1481b7.png) a screeshot from glade's icon list

However we are trying to make the color adaptive to the user's gtk theme. We are currently this:
```css
.recurring-active {
	color: rgb(52, 130, 224);
}
```
and we tried this one:
```css
.recurring-active {
	color: @theme_selected_bg_color;
}
```
but it doesn't work as expected with some gtk themes, for example this is a screenshot fo

**Comment by Maistrox9** [comment]
Hey, thank for your helpful input.

> I would hide the "Every:" label if repeat is not enabled. Also I'd remove the : and use bold to differentiate, like this: "Every Monday " (I'm guessing that's what that label does)

Here is some screenshots:
![popup_notrepeating2](https://user-images.githubusercontent.com/35756997/94422147-88f1ff00-017e-11eb-9e5b-ce8f306238c6.png)
![popup_repeating3](https://user-images.githubusercontent.com/35756997/94424693-8beeee80-0182-11eb-9c12-ab5be07e1ba0.png)


> We should use one of Gnome's symbolic icons for consistency with the other buttons (in the editor). I think either view-refresh-symbolic or media-playlist-repeat-symbolic would fit. The first one would probably be better. This would make the icons look different in the browser and editor, but we can solve that in the future when we redesign the browser.

I believe, the icon we are currently using is actually one of Gnome's symbolic icons, and its named `emblem-synchronizing-symbolic`.

[Here is a screeshot](https://user-images.githubusercontent.com/35756997/94422887-abd0e300-017f-11eb-80b3-7d995c1481b7.png) from glade's icon list

However we are trying to make the color adaptive to the user's gtk theme. We are currently using this:
```css
.recurring-active {
	color: rgb(52, 130, 224);
}
```
and we tried this:
```css
.recurring-active {
	color: @theme_selected_bg_color;
}
```
but it doesn't work as expected with some gtk themes. For example [this is a screenshot](https://user-images.githubusercontent.com/35756997/94426267-3536e400-0185-11eb-8665-82c3184e919f.png) of `Match-light-aliz` theme, which colors the entire button red while it is selected. And [this is another screenshot](https://user-images.githubusercontent.com/35756997/94426970-46ccbb80-0186-11eb-9169-f91f4b6fc729.png) of `Pop` theme, as it doesn't match the gtk checkbox color.
So do you know a better alternative to what we are trying to do? or do we just leave it blue?

**Comment by diegogangl** [comment]
@Maistrox9 Great work! I have no more comments, those popups are ready :rocket: 

> I believe, the icon we are currently using is actually one of Gnome's symbolic icons, and its named emblem-synchronizing-symbolic.

I see, maybe we should get ask some of the Gnome design guys. I don't know if the folder emblems should be used like button icons.

>  So do you know a better alternative to what we are trying to do? or do we just leave it blue?

The problem here is that Gtk doesn't have an actual "Theme API". There's only Adwaita and themes are implemented by replacing the system stylesheet. [Here's a good read about this.](https://blogs.gnome.org/tbernard/2018/10/15/restyling-apps-at-scale)

I'm not against theming but I believe third party themes should support GTG, rather than the other way around. We could help with this by adding a class to the editor window, so they can target the icon through it. Something like `.gtg-editor .recurring-active { color: red; }`

Anyways, leave it Adwaita blue for now. I'll take care of the theming issues later

**Comment by zeddo123** [comment]
Perfect!

We will be hunting for bugs and optimization. You can expect the pull request in a couple of days.😁

**Comment by nekohayo** [comment]
Hi @zeddo123 and @Maistrox9, I just wanted to thank you for getting involved and working on implementing this long-requested feature (as well as other issues I've seen you involved in), it's really cool and exciting! I haven't had the opportunity to try it out myself yet, but I'm looking forward to, and so I'm glad Diego was able to review and merge your work! People reading the release notes/announcement for the next version will probably go wild about this new feature!

**Comment by BeatLink** [comment]
I know I will! Does anyone know when it will be updated?
