### ISSUE TITLE
GtkHeaderBar not like other gnome applications

### ISSUE THREAD

**Issue by akash0675** [getting-things-gnome/gtg#181]
It would be nice to have text inside the buttons replaced by icons like other gnome applications(GEdit, document viewer, etc.)

**Comment by nekohayo** [comment]
My personal opinion is that icons, most of the time, are not clear on meaning, vs text that is instantaneously understood.

Also, it would imply designing icons. We don't have time for that if we want to get 0.4 out of the door this decade, sorry!
