### ISSUE TITLE
GTG is not DBusActivable

### ISSUE THREAD

**Issue by akash0675** [getting-things-gnome/gtg#183]
https://wiki.gnome.org/HowDoI/DBusApplicationLaunching

**Comment by nekohayo** [comment]
I don't quite grasp why this is important, but if you feel strongly about this technological feature, please provide a patch for this.

**Comment by diegogangl** [comment]
This is interesting:

> Instead of the typical UNIX-style fork()/exec() approach to process creation, launching an application is done by sending a D-Bus message to the well-known name of that application, causing a D-Bus activation. In the case that the application is already running, it can respond to the message by opening a new window or raising its existing window.

We might be able to throw away our pid detecting code. This depends on GApplication though, so a few other things need to happen first.

**Comment by diegogangl** [comment]
The GTKApplication port is done, but our dbus interface is still missing some work. Notably #277 
There's also the issue that we are parsing command line arguments using Python instead of the GTK way. Don't know if this might be a problem for dbus activation.
