### ISSUE TITLE
Help not accessible from main window

### ISSUE THREAD

**Issue by shtrom** [getting-things-gnome/gtg#189]
I tried to summon the help file from the main window, but couldn't find how: no button, no menu, and pressing F1 didn't do anything either.

There is a help button in the synchronisation dialog, so I eventually got back to the main page from there, but it's a bit convoluted.

**Comment by sagarghuge** [comment]
Thanks for reporting bug, help is provided on editor part. I will add it on main window. 
Because if user is not familiar and if he wants to know how to use `gtg` exactly he will look for help which should be ideally on main window too.
