### ISSUE TITLE
Requires installation of untrusted packages - Ubuntu Software Center

### ISSUE THREAD

**Issue by mattspag** [getting-things-gnome/gtg#191]
# Trouble installing GTG with all the plugins in Ubuntu Sofware Center

_Not sure if this is a problem with Ubuntu-MATE, Ubuntu Software Center or with GTG. After posting I installed the ppa and GTG manually in the terminal and it worked so I think it is the Ubuntu Software Center or Ubuntu-MATE. Sorry if this is the wrong place. Kind of new to Linux._

**Ubuntu Software Center  gave this error:**

```
Requires installation of untrusted packages
This requires installing packages from unauthenticated sources.

gtg python-liblarch

```

_Some other packages were listed but I hit the repair button before thinking to report it and this was the last one._

**AND This error:**

```

W:Failed to fetch http://ppa.launchpad.net/gtg/ppa/ubuntu/dists/wily/main/binary-amd64/Packages  404  Not Found
W:Failed to fetch http://ppa.launchpad.net/gtg/ppa/ubuntu/dists/wily/main/binary-i386/Packages  404  Not Found
E:Some index files failed to download. They have been ignored, or old ones used instead.

```

**Running:**

`Ubuntu-MATE 15.10 "Wily Werewolf" - Release amd64 (20151021)`

**uname -a:**

`Linux 4.2.0-32-generic #37-Ubuntu SMP Fri Feb 26 02:21:44 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

**After I tried to install the software center crashed.**

**Comment by mattspag** [comment]
I added the ppa and installed manually from the terminal then I unistalled and tried to recreate the error in Ubuntu Software Center. It installed fine that time.

**Comment by nekohayo** [comment]
This is a distro/PPA issue. The old project maintainers (who might have been involved with the PPA) are gone; I don't run Ubuntu and I don't do packaging, can't fix this myself.
