### ISSUE TITLE
Tags hierarchy not always saved consistently? Variations across versions of tags.xml

### ISSUE THREAD

**Issue by Nhorning** [getting-things-gnome/gtg#195]
Taxs.xml on is being written in my gtg folder at 21kb, most of the time.  However, I know the correct back up file size for my tags is  31kb.  This means that only a small minority of my backups are correct.  I frequently lose a few days worth of my tags hierarchy, and have to painstakingly search through my backup folder to find the most recent back up that will work. 

If this was just a backup issue, I could go in and manually make a copy of the main tags.xml to back it up.  However, since Tag.xml itself is not the right size, this must be an issue of the main tags.xml saving correctly in the first place.

**Comment by Nhorning** [comment]
Can Confirm this is still happening in 2019.  I have to go into the backup folder and fix my tag hierarchy every other day.

**Comment by nekohayo** [comment]
Was this happening on 0.3.1, or only the git version? I don't think I've experienced something like corruption on that front, at least nothing that I've noticed in many years of use (maybe I wasn't paying enough attention); for what it's worth, my tags files seem to have a fairly consistent filesize (1st column):

```
data/gtg/backup$ ls -l | grep tags
2667 12 sep 11:48 tags.xml.2019-09-12.bak
2667 13 sep 11:14 tags.xml.2019-09-13.bak
2667 14 sep 08:37 tags.xml.2019-09-14.bak
2667 17 sep 17:48 tags.xml.2019-09-17.bak
2667 21 sep 12:45 tags.xml.2019-09-21.bak
2667 22 sep 10:44 tags.xml.2019-09-22.bak
2667 24 sep 11:34 tags.xml.2019-09-24.bak
2667  1 oct 16:12 tags.xml.2019-10-01.bak
2722  6 oct 23:43 tags.xml.2019-10-06.bak
2722 10 oct 17:55 tags.xml.2019-10-10.bak
2722 12 oct 19:40 tags.xml.2019-10-12.bak
2722 13 oct 21:58 tags.xml.2019-10-13.bak
2740 17 oct 10:49 tags.xml.2019-10-17.bak
2740 21 oct 08:54 tags.xml.2019-10-21.bak
2740 22 oct 23:01 tags.xml.2019-10-22.bak
2740 23 oct 14:43 tags.xml.2019-10-23.bak
2740 24 oct 15:03 tags.xml.2019-10-24.bak
2740 25 oct 00:35 tags.xml.2019-10-25.bak
2722 27 oct 17:33 tags.xml.2019-10-27.bak
2722 29 oct 16:34 tags.xml.2019-10-29.bak
2722  2 nov 10:05 tags.xml.2019-11-02.bak
2781  8 nov 17:33 tags.xml.2019-11-08.bak
2781  9 nov 13:03 tags.xml.2019-11-09.bak
2763 10 nov 04:53 tags.xml.2019-11-10.bak
2816 11 nov 06:06 tags.xml.2019-11-11.bak
2763 12 nov 04:48 tags.xml.2019-11-12.bak
2763 17 nov 18:25 tags.xml.2019-11-17.bak
2763 18 nov 07:38 tags.xml.2019-11-18.bak
2764 19 nov 07:03 tags.xml.2019-11-19.bak
2764 21 nov 14:06 tags.xml.2019-11-21.bak
2764 23 nov 16:27 tags.xml.2019-11-23.bak
2764 24 nov 09:40 tags.xml.2019-11-24.bak
2764 25 nov 13:25 tags.xml.2019-11-25.bak
2764 26 nov 11:03 tags.xml.2019-11-26.bak
2764 28 nov 17:47 tags.xml.2019-11-28.bak
2764 29 nov 10:46 tags.xml.2019-11-29.bak
2764  1 déc 12:14 tags.xml.2019-12-01.bak
2764  2 déc 12:46 tags.xml.2019-12-02.bak
2764  3 déc 10:37 tags.xml.2019-12-03.bak
2764  5 déc 10:20 tags.xml.2019-12-05.bak
2764  7 déc 17:31 tags.xml.2019-12-07.bak
2764 10 déc 16:58 tags.xml.2019-12-10.bak
2764 10 déc 17:58 tags.xml.bak.0
2764 10 déc 17:01 tags.xml.bak.1
2764 10 déc 16:58 tags.xml.bak.2
2764 10 déc 16:58 tags.xml.bak.3
2764  7 déc 17:31 tags.xml.bak.4
2764  5 déc 10:20 tags.xml.bak.5
2764  3 déc 12:32 tags.xml.bak.6
2764  3 déc 10:37 tags.xml.bak.7
```

...but then I'm still running 0.3.1 for now.

Neil, maybe you could write some sort of test case for this? I think GTG has a test suite, and various switches/options that can be used for debugging, profiling, testing with dummy data (instead of your real data), etc. (maybe @ploum remembers, I think he mentioned something like that to me but I can't find it in my emails right now).

At this stage, I don't know yet where to point you to for the proper ways to debug, until #200 is solved, because at a glance there's half a dozen places where documentation is spread out, I'm a bit confused with those gazillion READMEs vs .rst files, wikis vs readthedocs, etc.

**Comment by Nhorning** [comment]
This is happening in 0.3.1

-rw-rw-r-- 1 nhorning nhorning   19965 Nov 30 10:21 tags.xml.2019-11-30.bak
-rw-rw-r-- 1 nhorning nhorning   33865 Dec  2 11:10 tags.xml.2019-12-02.bak
-rw-rw-r-- 1 nhorning nhorning   19965 Dec  3 11:31 tags.xml.2019-12-03.bak
-rw-rw-r-- 1 nhorning nhorning   46234 Dec  4 00:47 tags.xml.2019-12-04.bak
-rw-rw-r-- 1 nhorning nhorning   19965 Dec  6 11:49 tags.xml.2019-12-06.bak
-rw-rw-r-- 1 nhorning nhorning   19965 Dec  7 10:22 tags.xml.2019-12-07.bak
-rw-r--r-- 1 nhorning nhorning   18722 Dec  9 21:18 tags.xml.2019-12-09.bak
-rw-r--r-- 1 nhorning nhorning   33865 Dec 10 11:41 tags.xml.2019-12-10.bak
-rw-r--r-- 1 nhorning nhorning   46234 Dec 11 01:31 tags.xml.2019-12-11.bak
-rw-r--r-- 1 nhorning nhorning   19965 Dec 12 09:40 tags.xml.2019-12-12.bak
-rw-r--r-- 1 nhorning nhorning   11799 Dec 13 10:11 tags.xml.2019-12-13.bak
-rw-r--r-- 1 nhorning nhorning   33865 Dec 15 16:05 tags.xml.2019-12-15.bak
-rw-r--r-- 1 nhorning nhorning   33865 Dec 16 11:33 tags.xml.2019-12-16.bak
-rw-r--r-- 1 nhorning nhorning   33865 Dec 17 11:56 tags.xml.2019-12-17.bak
-rw-r--r-- 1 nhorning nhorning   33865 Dec 19 09:00 tags.xml.2019-12-19.bak
-rw-r--r-- 1 nhorning nhorning   33865 Dec 24 13:22 tags.xml.2019-12-24.bak
-rw-r--r-- 1 nhorning nhorning   33865 Dec 28 08:31 tags.xml.2019-12-28.bak
-rw-r--r-- 1 nhorning nhorning   33865 Dec 30 12:10 tags.xml.2019-12-30.bak
-rw-r--r-- 1 nhorning nhorning   19965 Dec 31 10:59 tags.xml.2019-12-31.bak
-rw-r--r-- 1 nhorning nhorning   46313 Jan  1 01:26 tags.xml.2020-01-01.bak
-rw-r--r-- 1 nhorning nhorning   46313 Jan  2 01:47 tags.xml.2020-01-02.bak
-rw-r--r-- 1 nhorning nhorning   33865 Jan  2 13:30 tags.xml.bak.0
-rw-r--r-- 1 nhorning nhorning   46313 Jan  2 13:30 tags.xml.bak.1
-rw-r--r-- 1 nhorning nhorning   33865 Jan  2 13:18 tags.xml.bak.2
-rw-r--r-- 1 nhorning nhorning   46313 Jan  2 12:28 tags.xml.bak.3
-rw-r--r-- 1 nhorning nhorning   33865 Jan  2 10:35 tags.xml.bak.4
-rw-r--r-- 1 nhorning nhorning   46313 Jan  2 01:47 tags.xml.bak.5
-rw-r--r-- 1 nhorning nhorning   33865 Jan  1 10:21 tags.xml.bak.6
-rw-r--r-- 1 nhorning nhorning   46313 Jan  1 01:26 tags.xml.bak.7

I've started a new position, so probably won't have the bandwidth to write a test case in the near future, but who knows.

**Comment by nekohayo** [comment]
Hi @Nhorning, we didn't hear back and I didn't encounter this in the 0.4 release. Please re-test with GTG 0.5 (that will be released Tuesday), but since it doesn't have a separate tags file anymore, unless you still see this happening, I'll close this as fixed and obsolete.
