### ISSUE TITLE
 GTG 0.3.1 shows a traceback / crash report dialog on quit due to pynotify not being found

### ISSUE THREAD

**Issue by fmfrisch** [getting-things-gnome/gtg#196]
Although it says that Apport will be started automatically it is not so I'm reporting this manually. When I quit GTG it says that it has crashed, although the end user wouldn't know if it wasn't for the crash notification - no unexpected behavior otherwise.

Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(_targs, *_kargs)
  File "/usr/share/gtg/GTG/plugins/bugzilla/notification.py", line 64, in uinit_pynotify
    pynotify.uninit()
NameError: global name 'pynotify' is not defined

**Comment by nekohayo** [comment]
I encountered this issue as well but it is harmless, just annoying.
Someone needs to test if this also affects the git version, I don't remember...

**Comment by diegogangl** [comment]
I never saw this one in master, I guess it was fixed sometime along the way
