### ISSUE TITLE
Crash when enabling Tomboy synchronization

### ISSUE THREAD

**Issue by bajhn** [getting-things-gnome/gtg#197]
When I try to enable synchronization with Tomboy, GTG crashes with an error from Python:

> **\* Error in `/usr/bin/python': realloc(): invalid next size: 0x0000000002be4be0 ***

Sometimes I get a segmentation fault instead.  This prior console output may or may not be relevant:

> 2016-05-31 10:19:16,708 - WARNING - **init**:**init**:74 - Backend backend_launchpad could not be loaded: No module named launchpadlib.launchpad
> 2016-05-31 10:19:16,708 - WARNING - **init**:**init**:74 - Backend backend_rtm could not be loaded: No module named dateutil.tz
> 2016-05-31 10:19:16,708 - WARNING - **init**:**init**:74 - Backend backend_evolution could not be loaded: No module named evolution
> 2016-05-31 10:19:16,709 - WARNING - **init**:**init**:74 - Backend backend_mantis could not be loaded: No module named suds.client
> /usr/share/gtg/GTG/gtk/browser/browser.py:102: GtkWarning: Theme file for default has no name
> 
>   self.builder.add_from_file(GnomeConfig.GLADE_FILE)
> /usr/share/gtg/GTG/gtk/browser/browser.py:102: GtkWarning: Theme file for default has no directories
> 
>   self.builder.add_from_file(GnomeConfig.GLADE_FILE)
> /usr/share/gtg/GTG/gtk/backends_dialog/**init**.py:210: GtkWarning: Theme file for default has no name
> 
>   self.icon_theme.prepend_search_path(directory)
> /usr/share/gtg/GTG/gtk/backends_dialog/**init**.py:210: GtkWarning: Theme file for default has no directories
> 
>   self.icon_theme.prepend_search_path(directory)

Steps to reproduce:
1. Click "Edit".
2. Click "Synchronization Services".
3. Click "Add".
4. Select "Tomboy" and click "OK".
5. Click "Enable syncing".

GTG version 0.3.1
Python version 2.7.6
Linux Mint release 17.1 (rebecca) "Cinnamon 64-bit" -- patches current as of 31 May 2016 14:30 GMT.

Please let me know if you need additional information.

**Comment by bajhn** [comment]
Tomboy version 1.15.4

**Comment by bajhn** [comment]
Reopening; I hadn't meant to close it.

**Comment by nekohayo** [comment]
I'm working on putting this project back on its feet with the goal of getting a release out of the door.

This issue here is up for grabs for anyone wanting to see it happen. Please test with the development version, and contribute code (or bring in someone who can) to the project to bring this plugin back into good shape, or it risks getting decommissioned as part of issue #222.
