### ISSUE TITLE
Gtg refuse to start after updating last Manjaro version

### ISSUE THREAD

**Issue by risoul** [getting-things-gnome/gtg#204]
Here is the output

/usr/bin/gtg:54: PyGIWarning: Gdk was imported without specifying a version first. Use gi.require_version('Gdk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository.Gdk import Screen
Traceback (most recent call last):
  File "/usr/bin/gtg", line 57, in <module>
    from GTG.backends import BackendFactory
  File "/usr/lib/python3.6/site-packages/GTG/backends/__init__.py", line 32, in <module>
    from GTG.backends.genericbackend import GenericBackend
  File "/usr/lib/python3.6/site-packages/GTG/backends/genericbackend.py", line 33, in <module>
    from GTG.core.tag import ALLTASKS_TAG
  File "/usr/lib/python3.6/site-packages/GTG/core/tag.py", line 29, in <module>
    from liblarch import TreeNode
ModuleNotFoundError: No module named 'liblarch'

**Comment by risoul** [comment]
Solved by adding:
```
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk
```
after import dbus into /usr/bin/gtg

AND

Copying libarch and libarch_gtk from /usr/lib/python3.6/site-packages to /usr/lib/python3.5/site-packages/liblarch

**Comment by manulicious** [comment]
That seems kind of dirty. Re-installing the package `aur/python-liblarch-git` did the trick for me—kind of. It seems to work, but in the background some warnings and traces are printed.

**Comment by nekohayo** [comment]
Not quite sure what to do with this as it's kind of unspecific and could be a distro issue or something mixed inbetween, but if you do run into issues with the current git version please feel free to report them.
