### ISSUE TITLE
Fedora 25: When I select "contents" in help menu, I get "Document not found"...

### ISSUE THREAD

**Issue by sudo-justinwilson** [getting-things-gnome/gtg#206]
In the menu bar, if I go to help -> contents, I get the following:
![image](https://cloud.githubusercontent.com/assets/20146242/23354515/ab38025a-fd25-11e6-887f-9125a498840d.png)

**Comment by sudo-justinwilson** [comment]
I'm not sure, but I think it might be a Fedora issue, because as far as I can tell, when I open the /usr/share/help/C/gtg files with gnome-help, it works ok...

**Comment by nekohayo** [comment]
If someone wants to have a go at fixing this and providing a patch, here's some inspiration of a working and battle-tested implementation:

https://gitlab.gnome.org/GNOME/pitivi/blob/master/pitivi/utils/misc.py#L244 ...which references this constant (that is set at configure time, in this particular case): https://gitlab.gnome.org/GNOME/pitivi/blob/master/pitivi/configure.py.in#L48

**Comment by diegogangl** [comment]
This isn't happening anymore as far as I can tell (on Fedora 31)
