### ISSUE TITLE
Calendar date picker dropdown widget missing for "Starts on" and "Due on" fields in task editor

### ISSUE THREAD

**Issue by swingnjazz** [getting-things-gnome/gtg#216]
Hi there.
In former versions of GTG there were date picker drop down menus for "Starts on" and "Due on" fields of the task editor. In version gtg-git  r5174.117bd7b4-1, which I have installed from the arch repos, these fields are simple input fields without any productivity helper. 

Providing these goodies again would be very much appreciated.

**Comment by nekohayo** [comment]
If you happen to have some comparison screenshots, those could be nice to have here for the record. I suppose this is something that was not reimplemented by @jakubbrindza when he redid the task editor GUI, I wonder if it was just for lack of time or due to a technical limitation.

**Comment by swingnjazz** [comment]
I'm sorry, but I don't have any screenshot available.

**Comment by diegogangl** [comment]
In Stable, when you click the up arrow next to the start/due date inputs you get a calendar popup. In master it (should) happen when you click the input. It's sort of looks like the calendar widgets are done but things aren't plugged. There are some TODOs that mention having to refactor the widget though.
