### ISSUE TITLE
Feature request: Dependency graph/tech tree

### ISSUE THREAD

**Issue by Thorsten-Sick** [getting-things-gnome/gtg#217]
Hi

I would love a feature (as a plugin?) to define dependencies in a task.

A graph view showing a kind of tech tree would be cool. To answer:
- Which task can be started ?
- When this task is done, what can be done next ?

Done tasks should be marked "green", task where not all dependencies are fulfilled "red". The tasks that can be started "yellow".

https://en.wikipedia.org/wiki/Technology_tree

In the task text there could be a marker like
DependsOn: Foo, Bar, Baz

**Comment by ploum** [comment]
It's already the case if you create subtasks : simply start a line with "-" and the remaining is the subtasks. Tasks can also be drag and dropped to become subtasks.  (there's also a way to have the same task be the subtasks of mutliples main tasks but I don't remember how to do it).

Anyway, it should be there ;-)
