### ISSUE TITLE
Be smarter about handling the process ID file, and handle multi-computers scenarios

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#218]
If you kill gtg (either because it froze or because you're a crazy tester), for example with gnome system monitor, it will leave a rogue "gtg.pid" file that will prevent startup with "gtg is already running!" printed in the terminal. However, this clearly doesn't check that the process associated with that PID number actually exists, and that it actually is a GTG/Python process. It should.

This is a corner case, but worth filing so it's not forgotten.

**Comment by nekohayo** [comment]
One corner case I forgot about: GTG synced across multiple computers with Unison or some other mechanism. If the user forgets GTG running on one computer, this change would make the 2nd computer launch it anyway, leading to disparity.

To prevent this, two approaches are possible:

* The dumb approach: if the stored PID is not found as a running process on the current system, just warning the user with a dialog that says "It seems GTG was either shut down incorrectly, or it is still running on another computer you synchronized its data folder with, as the process ID (the number) was not found among running processes on this computer. If the latter, close GTG on both machines, synchronize the data, then launch GTG. [ Launch anyway ] [ Close ]"
* The smarter approach: storing the hostname along with the PID to determine if GTG is running on a different computer (prompting the dialog above), or if it's just a dead process ID from this computer that can be safely and silently ignored.

**Comment by diegogangl** [comment]
This is done-ish. We now look for the GTG process with a more robust method. I didn't do the hostname part though, I don't have another PC so I'm not sure how to test that feature.

**Comment by nekohayo** [comment]
Yeah, if you don't have a second testing computer, short of writing a fake hostname into the file to force GTG to go "wait this lock file is from a computer that is not me?", I guess the only other testing approach would be to use a virtual machine (or for me to test it out whenever I get to set up GTG git instances on multiple machines here)...

**Comment by diegogangl** [comment]
Hum, manually changing the file could work. It only has to refuse to start after all

**Comment by leio** [comment]
Why do we need anything like this at all with GtkApplication uniqueness?

**Comment by nekohayo** [comment]
That's a good point, I totally forgot that GtkApplication provides that (which didn't exist back in the PyGTK2 days), so that could be the better fix if Gtk doesn't depend on some similarly silly lock file concept. You lose the network transparency though, but I guess not that many people use GTG on two computers synced by Unison (until I document that trick, that is :P)

**Comment by diegogangl** [comment]
Lol I forgot about this issue completely. Yeah, GtkApplication handles this and all the PID-related code was nuked when I ported. Closing this for now

@nekohayo shouldn't we do network-syncing via the backends system?

**Comment by nekohayo** [comment]
> shouldn't we do network-syncing via the backends system?

I would need to see proof that gtgonline works and that it works "bulletproofly" ;)
