### ISSUE TITLE
Search fails when the input is empty (after searching)

### ISSUE THREAD

**Issue by diegogangl** [getting-things-gnome/gtg#221]
This is the error that comes out:

```
WARNING - browser:on_search:436 - Invalid query '' : 'Query is empty'
```

Also the search field should be cleared when closing the search bar.

**Comment by nekohayo** [comment]
I would add that, for performance reasons, the app should never run a search for something under 3 characters. Triggering a search only once you have typed more than 2 characters typically yields immense performance improvements, from my previous dev/QA experiences. Additionally, if the filtering is not done by GTK or some very efficient mechanism, we should avoid spamming it with requests by having the search trigger after a typing inactivity timer (ex: 250 miliseconds, with each keystroke resetting the timer).

There's also the question of if a search is cancellable (if the performance is bad enough that it takes more than half a second for a thousand items), but I suspect that would be a much more complicated system to implement (maybe it's already implemented, I don't know).

**Comment by diegogangl** [comment]
> I would add that, for performance reasons, the app should never run a search for something under 3 characters.

I like that except for how it's going to work with CJK languages. Let's say someone wants to search for "summer" in japanese, that would be 夏. It's a single character (tho I think it's two-byte).

> Additionally, if the filtering is not done by GTK or some very efficient mechanism, we should avoid spamming it with requests by having the search trigger after a typing inactivity timer (ex: 250 miliseconds, with each keystroke resetting the timer).

Apparently it's all python (`core/search.py`)

> There's also the question of if a search is cancellable (if the performance is bad enough that it takes more than half a second for a thousand items), but I suspect that would be a much more complicated system to implement (maybe it's already implemented, I don't know).

I think a better approach would be to make search lightning fast so that never happens :)
