### ISSUE TITLE
Higher resolution versions of the logo / icon

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#246]
The current icon was designed by [Kalle Persson](http://kallepersson.se/) and committed 11 years ago [here](https://github.com/getting-things-gnome/gtg/blob/master/data/icons/hicolor/svg/gtg.svg) (source design file). Even if I find it a bit "too square-shaped" for my tastes (vs a real-world clipboard having a "portrait" aspect ratio), I always liked that icon and I think it still looks good today even after GNOME's move to "semi-flat" simplified/non-skeumorphic icon styles (see [here](http://jimmac.musichall.cz/blog/2018-07-18-detail-considered-harmful/) and [here](http://jimmac.musichall.cz/blog/2019-01-23-the-big-app-icon-redesign/)). It's as if it was designed to be flat-enough "before flat was a thing".

I just wish there were **higher resolution versions** of the GTG icon, for HiDPI desktops and for project marketing. Beyond the pixel-perfect super-small versions, it stops at the ["pixel-perfect" 48x48 SVG version](https://github.com/getting-things-gnome/gtg/blob/master/data/icons/hicolor/scalable/apps/gtg.svg), but I think it would benefit from at least a 128x128 version, and maybe some more detailed 256x256, 512x512... if anyone is interested, see also:
* https://developer.gnome.org/hig/stable/icon-design.html.en
* https://developer.gnome.org/hig/stable/icons-and-artwork.html.en
* https://blogs.gnome.org/tbernard/2019/12/30/designing-an-icon-for-your-app/

So... up for grabs for icon designers passing by, if any.

If the icon is only expanded and not completely redesigned, I definitely would like us to retain the existing pixel-perfect low resolution versions (because they look great and they're "already there" anyway) in addition to eventual high resolution versions. Pixel-perfect versions are also still [highly valued by elementary](https://blog.elementary.io/gnomes-new-app-icons-drop-pixel-precision-and-hinting/).

-----
Note: I'm not sure how it goes from that single SVG file to multiple rendered versions (in the parent directories), i.e. if that's an automated process or if it's simply manual exports from Inkscape (presumably so).

**Comment by diegogangl** [comment]
Some notes:
- Colors need to be updated to the current guidelines
- The icons needs to have less detail
- It also needs to be adjusted to a grid
- We also need to have a symbolic icon
- External shadows need to be removed (they are applied via code)

The App Icon Preview app lets you export icons from a svg file:
https://flathub.org/apps/details/org.gnome.design.AppIconPreview

It can also autogenerate development icons, which are nice to have.

The new icons guidelines:
https://developer.gnome.org/hig/stable/icon-design.html.en

**Comment by nekohayo** [comment]
That's _if_ you're a huge fan of the simplified icon style introduced in GNOME 3.32; I'm not and I tend to prefer a _little_ bit more detail, but I'm probably an old fart ;) however, in all cases, even _if_ someone were to propose a visually superior "flatter" icon, I believe it would still need to offer various pixel-perfect (grid-aligned) versions, like the elementary project [pointed out in their blog post](https://blog.elementary.io/gnomes-new-app-icons-drop-pixel-precision-and-hinting/)...

**Comment by diegogangl** [comment]
We don't have to go full flat, I meant something simpler like the new contacts icon.
Here's a quick iteration of what I had in mind:

![gtg_idea](https://user-images.githubusercontent.com/264829/75082798-2653c900-54f4-11ea-96ef-c2041e3a41a2.png)

**Comment by diegogangl** [comment]
Another idea, closer to the old icon:
![gtg_idea_02](https://user-images.githubusercontent.com/264829/82718579-a3204b80-9c79-11ea-983f-138fb2908de3.png)

Also tried making a symbolic icon:

![gtg_symbolic](https://user-images.githubusercontent.com/264829/82718609-d4991700-9c79-11ea-9f6c-48ee330acde0.png)

**Comment by nekohayo** [comment]
Those are pretty nice icons! The 1st one looks pretty clean visually, though the problem of course is that it doesn't reflect the "power" of GTG's non-linear nature, which I guess you're trying to convey in the 2nd (blue) icon... but how do they look at small resolutions? I don't have your SVGs so was only able to simulate by scaling to 32x32 with GIMP (a bit ridiculous, I know) and it really looked noticeably less "sharp" than the existing icon that has pixel-perfect variants. This is what GTG currently looks like on my panel, dash-to-panel (height+padding+spacing adjusted to allow icons to fit exactly 32x32), this is my "benchmark":

![Screenshot from 2020-05-24 10-26-41](https://user-images.githubusercontent.com/479401/82756763-2476fb80-9daa-11ea-86d6-116b1141a404.png)

**Comment by diegogangl** [comment]
Aight, I got this sucker gridded and following the template.

Here's the screen from the icon preview app:
![screen](https://user-images.githubusercontent.com/264829/83956608-52dae900-a836-11ea-85ba-1186bfa7cbbf.png)

Also, an alternative using brown instead of Blue:
![screen-2](https://user-images.githubusercontent.com/264829/83956614-5bcbba80-a836-11ea-8134-59b4e2488745.png)

This is how the nighlty icon would look:
![org gnome GTG Devel](https://user-images.githubusercontent.com/264829/83956624-743bd500-a836-11ea-859e-3780be304077.png)

Here's the updated symbolic (at ~16x16):
![gtg-symbolic](https://user-images.githubusercontent.com/264829/83956646-b9600700-a836-11ea-9f27-ffa1053ceef9.png)

Here's the icon exported at 32x32 so you can test it in the dock:
![gtg_32x32](https://user-images.githubusercontent.com/264829/83956656-cb41aa00-a836-11ea-9f89-eb4102b10f12.png)

**Comment by nekohayo** [comment]
Those look pretty cool, though not as sharp as the original 32pix icon (although you designed/pixel-aligned it to a 32x32 pixel grid?), the new one does feel "fuzzy" on the panel, not as crisp for its inner contents, and the blue/brown sides are barely visible. Comparing the old and the new at 32x32 on the panel:

![Screenshot from 2020-06-06 21-08-23](https://user-images.githubusercontent.com/479401/83957952-6425f480-a83a-11ea-8757-5869e4ae8020.png)

Zoomed (without interpolation), we can see the too-thin margin problem more clearly:

![Screenshot from 2020-06-06 21-08-23 zoomed](https://user-images.githubusercontent.com/479401/83957959-73a53d80-a83a-11ea-8c59-ca0c820e8452.png)

I know I'm setting the bar pretty high here. Ye olde pixel-perfect icon is very hard to beat for sharpness ;)

**Comment by diegogangl** [comment]
New versions better aligned and with more space on the sides:

128x128:
![gtg_128x128](https://user-images.githubusercontent.com/264829/84580673-5a0e7380-adaf-11ea-856f-f2a9a40decc7.png)

32x32:
![gtg_32x32](https://user-images.githubusercontent.com/264829/84580674-5bd83700-adaf-11ea-88de-369a163c0904.png)

Also, I've always forgotten to add the source:

[org.gnome.GTG.Source.zip](https://github.com/getting-things-gnome/gtg/files/4775629/org.gnome.GTG.Source.zip)

**Comment by bertob** [comment]
Took a quick stab at putting @diegogangl's icon on the tall base shape:

![image](https://user-images.githubusercontent.com/1908896/86818498-bf8c1200-c086-11ea-8cc9-e2e02e684333.png)

**Comment by diegogangl** [comment]
That looks good! Interesting how the straight borders are making it looks less wonky. I'd imagined straight + curved would look worse. Could you share the svg?

**Comment by bertob** [comment]
Here you go: [org.gnome.GTG.zip](https://github.com/getting-things-gnome/gtg/files/4893598/org.gnome.GTG.zip)

The important tihng with nested border radii is that they get larger as you go outwards, so the border's thickness looks even all around. That's why this looks more "natural" than having them all have the same radius.

**Comment by diegogangl** [comment]
> The important thing with nested border radii is that they get larger as you go outwards, so the border's thickness looks even all around. That's why this looks more "natural" than having them all have the same radius.

Nice trick, thanks!

Added a bit more padding to the content and made the clip stick out a bit more. Mostly bike shedding at this point TBH
I think this icon is ready to go in. What say you, @nekohayo?

![icon](https://user-images.githubusercontent.com/264829/87102337-ff3e2f80-c227-11ea-8106-99005135e8e0.png)

**Comment by Exalm** [comment]
Since there was a question in IRC, here are exported icons. These are ready to use.

[org.gnome.GTG.zip](https://github.com/getting-things-gnome/gtg/files/4939828/org.gnome.GTG.zip)

**Comment by nekohayo** [comment]
So... from what I could tell by trying out the icons on a panel/dock, and in the app grid/icon view, they look okay, though I still miss the level of crispness and detail of the existing icon at some of the small sizes. The new blue clipboard backdrop material still feels so thin and borderless that I tend to just see a white rectangle when looking at it from an arm's length on my 24" monitor, at 32px size in particular (same thing with my laptop screen); the old icon also seems mostly white but _somehow_ it managed to have a bit more of a better visual delimitation, I don't know why exactly. That said, while the old icon excels at 48px and below, the new icon is able to fill the medium-to-high range (48 to 128+) fairly well, since it's not bound to exact pixel values... so I guess that's a noteworthy aspect of it.

I wonder if something can be improved further on the blue border material for contrasting with the surroundings, or if that's the best we can do. In any case, even if no further refinements are possible, I guess it'd be good enough to accept and merge, there are more critical things in life than obsessing about an app icon so I don't want to be stop energy for you folks :)
