### ISSUE TITLE
Fix the traceback catcher code/GUI, figure out what to do with Apport crasher bug reporting support

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#247]
In /GTG/gtk/crashhandler.py:
1. at the very end of the file, there is a mention (and URL) of LaunchPad for bug reporting. For general bugs, it should point to GitHub (or eventually GitLab). I was thinking of simply going ahead and rewriting that translatable string and pushing a fix right here and now (and take the opportunity to remove the URL from the translatable part, replace it by another variable for security so that the URL can't change based on translation files; by the way there is a way to have more descriptive gettext variables than "%s" but I don't quite remember what it was...), however...
2. the code has support for Ubuntu's [Apport](https://wiki.ubuntu.com/Apport) bug reporting tool, and that translatable string mentions it. I'm presuming it works well, but I'm wondering if this could be plugged into GitHub or Gitlab, somehow, or if it remains strictly a LaunchPad/Ubuntu-specific tool, like ABRT is to Fedora's bugzilla... presumably it is harmless to leave it there, however the problem is that crasher reports would go to LaunchPad, which we have little interest in looking at (unless we make it a policy/exception to look at crashers there).

**Comment by diegogangl** [comment]
Does the crash handler actually work? I've been trying to trigger it with `os.abort()` and I don't get any reaction.

**Comment by liberforce** [comment]
> Remove LaunchPad mention as being the "official" bug tracker

There's also `README.md` that references it.

**Comment by diegogangl** [comment]
Thanks for spotting that :+1: I nuked both references to launchpad and also the old site

**Comment by diegogangl** [comment]
I've removed the crash handler since I couldn't trigger it and looking at the code it doesn't seem to work with GtkApplication at all.

I also updated the info in the info module, though I found this and don't know what to put instead:

```
EMAIL = "gtg-contributors@lists.launchpad.net"
```

**Comment by liberforce** [comment]
I think at this point, if you're switching to GitHub and don't plan to have a mailing list (people just tend to ask question in the bug tracker anyway), you could just remove it, and ask to close the existing mailing list. The difference is that people would need to have a GitHub account to ask for help, which might be a problem for some people.

**Comment by nekohayo** [comment]
Oh, interesting... I hadn't realized the crash dialog wasn't triggering in the git version (or maybe we just haven't discovered how/in which cases it gets triggered) but it definitely was/is triggering in 0.3.1. I'm a bit worried of seeing that code get thrown out completely though, because it was a pretty well-architected system, in an ideal world I would have preferred to see it proven working in the git version or to see it fixed up (if needed)... but since I'm not maintaining the code, I guess I can't really complain, just share my opinion ;)

**Comment by liberforce** [comment]
Maybe it's possible to git bissect to find when it stopped working and save that code then?

**Comment by diegogangl** [comment]
> Maybe it's possible to git bissect to find when it stopped working and save that code then?

I went back all the way to 98890d4c5f2a61b6426b6bcf048f24d8dd56e8e8 but it's still not coming up when I SIGTERM the process or use os.abort(). I though this wasn't working with GTKApplication because it was expected to be imported before `Gtk.main()` but it seems it depended on some GTK2 implementation detail.

**Comment by liberforce** [comment]
Are you able to trigger it like nekohayo on 3.0.1 ?

**Comment by liberforce** [comment]
If your can trigger the crash dialog on 0.3.1, maybe the bissecting could be automated to find the relevant commit?

**Comment by nekohayo** [comment]
It will only trigger if you encounter a Python traceback (as far as I know), 0.3.1 won't even trigger it if you kill it with SIGSEGV, SIGKILL or SIGTRAP for example. The reason why SIGTERM triggers it on 0.3.1 is because 0.3.1 tracebacks on exit for unrelated reasons, as you can see below ;)

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/app/lib/python2.7/site-packages/GTG/plugins/bugzilla/notification.py", line 64, in uinit_pynotify
    pynotify.uninit()
AttributeError: 'module' object has no attribute 'uninit'
```

(probably was reported among those in https://github.com/getting-things-gnome/gtg/issues?q=is%3Aissue+uninit+is%3Aclosed but whatev')

Maybe you could forcefully raise an uncaught Python "exception" somewhere in the code to see if that triggers it on your end? I'm suspecting that would be an easy way to test that this code is functioning.

**Comment by diegogangl** [comment]
Nope. I went back to the old commit, raised an `AttributeError` in the browser window's init and nothing came up :/

**Comment by diegogangl** [comment]
Closing this, the catcher has been dead and removed for a while (I don't remember when it happened TBH)
