### ISSUE TITLE
cannot run, python-gnomekeyring deprecated

### ISSUE THREAD

**Issue by pwr33** [getting-things-gnome/gtg#251]
> Setting XDG vars to use default dataset.
Traceback (most recent call last):
  File "./GTG/gtg", line 59, in <module>
    from GTG.backends import BackendFactory
  File "/home/pwr/cbuilds/gtg-master/GTG/backends/__init__.py", line 31, in <module>
    from GTG.backends.genericbackend import GenericBackend
  File "/home/pwr/cbuilds/gtg-master/GTG/backends/genericbackend.py", line 35, in <module>
    from GTG.tools.keyring import Keyring
  File "/home/pwr/cbuilds/gtg-master/GTG/tools/keyring.py", line 21, in <module>
    gi.require_version('GnomeKeyring', '1.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GnomeKeyring not available

replacement libsecret uses different function names
not running on debian buster xfce

reason I am trying to run dev version is because version in repo has the wrong dbus endpoint name to communicate with gnotes, gnotes communicates with gtg OK except expects some response from gtg I think.

> While Gnote has a compatible API to Tomboy for its remote control, it uses a distinct namespace (org.gnome.Gnote). Current code uses namespace org.gnome.Tomboy for both Gnote and Tomboy (and that's the reason why Gnote integration fails).

**Comment by diegogangl** [comment]
Hey, thanks for reporting. We have to look at what Gnome keyring was being used for and see if we can replicate it with libsecret.

**Comment by pwr33** [comment]
reinstalled the debian gtg package after discovering the git master problem with gtg, and now the dbus integration is working OK, seems a nice trio, getting things gnome, hamster and gnotes.  Only extra thing I did I think was build hamster from github and install a few dependencies.

**Comment by pwr33** [comment]
Runs OK now, thanks, I see the hamster and gnote plugins are no longer working, (not that they were perfect anyway) may get around to having a look at them to see if I can get them working, think I want the gnotes interface to work differently and maybe a few bugs in the hamster interface.
Can all be used in isolation anyway.
