### ISSUE TITLE
Ctrl+W / Esc to close the task editor only bound to the last-opened instance of task editor windows

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#263]
Probably a trivial fix, if possible to get it fixed for 0.4 for consistency with previous releases it would be nice, but not a showstopper otherwise.

**Comment by diegogangl** [comment]
That's weird, it works here. And it's actually added along esc, maybe there's a conflict in your desktop?

``
('app.editor.close', ['Escape', '<ctrl>w'])),
```

**Comment by nekohayo** [comment]
OK, found the root cause that made me think it wasn't working: turns out it only works "once".

If you open two or more instances of task editor windows, no matter which of them is focused, the window closing keyboard shortcut will be bound to the "last opened" of those windows. So not only does this work "only once if your last opened window is the one in focus", but if you focus another window to close instead, it will _still_ close the "last opened" window—therefore the wrong window. That is... special :laughing:

**Comment by nekohayo** [comment]
That's an elegant (and much more complicated than I would've expected) fix, I wouldn't have imagined that to be the cause! Great job.
