### ISSUE TITLE
Window sizes (and positions) are not remembered anymore

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#264]
The git version has regressed on a couple of points:
* The Main window's size is not remembered anymore
* The task editor window sizes (per-task) are not remembered anymore

0.3.x also used to remember the position (X, Y) of each window, to restore them on startup or when each task editor window is requested/shown; however one must make sure to set the position properties before calling show() or show_all() on those windows.

**Comment by diegogangl** [comment]
This is a weird one too. It doesn't remember sizes when I run it from the script, but it does when running from the flatpak :thinking:
