### ISSUE TITLE
Keyboard shortcuts ("accelerators") should be indicated in the hamburger menu entries

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#268]
Not sure if GtkMenuButton allows this like the traditional menus or the contextual menu, but assuming it does, the following could benefit from being indicated:

- Toggle show/hide tags sidebar: F9
- Help: F1
- Quit: Ctrl+Q

**Comment by diegogangl** [comment]
I was hoping to get to this soon. AFAIK accelerators shouldn't be shown in menus. The pattern to use instead is the Shortcut Dialog, which shows all the hotkeys in the app.
(open nautilus and look for the Keyboard Shortcuts option in the menu for an example)

**Comment by nekohayo** [comment]
Yeah if that's the new official way of doing things these days, I guess the standard shortcuts cheatsheet dialog could do the job.
