### ISSUE TITLE
Remember the task window size

### ISSUE THREAD

**Issue by tkdchen** [getting-things-gnome/gtg#273]
Hi, sometimes I feel the default task window size is too small for me to view the content, and then I enlarge the window manually. However, when I open the task again, the window size is still the default and I have to enlarge again. Could you please make GTG be able to remember the window size, or make the default window size bigger? Either is ok for me. Thank you very much.

**Comment by nekohayo** [comment]
This is odd, Diego closed this issue #264 yesterday with commit bc0b158 ; you still experience this on git master?

**Comment by tkdchen** [comment]
@nekohayo I haven't synced my local repo when I wrote this issue just now. The change works well. Thanks. I'll file another issue I experienced against the master branch.

**Comment by tkdchen** [comment]
Oh, that's the issue 271.
