### ISSUE TITLE
Performance: Searchbar searches live on every character being typed

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#281]
Observation: 0.4's searchbar searches "live" everytime you type a character in it.

~~Theoretical supposition (to be verified):~~ performance will be crap, as soon as you have more than a handful of tasks. ~~Note that I have not bench-tested this (yet), but I _presume_ performance will be horrible, unless the search is only something like a Gtk TreeModel filter and doesn't touch the storage backend, but I doubt that's the case...~~

Ways to avoid triggering performance issues:
* If keeping a (nearly) "live" filtering feature:
  * Do not run a search if 0 < search_query_string_length < 3 (but if 0 characters, that counts as "clear/reset the search"). There is no reason to search for something less than 3 characters, no significant words or acronyms are made of 2 characters and it just returns a ton of results that impair your search performance (if your search benefits from "filtering existing results" in its algorithm). This alone won't be enough, but it probably will help a little.
  * Introduce a timer-based activation algorithm like what I'm proposing for parsing tags in the task editor in #270
* The nuclear option: "don't do live search at all". In this case, put a "Search" button between the search field and the "Save search" button, and also respond to the Enter/Return keyboard shortcut, but don't trigger the search until the user explicitly says so. This is less "sexy" than semi-live filtering, but is simultaneously the best-performing and easiest-to-implement approach.

**Comment by diegogangl** [comment]
Live search is used everywhere in Gnome, and frankly it's much better than having a button. 

> There is no reason to search for something less than 3 characters, no significant words or acronyms are made of 2 characters and it just returns a ton of results

仕事, 夏, 夏休み, are all valid words that someone could search for. I think we should try the timer to avoid spamming.

**Comment by nekohayo** [comment]
Crap, I totally forgot about asian/ideographic languages!

As for live search being common: I don't know of many examples of apps that do that and are performant for anything other than a linear list of item titles (vs a treeview of XML thingies with descriptions inside those thingies)... but if it can be made super fast, and/or with timer-based mitigation, if someone wants to go through the trouble of implementing that vs a static search, eh why not!

**Comment by nekohayo** [comment]
I can confirm, after months of using 0.4, that live search performance is indeed crap as predicted.

My conclusion is that either live filtering search should be disabled in favor of a search that relies on the Enter key (absolute best performance and simplest implementation, but slightly less cool-looking), or it needs to have a timer-based approach that resets the search trigger timer to at least 500ms of delay each time a keystroke happens (and maybe even 1000ms if the number of characters is < 4). Anything faster than a 500ms delay will hammer the search engine and cause exponential performance problems.

A timer-delayed search trigger approach will be a middleground between "worst performance" and "best performance", yielding faster search results than the current fully-live search. It is a fancy-looking UX in exchange for higher code complexity and slightly lower performance.

**Comment by diegogangl** [comment]
Technically the search uses the same method as changing tags (applying a filter in liblarch).  We could add a button to work around the speed issue while we fix the underlying problem

**Comment by nekohayo** [comment]
I did a quick test to try out my theory today: instead of typing into the search bar, just paste a word into it with Ctrl+V. The result proves my theory: search is near-instantaneous and refinements (further typing after the initial search) are also near-instantaneous, even if I have over a thousand tasks. So while not eliminating the underlying performance issue completely, a logarithmic timer-based approach (i.e. longer timer before searching if there are less than 4 characters, shorter timer as the number of characters increase) would already do wonders for symptom mitigation.
