### ISSUE TITLE
"Search" row in the tags sidebar can be confusing as a UI element

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#282]
This is a simple usability nitpick. We have a "Search" row in the sidebar that is clickable but doesn't do/show anything. Some potential ways to make it clearer:

1. Rename it "Saved searches". Theoretically we could make it so that clicking that row enables the searchbar, but we can't rely on the sidebar being shown/present so we always still end up having a search button in the headerbar anyway...
2. Don't show that row unless saved searches are present.

**Comment by diegogangl** [comment]
Looks like disabling the row or hiding it would involve quite some code, and we're nuking all that when we start using listboxes anyways. Close this issue if you think it's looking good enough
