### ISSUE TITLE
Change default font for task editor

### ISSUE THREAD

**Issue by tkdchen** [getting-things-gnome/gtg#289]
The task editor's default font size is too small for my eyes. I'd like to change it in some way, e.g. from preference to set default font. Could you please consider this? Or, an alternative option is to be able to change font size by `Ctrl-+`, `Ctrl--` or `Ctrl+mouse wheel`. Thanks.

**Comment by nekohayo** [comment]
I'm presuming you're talking about the "content" (i.e. what goes after the 1st line) text font size... isn't it inheriting the same font size as all the other GTK applications on your desktop though? If it's too small there, isn't it too small in other applications too? (in which case it might be a matter of changing the font scale setting in gnome-tweak-tool's "Fonts" section) i.e. why would GTG be different from other apps in that regard?

That said, on the other hand, I think the font size for the task's header (1st line) is a bit excessive in comparison, it could benefit from being a less bold and possibly a smaller font size (which would also make it less ridiculous when you rise the desktop's global font scaling setting)...

**Comment by diegogangl** [comment]
> The task editor's default font size is too small for my eyes. I'd like to change it in some way, e.g. from preference to set default font.

There's a setting for that in preferences (at least in master). Look for _task editor font_, you can change the font and the size there.

> That said, on the other hand, I think the font size for the task's header (1st line) is a bit excessive in comparison, it could benefit from being a less bold and possibly a smaller font size (which would also make it less ridiculous when you rise the desktop's global font scaling setting)...

Love me some ultrabold type.
The header is taken from the Gnome HIG. There's a bunch of mockups with headers like that, and I think 3.36 already has some dialogs with that style. We could do title-2, but I really like the impact it has now.

**Comment by tkdchen** [comment]
> There's a setting for that in preferences (at least in master). Look for task editor font, you can change the font and the size there.

Thanks. It works like a charm. I'll close this issue.
