### ISSUE TITLE
Purge email addresses from info.py and AUTHORS file?

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#291]
GTG/core/info.py and the AUTHORS file are duplicating information in two places. To me, it seems like a lot of manual (and therefore arguably pointless) work to maintain, much like the manual "ChangeLog" file.

So this brings me to these questions, perhaps @ploum can weigh in and tell me if I'm being too radical here:

* Can we simplify this a lot and do something like what I did in Pitivi, that is https://gitlab.gnome.org/GNOME/pitivi/-/blob/master/pitivi/dialogs/about.py#L64 and the upper part of https://gitlab.gnome.org/GNOME/pitivi/-/blob/master/AUTHORS ? I'm thinking of a nearly empty AUTHORS file that points to the about dialog's code (info.py) or something, maybe list "Current maintainers" and "Previous maintainers" and that's it, for the rest we could point to:
  * git blame
  * git shortlog -s -n
  * https://www.openhub.net/p/gtg/contributors?sort=latest_commit or https://www.openhub.net/p/gtg/contributors?query=&time_span=&sort=commits
  * https://github.com/getting-things-gnome/gtg/graphs/contributors
* Can we also just remove everybody's email addresses from those files? I'm thinking it's just an invitation to be harvested for spam or to be emailed directly by random users (instead of them going through the bug tracker), also I suppose many email addresses become invalid over the years.
* Should the ChangeLog file be killed in favor of just linking to the list of milestone-targetted closed issue tickets? Who has time to maintain this thing by hand?

**Comment by ploum** [comment]
Do (wtf) you want ;-)

**Comment by nekohayo** [comment]
Fixes merged.
