### ISSUE TITLE
Figure out if we need to rename or duplicate the .desktop file for DBus, GNOME Shell, Flatpak and development/nightlies variants

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#293]
Turning a chat with @leio into an open question for whoever has time to investigate this someday, because I feel like if I just use "git mv" to rename the desktop file and then update setup.py, I may make the wrong choice.

> Diego: "In the major version following GTG! 0.3, the GTK+ user interface (and all other user interfaces) will be 100% through DBus."
> Diego: ha, we accidentally accomplished this with the GtkApplication port, since it exposes actions to dbus
> Mart: we should rename the desktop file, so we don't have to do this once there are users again; the desktop file should be the same as the GtkApplication (unsure about the devel suffix in those cases)
> Jeff: crap, in my branch I renamed "gtg.desktop" to "GTG.desktop"
> Mart: it needs to be the same as dbus service name
> Mart: and changing it changes what app it is (gnome-shell favorites goes away, etc); hence the suggestion to make sure that change goes into release
> Mart: so once people install revived thing, they won't have a new app with 0.5 :P
> Jeff: where do I check what is the exact name it should be
> Mart: there's the Gtk.Application application_id and app_id passing
> Mart: it should be that
> Mart: look for app_id/application_id in GTG/gtk/application.py
> Mart: I'm not sure how the devel profile should be handled in that; I think there are various examples for that though, as many set things different for flatpak nightlies
> Mart: epiphany, et al
> Jeff: Pitivi would probably be my inspiration, iirc it has a global in_devel variable
> Jeff: application.py in GTG says: ``app_id = f'org.gnome.GTG{"devel" if debug else ""}'```, so how does that translate to the .desktop file?
> Mart: org.gnome.GTG.desktop, with the open question of what would be done in case of devel
> Jeff: do apps provide a second "not-shipped/installed" .desktop file for their devel versions?
> Jeff: there was something about devel-specific app icons, dunno if this is still a thing
> Mart: it's more about "nightly" there

**Comment by diegogangl** [comment]
This depends on getting the Meson work done, since it's all generated through it
