### ISSUE TITLE
Editing Saved searches

### ISSUE THREAD

**Issue by diegogangl** [getting-things-gnome/gtg#302]
@jscn brought up an interesting issue: we don't have a way to edit searches. While searches are quite simple right now, we might want to have more involved searches in the future. Like searching for overdue tasks, tasks that start in X date, etc. However this isn't decided, and we should also consider if we want to add this feature right now or wait until search becomes more complex and it  has a bigger impact on the workflow.

Also needs design for the dialog.

**Comment by IcedQuinn** [comment]
Could add a plain text field showing what the search query is in the edit window. Not as nice of a solution as a fancy query editor (as in MyLifeOrganized) but would at least allow editing it.

Right now you can assign a custom name to the search via edit but not see what it's actually searching for.

**Comment by nekohayo** [comment]
> Right now you can assign a custom name to the search via edit but not see what it's actually searching for.

Sounds like the editing dialog should have two fields then, one for the nickname of the search, and one for the search query; in the sidebar UI, the nickname would be shown, but we could have a GtkTooltip associated with it that reveals the query (if different from the nickname) when the mouse hovers it...
