### ISSUE TITLE
Bad stock icons for Ok/Cancel button in plugin configuration

### ISSUE THREAD

**Issue by Cogitri** [getting-things-gnome/gtg#313]
See the following screenshot:

![image](https://user-images.githubusercontent.com/8766773/82141427-081d1100-9836-11ea-8ac1-cd8dc5462e96.png)

**Comment by nekohayo** [comment]
That's right, I had seen this small issue (which I think is seen in other plugins too?) but had not reported it because I forgot and it was so trivial compared to the rest ;)

**Comment by diegogangl** [comment]
The UI should be updated, but I think fixing the texts is enough for now

**Comment by Cogitri** [comment]
FWIW, fixed by commit 2143d904f2e7076099f477540348bc6552817f20
