### ISSUE TITLE
Calendar closes in "Due on" selection when changing the year/month

### ISSUE THREAD

**Issue by Cogitri** [getting-things-gnome/gtg#314]
When I open the calendar by clicking on "Due on" and try to change the year/month by clicking the left/right arrows at the top of the calendar the calendar closes, so I have to click on the "Due on" field again to select a date in the previous/next year/month.

Using latest git version for testing

**Comment by diegogangl** [comment]
This is because Gtk calendar is firing the day-selected signal when the month is changed.  I think the best solution would be to remove the line that closes the popup on day selection. The popup closes when we focus out anyways, so the workflow would be select a day -> click somewhere else

**Comment by Cogitri** [comment]
Ah yes, I think when the month changes it automatically selects current day - 1 month

**Comment by diegogangl** [comment]
The day selected thing was an older bug in the end, this was caused by the calendars stealing focus from the input

**Comment by Cogitri** [comment]
Ah great, thanks for looking into it
