### ISSUE TITLE
 gtg_new_task presents window but does not give it focus

### ISSUE THREAD

**Issue by twaugh** [getting-things-gnome/gtg#32]
When using GNOME (don't know about other desktops), running gtg_new_task either from a terminal window or from a custom keyboard shortcut presents the new task window but does not give it focus.

**Comment by izidormatusov** [comment]
I know, this sucks :hankey: I've tried to solve this bug before, but I couldn't find a way how to do it. When asked on ubuntu developers mailing list, I haven't got any answer:
https://lists.launchpad.net/unity-dev/msg00455.html

I'm sorry, it would be nice to have this fixed but I don't think we're able to fix it. It's the way Unity works.
