### ISSUE TITLE
Animate opening/closing the sidebar

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#327]
This is really NOT important so shouldn't be targetted to a particular milestone, it is purely eye candy for the "wow" factor, but since the sidebar can be toggled on/off with F9, it would be cool if it did so with a sliding animation from/to the left of the main window.

I suppose this is done by putting it in a [GtkRevealer](https://developer.gnome.org/gtk3/stable/GtkRevealer.html). There's some [example pythonic code](https://www.programcreek.com/python/example/88433/gi.repository.Gtk.Revealer) for this.

**Comment by nekohayo** [comment]
So, unless someone comes up with a magic hack (or spends a lot of effort on this, including potentially making use of libhandy), or we switch to a non-resizeable sidebar (i.e. not using Gtk Paned) it turns out this is really far from trivial.

For posterity I have made [a commit](https://github.com/nekohayo/GTG/commit/5c6463b57a3d97) with my experiment that will sit in [this branch](https://github.com/nekohayo/GTG/commits/animated_sidebar_revealer_experiment) in case someone smarter wants to attempt this, but in practice until that happens then GTG cannot have animated sidebars.

If you look at it with the GTK inspector, you can see I successfully inserted the Revealer in the hierarchy:

![GTG sidebar revealer in paned experiment](https://user-images.githubusercontent.com/479401/83296951-a78bbd80-a1bf-11ea-8df1-4b3645415a7a.png)

And the sidebar's contents can be toggled on/off... but the problem is that the animation does not occur, and the GtkPaned does not collapse.

Here's a discussion I had with GTK developers for the full explanation:

> * me: hey folks... Is the presence of a GtkRevealer in this hierarchy supposed to work?  Window » Box » Paned » Revealer on the left, Box on the right of the paned
> * me: 'cause it "seems" to mostly work, but when I toggle the revealer's "reveal-child" property to True/False using the Gtk Inspector, it does not animate the transition (I set the transition type to SLIDE_RIGHT), nor does it collapse the paned
> * me: it's as if I was setting the child's visiblity to True/False, except that it does have the animation delay... just not the animation nor the collapsing, just the hiding/showing
> * me: and if I set the Revealer's "visible" property to False/True, it does hide the thing including collapsing the paned
> * baedert: there is an open bug about that iirc
> * me: oh this is a bug?
> * me: how do other apps handle their sidebars then?
> * mclasen: one persons feature is another persons bug
> * mclasen: paned and revealer were not made to cooperate in this way
> * Company: the handle in a paned is set to the amount of pixels from the left
> * Company: if a GtkSomeWidget on the left does some weird dance with its size request, it doesn't care too much
> * me: but if so wouldn't I see the revealer "slide" the content "inside" the paned?
> * me: right now I just see it as if it was a show/hide but with 250ms delay
> * Company: the revealer places the content into its allocation probably
> * Company: and as long as it's getting its full size allocated, so be it
> * Company: setting the revealer's halign would probably change that
> * me: apparently not, if I set halign to START instead of FILL, the revealer's contents are cropped but the animation still doesn't manifest itself
> * Company: well, the animation should happen in that the revealer allocates less and less space to its child
> * Company: the paned still won't care of course
> * me: not that I can see
> * mclasen: you don't really want a revealer here; it would be better to just animate the paned position directly
> * Company: that doesn't sound too good either
> * me: I didn't know you could do that?
> * Company: gtk_paned_set_position()
> * Company: or something
> * mclasen: just a matter of writing the code
> * me: you mean calling set_position 60 times per second manually? I'm going to guess that's going to end badly :)
> * Company: it will the moment something else influences what's going on
> * Company: other than that it's exactly how animating a paned would look
> * Company: but GtkPaned is a GTK1 widget and GTK1 widgets have APIs that cannot be animated really
> * me: what would be the "equivalent" to a paned for "user-resizeable divider container of two things that don't overlap" that is revealer-friendly?
> * Company: a modern widget
> * Company: a modern widget also wouldn't need to be "revealer-friendly" because it'd support animating out of the box
> * Company: mostly it'd be a widget that doesn't think about the handle position as an integer pixel value
> * me: OK but does such a widget exist, or "modern widget" implies it doesn't yet? :)
> * Company: no
> * Company: the correct way to animate *resizable* sidebars in GTK/Gnome is "don't"
> * Company: the other option is using a revealer but not a Paned
> * Company: i believe that's what libhandy does
> * Company: the leaflet (that's the name, right?)
> * me: would it be considered as a future gtk feature (i.e. should I file a wishlist RFE) or "nah never"?
> * Company: i would think somebody needs to implement it, i don't know if anyone curates a wishlist
> * Company: i think we just close all wishlist issues without activity
> * mclasen: after a while, measured in years
> * mclasen: so, you can file one, and you might get some comments and suggestions for attack the problem, but you are unlikely to get volunteers falling over each other to satisfy request
> * me: if leaflet is the widget for the situation... that makes me wonder: I assumed AdrienPlazas 's long term plan would be to merge libhandy into gtk somehow
> * me: I wonder if I'm guessing correctly or if that's absolutely not in his plans
> * AlexanderMikhaylenko: not all libhandy widgets are "generic enough" for GTK
> * Company: the libhandy situation can best be summarized as ¯\_(ツ)_/¯
> * AlexanderMikhaylenko: there will likely be a GNOME-specific (and elementary-specific too given that they picked up libhandy as well) library for GTK4 with the more GNOMEy widgets in there
> * Company: is it gonna be put into GTK3: no
> * Company: is it gonna go into GTK4? ¯\_(ツ)_/¯
> * Company: are parts of it gonna go into GTK4? ¯\_(ツ)_/¯
> * AlexanderMikhaylenko: well, arguably some parts are already in there :p
> * Company: is it gonna turn into a library of useful widgets? ¯\_(ツ)_/¯
> * Company: is it gonna be primarly about mobile use cases? ¯\_(ツ)_/¯
> * AlexanderMikhaylenko: that said, would be useful if you explain what you want to implement
> * AlexanderMikhaylenko: it's already not primarily about mobile use cases :p
> * Company: ¯\_(ツ)_/¯
> * AlexanderMikhaylenko: because depending on situation you might want HdyLeaflet here, HdyDeck or a transient sidebar widget that doesn't exist atm
> * me: mostly eyecandy (link to this bug)
> * AlexanderMikhaylenko: but... That's just GtkRevealer?
> * me: the existing UI has a sidebar in a paned on the left, and the contents on the right
> * me: the sidebar being resizeable
> * AlexanderMikhaylenko: ah, IDK if revealer would work inside paned
> * AlexanderMikhaylenko: but if it's paned, then you don't want libhandy in the first place
> * me: "not really" is what I found out above
> * AlexanderMikhaylenko: just make the sidebar non-resizable and use a revealer 🤷️
> * me: thanks for the advice folks
> * me: that does help me figure out what can and cannot be done ;)
> * AdrienPlazas: "the libhandy situation can best be summarized as ¯\_(ツ)_/¯" : Sadly yeah.
> * AdrienPlazas: Libhandy is mostly Alexander Mikhaylenko and me, well, mostly Alexander to be honest because of how much he works. I'd love to port some of its widgets to GTK 4, and either submit them to GTK 4 or have a GTK 4 version of libhandy, but for the moment we are very busy improving the state of our API, cleaning up and stabilizing what we developped over the last two years.

**Comment by leio** [comment]
I think the DzlDock* stuff from libdazzle could be used here.
