### ISSUE TITLE
Missing "Now" as a due date choice in the right-click menu

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#328]
Compared to GTG 0.3.1, GTG git is missing the "Now" due date choice in the right-click menu in the main window, just above the "Soon" choice. Not a huuuuge deal as there are other ways to set this, but it'd be nice to have back for consistency.

**Comment by indierodo** [comment]
[Here's for consistency](https://github.com/getting-things-gnome/gtg/pull/332)
