### ISSUE TITLE
setuptools requirement

### ISSUE THREAD

**Issue by indierodo** [getting-things-gnome/gtg#331]
I'm on Linux Mint 19.3 Tricia . Trying to install from source I also needed to `pip3 install setuptools` .  Only then, I followed [XioNoX's steps](https://github.com/getting-things-gnome/gtg/issues/242#issuecomment-619821939) and compiled succesfully.

$ pip3 install --user -r requirements.txt
```
ModuleNotFoundError: No module named 'setuptools'
```

Is `setuptools` needed in all setups, or was it something specific to my installation? Is it possible to add it to the requirements file?

**Comment by leio** [comment]
setuptools is going away with #330 and the installation instructions will need to be updated per #303 and others

**Comment by indierodo** [comment]
Thank you, looking forward to it. Let me know if I can help in any way.
