### ISSUE TITLE
Trying to run two GTG instances at the same time causes an uncaught GDBus error

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#333]
~~In the data/test-data/ folder, there are datasets, meant to be able to test various sample provided sets of data. I find that this would be useful, for example, to have a standard data set used for our marketing & documentation screenshots purposes (#274), instead of improvising them each time, we could have perfect standardized screenshots each time. So I tried running with the "bryce" dataset out of curiosity... and it broke my system, requiring a session logout+login. When you execute `./gtg.sh -s "bryce"` you get this:~~

When you try to launch two instances of gtg (it can be two instances of gtg git, or one of git and one of 0.3.1 in a flatpak, etc.), you get a nasty confusing traceback preventing the launch of the 2nd instance. When I tried launching gtg.sh while my 0.3.1 flatpaked version of GTG was already running, this is what I got (notice the references to Python 2.7 because of GTG 0.3.1):

```
Running the development/debug version - using separate user directories
Your data is in the 'tmp' subdirectory with the '' dataset.
-----------------------------------------------------------------------
2020-05-26 12:06:03,402 - INFO - cleanxml:openxmlfile:176 - No suitable backup was found
2020-05-26 12:06:03,405 - INFO - cleanxml:openxmlfile:176 - No suitable backup was found
2020-05-26 12:06:03,405 - INFO - cleanxml:openxmlfile:176 - No suitable backup was found
Failed to register: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Traceback (most recent call last):
  File "/app/lib/python2.7/site-packages/dbus/service.py", line 654, in _message_cb
    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
  File "/app/lib/python2.7/site-packages/dbus/service.py", line 246, in _method_lookup
    raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: DescribeAll is not a valid method of interface org.gtk.Actions
```
~~...and any subsequent attempt at running gtg.sh, even without a particular dataset, will fail with the same traceback, until you log out & log back into the GNOME session (I previously thought you needed a full reboot or to do a `systemctl isolate multi-user.target && systemctl isolate graphical.target`, but it seems a logout is sufficient)~~

~~For a while, I thought this only happens with the "bryce" dataset and maybe something in its config file was FUBAR, because it wasn't happening if I launched with -s "standard" (which was used for the old screenshots a decade ago, it seems; not the same thing as the default one). But then when I waited some minutes after using the "standard" dataset, it stopped working again, same kind of traceback. So… I don't know what causes this. I'm filing this in case someone smarter wants to have a go at investigating/solving this :)~~

**Comment by nekohayo** [comment]
In commit 7707cfa I fixed an unrelated cosmetic issue, the dataset argument name not being printed correctly, as you could see above:

`Your data is in the 'tmp' subdirectory with the '' dataset.`

It also fixes the fact that the bryce/xdg folder was copied into tmp/ instead of the bryce folder itself being copied into tmp/.

And for a short while, I thought this had even fixed my dbus traceback problem, but it didn't. That thing seems to be random (some race condition?) when it comes to triggering it... so keeping this issue open after all, because I still have no idea what triggers this exactly.

**Comment by diegogangl** [comment]
Seems to trigger if you run two gtgs at the same time.
The error comes from here: https://github.com/freedesktop/dbus-python/blob/master/dbus/service.py#L654 

In my Fedora box it uses Python 3.7 though. This might be python-dbus being obsolete

**Comment by nekohayo** [comment]
Can't believe I hadn't realized that to be the cause! Updated the description accordingly.

Reportedly, this happens even if the two versions you're trying to launch are git versions, so still worth fixing (i.e. not a case of "well it only affects 0.3.1").

In this case, GTG should somehow catch the error, and either provide a GTK error dialog with some clear explanation text that can be understood by humans, to the effect that you can't have two GTG instances running simultaneously (this is useful if GtkApplication doesn't let you "raise" the running application already), and/or allow it _only_ if using different datasets or different data storage & configuration folders, to avoid possible corruption.

**Comment by leio** [comment]
So the first running gtg has claimed the well-known dbus name (based on application ID) already, so dbus messages of course go to that.
The problem seems to be that the application uniqueness isn't working right with our GtkApplication and two same application IDs manage to continue running in their full GUI glory. That shouldn't happen.

**Comment by diegogangl** [comment]
This isn't actually happening anymore in git. It might be a problem if someone tries to run 0.3 alongside 0.4 for some reason but not for running a current GTG.
