### ISSUE TITLE
Add meson and ninja dependencies to README.md

### ISSUE THREAD

**Issue by jebins** [getting-things-gnome/gtg#339]
Hi,

I needed to install meson and ninja in order to "run the beast".
`pip3 install -U meson ninja`

**Comment by nekohayo** [comment]
Ah yeah that's the new build system that landed today. Will have to mention that in the README indeed. Makes much more sense (I think) to install it via distro packages rather than pip, though.

**Comment by leio** [comment]
a meson distro dep would automatically pull ninja in for you, so no strong need to mention ninja in that case

**Comment by Neui** [comment]
Couldn't this be closed since meson is now mentioned in the README since commit 19d1f25ffd608091a012e51c3d7180892d2ec203 (#391)?

**Comment by diegogangl** [comment]
Thanks for heads up @Neui !
