### ISSUE TITLE
Thoroughly document the multilingual dates and keyword parsing syntax

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#340]
An initial commit I've made in my own userdocs branch in my personal repo: https://github.com/nekohayo/GTG/commit/3b23e5b8

If @vansia43 likes it I could merge it to master.

Afterwards, potentially, subsequent work could include splitting it into some modular page that can be reused/included/cited/linked to from other pages, because that syntax is valid anywhere in the app, so both the Quick Add entry and the Task Editor window, the "Pick a date..." dialogs, and maybe elsewhere (?).

A starting point about the multilingual aspect was mentioned in https://github.com/getting-things-gnome/gtg/issues/243#issuecomment-623752476 too.

**Comment by nekohayo** [comment]
If anyone is curious to study the code that makes the magic work, it's https://github.com/getting-things-gnome/gtg/blob/master/GTG/core/dates.py ; particularly the [last third](https://github.com/getting-things-gnome/gtg/blob/master/GTG/core/dates.py#L310) of the file, which is more down-to-earth and understandable, particularly the "parse" method's description around [line 403](https://github.com/getting-things-gnome/gtg/blob/master/GTG/core/dates.py#L403).

**Comment by vansia43** [comment]
The suggested information makes sense to me. I think it is good to merge as you have indicated. 

I see a little editing update that I need to make, so more a note to self. I had "for example" in one parentheses and a different structure in the others. I see you have "ex:" here. These things aren't too important but I would probably just make it consistent when working on splitting out the info. on this page. 

I can split out this information from this page and include relevant info. from the other pages/ refer as needed. Go ahead and merge and I will start working through that. Thanks!

**Comment by nekohayo** [comment]
OK, I pushed my commit to master now. You should be able to, from your userdocs branch, do a "git rebase upstream/master" and it shouldn't conflict or cause trouble, other than you needing to force-push your userdocs branch to your personal repo afterwards. But at least now you'll have my changes integrated in your branch as a basis.

In the same topic, you may also be interested in making a suggestion for what could be good tooltips in the UI for #336 :)
