### ISSUE TITLE
Use special headerbar styling when running the dev version (whether through gtg.sh, GNOME builder, or the whatever flatpak we may have)

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#341]
Not vital, but "nice to have": some GNOME apps detect when they're being run in dev mode, and show a standard (?) dev headerbar styling. This is how gtg looks like compared to gitg when both are launched by GNOME Builder, for example:

![Screenshot from 2020-05-28 10-04-18](https://user-images.githubusercontent.com/479401/83151725-ee4bbb80-a0ca-11ea-91dc-69fc8fb6f6f0.png)

They sometimes also sport special icons for the development/nightly variants, but I don't know if that'd be the same issue and complexity...

**Comment by diegogangl** [comment]
We already have that bar when you run with -d
We can auto-enable it for dev versions once we have meson profiles and can have a dev profile
