### ISSUE TITLE
Auto-close current task window when a child task's link is clicked/keyboard-activated

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#345]
This is a follow-up to issue #326, for when the Task Editor's TaskView (?) will have been refactored by Diego.

As children now close when jumping to the parent, the reverse should also be done for consistency (close the parent when going to a child from the parent), as the same root problem would be present: as Task Editor utility windows focus but don't raise when "presented" on X11/Xorg GNOME session.

Note that there are two ways to enter into a task child from the parent:
* Clicking the link
* Focusing the link with the keyboard cursor and hitting Ctrl+Enter

**Comment by diegogangl** [comment]
Huh I didn't remember there was an issue for this. Fixed in the taskview branch (which has now landed in master)
