### ISSUE TITLE
Replace the CHANGELOG file by a NEWS.md file, write clean release notes

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#347]
Basically https://discourse.gnome.org/t/gtg-0-4-release-coming-very-soon-need-help-with-testing-marketing-release-notes-video/3050 - we need to write some serious 0.4 release notes:

> I would welcome help, at least for digging around to find and synthesize the user-visible changes between GTG 0.3.1 and GTG 0.4—even if you don’t feel at ease with words/copywriting, if you can provide at least a very basic “bullet points” list of changes that we must not forget to mention, that’s already a huuuuge help and I could use that to craft some super-marketingy exciting text.

In this day and age, the ChangeLog file is made redundant by version control / git history + bug trackers with milestones, but a NEWS.md file would still be desireable as a clean update thingy, which I _think_ gets picked up by GNOME Software or distros or whatnot? Or at least, it could serve as the basis for release notes in announcements and such.

Anyway... the toughest part is finding the time to study the existing ChangeLog file, the closed tickets, the git history, and try to "synthesize" this into human-readable and interesting release notes in the form of NEWS.md. Help wanted.

**Comment by leio** [comment]
Should be just NEWS, not a NEWS.md imo. I don't think things pick up NEWS.md. The styled version goes in appdata into <release> tags with HTML - that is what gnome-software picks up.

**Comment by vansia43** [comment]
@nekohayo Are the items in the Changelog for lines 1-54 relevant to these release notes? Looks like these changes were for 0.3.2(??) and the last update was 2016. I assume we really want to just highlight anything that the team has worked on since December when this was all started again. Also, if we kill this, are we going to archive the info in the Changelog for previous versions anywhere else, or is that not needed anymore?

**Comment by leio** [comment]
I think they are relevant if 0.3.2 was never released; but it's probably quite a bit too detailed to what we want in a NEWS file. Maybe just highlights from there should be included in NEWS, as they are still new things compared to the last 0.3.1 release (unless it was something that was in turn ripped out later by the new work).

Personally I would do that NEWS file, put in the CHANGELOG at the top of the 0.3.2 listings a note that this listing doesn't include new work and refer to NEWS and git log for that, rename the 0.3.2 with 0.4.0, add the release date, and then in some subsequent release remove the CHANGELOG overall.

**Comment by nekohayo** [comment]
Yeah that 0.3.2 release clearly never happened, and can be considered the 0.4 release; I had changed that version number locally on my side but never committed that because I knew the whole darned file would get rewritten into a "NEWS" file in a less "dumping ground list of every issue number" fashion and more of a human-readable release notes format.

**Comment by vansia43** [comment]
Alright. I have done my piece and all that I can do at this time. Please refer to the Gdoc and draft we were working on. I added some comments and points that may need clarification. At this time, I believe I have addressed the majority of the important PRs. Note that as I mentioned, some of the other features I could have missed may be buried in issues or commits without a corresponding issue. Feel free to tag me on anything you have a question about based on the work that I did :)

**Comment by nekohayo** [comment]
Completed via commit b55cbf844
