### ISSUE TITLE
Ctrl+Delete should be mapped only within the main window as a keyboard shortcut, not in the Task Editor

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#352]
I was wondering why I was always triggering the Delete task action in the git version... well it seems the Ctrl+Delete shortcut activates even if you do it within the Task Editor, not just within the main window (task browser).

Now why the heck would I want to use Ctrl+Delete in an editor? Because that's the standard way to delete the word that is after the text cursor (the opposite of Ctrl+Backspace)...

**Comment by nekohayo** [comment]
Also should not be active when the quick add entry is focused in the main window

**Comment by diegogangl** [comment]
The main reason I picked `ctrl+del` instead of `del` was to avoid conflicts like this!
I guess there's no other way but to remove accels on focus out and re-add them on focus in (in the mainwindow)

**Comment by nekohayo** [comment]
Yup... Pitivi deals with the same problems when focusing/defocusing the timeline, it enables/disables a bunch of accels (I spent some quality time making that work back then ;)

**Comment by flavin** [comment]
Hi @nekohayo I create this PR to handle this issue, could you take a look?
https://github.com/getting-things-gnome/gtg/pull/460

thanks in advance for your time!

**Comment by nekohayo** [comment]
Thank you for fixing this (and many other issues) @flavin, and thank you @diegogangl for reviewing and merging :)
