### ISSUE TITLE
Task browser's treeview columns sorting order is not remembered in the "Actionable" and "Closed" view modes

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#353]
If you change the sorting by due date to have the more urgent tasks at the top instead of the bottom (which should probably be the default anyway), when you restart GTG you can see that it was remembered in the "Open" tasks view, but not the "Actionable" or "Closed" tasks.

I was thinking that all three should be controlled by a single sorting setting but then maybe some users won't like that, or particularly, the views offer different sorting columns (the Actionable view doesn't show the start dates for example)...

**Comment by asakura42** [comment]
+
