### ISSUE TITLE
Title of the main window is simply "gtg"

### ISSUE THREAD

**Issue by Neui** [getting-things-gnome/gtg#361]
While this application moved to use headerbars, it seems the title of the main window is simply "gtg".
I would suggest at least giving it a more fitting name such as "Getting Things GNOME!" or "Gettings Things GNOME! (GTG)", so that it is easier to identify the application when a list of windows is displayed (such was when using rofi or i3wm) and generally looks nicer.
The "n active tasks" part can be left out I think, since there were [apparently problems before](https://github.com/getting-things-gnome/gtg/issues/203) and I think it isn't really needed.

Using git master (63353d7e4cdabc137e25886bb8b38d3125d28dcc).

![Screenshot of i3wm title bars and the rofi menu](https://user-images.githubusercontent.com/1196130/84543195-296d0200-acfb-11ea-82c4-35998dc76b0d.png)

**Comment by diegogangl** [comment]
Fixed, thanks for reporting!
