### ISSUE TITLE
ESC doesn't close editing tags window

### ISSUE THREAD

**Issue by Neui** [getting-things-gnome/gtg#363]
1. Have some tags, open the sidebar
2. Right click on a tag
3. Select "Edit..."
4. New window pops up. Press ESC

I expected it to close the window, like many other windows in the application (such was when examining plugins or editing an task).

Using git master (abe2a9110dd0fc6a46f2d095013972877ea67d78).

**Comment by diegogangl** [comment]
Fixed, thanks for reporting (and the other one too)
