### ISSUE TITLE
Renaming tags to use spaces does weird things

### ISSUE THREAD

**Issue by Gert-dev** [getting-things-gnome/gtg#373]
Hello, I'm new to Getting Things GNOME! and I wanted to take the time to report an oddity I noticed.

In the editor you can use `@blah` to create a new tag; that works, and the tag is highlighted and shows up in the sidebar. I notice that `@blah spaced` only marks `@blah` as tag, which makes sense, no spaces are supported, I guess. I change the tag to `@blah-space` instead, which works.

If I now go to the sidebar and rename `@blah-space` to `@blah space` there, the bulk rename happens, and `@blah space` is displayed in the sidebar. Opening the item description however shows `@blah space` with only `@blah` marked, as before. The sidebar now suddenly corrects itself to show `@blah`. Up until that point, the spaced version was still incorrectly displayed in the sidebar.

I also encountered a case with multiple items with this tag existed and I was left with two tags in the sidebar after the rename: both `@blah` and `@blah space`, which is probably related.

Hope this helps in getting things stable!

**Comment by diegogangl** [comment]
Thanks, pushed a quick fix. We'll fix this better once we have the new dialog -_-

> Hope this helps in getting things stable!
Ha, nice!
