### ISSUE TITLE
Unified "Reopen" action for closed tasks in the treeview

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#377]
Somewhat similar in spirit to #298, but not exactly.

I noticed at least one case where the translatable string "context" parameter can make a difference for translators, such as my own FR translation... in GTG/gtk/data/context_menus.ui, the closed_task_menu items have that problem where I was translating them identically in the FR version I had considered both "Mark as Not Done" and "Undismiss" as the same thing in practice, "Restaurer" (which means "Restore"), because French is verbose and I preferred to have a shorter label there.

But then when you look at the right-click menu for Closed tasks in the main window, you end up with twice the same string due to my overzealous translation simplification:

![restaurerX2](https://user-images.githubusercontent.com/479401/85230780-77030200-b3c0-11ea-8490-73f6a08733e3.png)

One way to address this could be to have  `context="right-click menu in the treeview"` as a parameter everywhere in GTG/gtk/data/context_menus.ui... but this made me think of something else.

In addition to the potential UI improvements for #298, I think that in the main window / closed tasks treeview, when you right-click closed tasks, instead of being presented with two choices, GTG should just offer you to "Reopen" the tasks, and behind the scenes it figures out for each task if it needed to be "marked as not done" or "undismissed".

Hence this bug report, because that means there'd some code logic involved instead of just flagging strings now.

**Comment by Neui** [comment]
I think combining those is much more intuitive, because I was also confused at first before reading this, and I guess the distinction when reopening isn't really important.

**Comment by diegogangl** [comment]
Tasks have three states:

```python
    STA_ACTIVE = "Active"
    STA_DISMISSED = "Dismiss"
    STA_DONE = "Done"
```
So in both cases they would just return to "active". There's not much point in having both options in the menu TBH.

**Comment by nekohayo** [comment]
Confirming, as I'm running the English version lately: even with the distinction, it makes no sense to me to have both "Mark as Not Done" and "Undismiss" as context menu actions in the task browser, so in the case of the Closed tasks view, I'd have just a unified "Reopen" action.
