### ISSUE TITLE
Python f-strings can't be really translated

### ISSUE THREAD

**Issue by Neui** [getting-things-gnome/gtg#380]
Take a look at:

https://github.com/getting-things-gnome/gtg/blob/abe2a9110dd0fc6a46f2d095013972877ea67d78/GTG/gtk/browser/delete_task.py#L109

What happens is that while gettext correctly finds the `"\nAnd {missing_titles_count:d} more tasks"` string, however at run time, Python formats the string first (like `"\nAnd 4 more tasks"`) before feeding it into gettext, and because there isn't explicit translations for each number, the string is left untranslated.

There is an  [StackOverfow question about this](https://stackoverflow.com/questions/49797658/how-to-use-gettext-with-python-3-6-f-strings), and there are 2 solutions:
* Don't use Pythons `f`-strings, use the `format()` method
* Use an wrapper method (`f(_("\nAnd {missing_titles_count:d} more tasks"))`), but seems somewhat hacky

There might be other strings that have the same faith, such as (seems gettext mark those strings as `python-brace-format`, so it is somewhat easy to find, or run `grep -r "_(f"`):

https://github.com/getting-things-gnome/gtg/blob/abe2a9110dd0fc6a46f2d095013972877ea67d78/GTG/gtk/backends/__init__.py#L68

(Only found those two)

**Comment by diegogangl** [comment]
We'll fix this for 0.5 so we don't stall the release any more than necessary.
Though it breaks my heart to drop f-strings for format() again -_-
