### ISSUE TITLE
ESC doesn't close the dedicated date selector window

### ISSUE THREAD

**Issue by Neui** [getting-things-gnome/gtg#382]
1. Right click on an open task
2. Set start/due date → select date...
3. Press ESC

Expected: Window will close, no change is being made

Actual: Window doesn't close

I am wondering if maybe the popup, when you click onto one of the date fields when editing a task, could be reused rather than opening an window.

**Comment by diegogangl** [comment]
> I am wondering if maybe the popup, when you click onto one of the date fields when editing a task, could be reused rather than opening an window.

This would be nice but it will take a small refactor of all that code + editor
