### ISSUE TITLE
Traceback when trying to send a task via email (plugin) in the flatpak version

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#388]
When you try to use the "Send by email" action in the task editor's "…" menu when the plugin is activated, you get this traceback (doesn't occur when running the git version manually, IIRC):

```
  File "/app/lib/python3.7/site-packages/GTG/plugins/send_email/sendEmail.py", line 69, in onTbTaskButton
    Gio.app_info_get_default_for_uri_scheme('mailto').launch_uris(
AttributeError: 'NoneType' object has no attribute 'launch_uris'
```

Is it just an error in terms of the Flatpak package needing to have permissions for a portal for this, or this requires changes in the plugin's code?

**Comment by bilelmoussaoui** [comment]
You should use `Gio.AppInfo.launch_default_for_uri` instead which uses the OpenURI portal for you.
