### ISSUE TITLE
Merge the Plugins and preferences.

### ISSUE THREAD

**Issue by sagarghuge** [getting-things-gnome/gtg#39]
We have the GtkNotebook in preferences so we can merge the plugins with preferences dialog box by adding it to another page of notebook. and also we can provide the preferences menu as a app menu . 

< Open for discussion >

**Comment by izidormatusov** [comment]
This is a feature not a bug :) I've split those two dialogs as plugins dialog got quite complex already. It also plays along with settings dialog for synchronization services/backends.

IMHO, it better to have two simple dialogs rather one complex one.
