### ISSUE TITLE
Remember last view on closing/opening

### ISSUE THREAD

**Issue by hugotrip** [getting-things-gnome/gtg#398]
At first, thanks for this great relaunching.

I've installed the flatpak 0.4 release to replace my old fedora gtg i've been keeping since ages, and I'm surprised that GTG 0.4 dosen't remember which view I was when I closed windows.
I mean I used actionable view (formerly known as workview, I think) by default until then, but when I close GTG 0.4 and reopen it, it always start on open view.
Is it a bug  in my setup, or is it like that for everybody ?
(in my workflow, GTG starts with gnome login, that's why I'd like it to be at first a reminder of what is actionable)

**Comment by diegogangl** [comment]
This is saved in the config but not used, so it's a regression

**Comment by diegogangl** [comment]
In case anyone wants to tackle this:
- The config is in config.py (the `view` key)
- The place to restore the view is in `MainWindow.restore_state_from_conf()`

**Comment by nekohayo** [comment]
Also somewhat related: #353

**Comment by hugotrip** [comment]
Ok, I just tested master, and it works now for me.
Thanks a lot.
