### ISSUE TITLE
task not shown in work view if one of it tags deactivated in work view

### ISSUE THREAD

**Issue by phyl0x1** [getting-things-gnome/gtg#40]
If a task is due and at least one of its tags is disabled in work view then the task doesn't appear when work view is activated. (I am using 0.3)

I am not 100% sure whether this actually is a bug or just intended behavior. It could also be seen as a feature to easily ban certain things from your work view.

**Comment by izidormatusov** [comment]
This is a feature. You might want to have a tag `@Later` that hides it for you from Workview. I've reported issue #91 that will make those reasons discoverable from UI.
