### ISSUE TITLE
Feature request: Recurrent tasks

### ISSUE THREAD

**Issue by Arbitrate3280** [getting-things-gnome/gtg#400]
Hey, would it be possible to add a recurrent tasks feature?

Say I need to do a specific task every monday and friday, now I would need to every week recreate this tasks manually. The way I imagine it working would be: Create task > set date to every friday, it would then show up every friday until the task is dismissed.

I'm really new to gtg and still discovering it's features, sorry if this is already there and I just missed it. Fantastic job to everyone who worked on getting this new version out the door, your efforts are appreciated!

**Comment by Vitorvlv** [comment]
Nevermind, I misspelled it and that's I didn't found an issue about it.  #169 already exists, I'll follow that.
