### ISSUE TITLE
Untouched tasks: Set timer to something over 100 days?

### ISSUE THREAD

**Issue by JaneSmith** [getting-things-gnome/gtg#412]
Hello.

I wanted to use the Untouched Tasks plugin, and configure it to tag tasks after 6 months, which translates to roughly 180 days. I was surprised to see that after I type in 180 days and shift focus in the UI, it immediately changes it to 100 days.

Is there some reason behind this limitation, or was it an arbitrary choice? Would it be possible to extend the timer?

Thanks.

**Comment by nekohayo** [comment]
I don't think it was a limitation on purpose, more like a bug resulting from the default parameters of GTK's spinbutton widget for that UI maybe. If you look at the "untouchedTasks.ui" file, on line 7 you can see this (which is the only mention of "100" I can find, and I see no mention of max or limit or 100 in the actual code in untouchedTasks.py):

`    <property name="upper">100</property>`

If you were to change it to, say, 365 or 999, I suspect it would work fine. If so, I guess then we could change that ui widget's default max value to something bigger (but what, that is the question)

**Comment by clobrano** [comment]
Hi all, I was looking at this as first contribution to the project. As you suggested, changing the "upper" property in "untouchedTask.ui" does change the behavior. 
I tried a little more, and set the upper limit to 1000, but it seems that the counter widget does not have space enough to allocate 4 digits. Considering this, would you say that using "999" as upper limit is a good compromise and fix for this bug?

**Comment by nekohayo** [comment]
Yeah, a 999 days limitation sounds perfectly fine to me... because frankly, who would want a plugin to only tell them about tasks that haven't been touched in over 2.73 years? ;)
