### ISSUE TITLE
Tag icon selector window empty after first open

### ISSUE THREAD

**Issue by leio** [getting-things-gnome/gtg#414]
When selecting an icon for a tag, it pops up a rather small selection of icons to pick and works. But opening it a second time within the lifetime of the same gtg process, it opens an empty dialog with no icons and other UI controls in it. Need to restart the app to be able to set another tag icon.

**Comment by nekohayo** [comment]
Indeed, the 1st time you get:

`(gtg:266997): Gdk-WARNING **: 07:39:49.204: Couldn't map as window 0x562f17f95120 as popup because it doesn't have a parent`

But the 2nd time you get:

```
(gtg:266997): Gdk-WARNING **: 07:40:00.125: Couldn't map as window 0x562f17950c70 as popup because it doesn't have a parent
(gtg:266997): Gtk-CRITICAL **: 07:40:01.886: gtk_widget_get_window: assertion 'GTK_IS_WIDGET (widget)' failed
(gtg:266997): Gtk-CRITICAL **: 07:40:01.886: gtk_widget_translate_coordinates: assertion 'GTK_IS_WIDGET (dest_widget)' failed
(gtg:266997): Gtk-CRITICAL **: 07:40:01.886: gtk_widget_get_window: assertion 'GTK_IS_WIDGET (widget)' failed
(gtg:266997): Gtk-CRITICAL **: 07:40:01.886: gtk_widget_translate_coordinates: assertion 'GTK_IS_WIDGET (dest_widget)' failed
(gtg:266997): Gtk-CRITICAL **: 07:40:01.886: gtk_widget_get_settings: assertion 'GTK_IS_WIDGET (widget)' failed
/usr/lib64/python3.8/site-packages/gi/overrides/Gio.py:44: Warning: g_object_get: assertion 'G_IS_OBJECT (object)' failed
  return Gio.Application.run(self, *args, **kwargs)
```

**Comment by diegogangl** [comment]
Can't confirm this on current master, is this still happening?

**Comment by Neui** [comment]
Now that the icons have been switched to being emoji-based using the GTK built-in emoji selector, and even now re-done the tag editor, I don't think this is still an issue any more.
