### ISSUE TITLE
Hierarchical tags in sidebar are unclear when renaming parent tag

### ISSUE THREAD

**Issue by ftsell** [getting-things-gnome/gtg#415]
Given the following tag structure:
![image](https://user-images.githubusercontent.com/12398140/87221779-002da900-c36f-11ea-9bf5-a5a3e1bc3574.png)

Once the *parent_tag* is renamed to something different using right-click -> edit, the hierarchical display does not get updated and still displays *child_tag* to be under *parent_tag*.
![image](https://user-images.githubusercontent.com/12398140/87221807-2bb09380-c36f-11ea-9460-b02f7ec37b23.png)

What I expected was GTG to automatically update the tag hierarchy to move *child_tag* under *parent_tag_new* after a rename operation.

**Comment by nekohayo** [comment]
Indeed, that is issue #307 ; if you can provide help in finding a solution for it, it'll be much appreciated :)
