### ISSUE TITLE
help system: certain pages fail to load

### ISSUE THREAD

**Issue by 1player** [getting-things-gnome/gtg#421]
GTG 0.4.0 from Flatpak.

Steps to reproduce:

* Open Help
* Click Searching For Tasks -> GTG Search Syntax link

Not all help pages are broken, for example Searching For Tasks -> Searching For Tasks works as expected.

**Comment by diegogangl** [comment]
I can't replicate. Clicking the _GTG Search Syntax_ from both the home and _Use GTG Search_ works for me

**Comment by nekohayo** [comment]
I'm unable to reproduce this issue with the 0.4 flatpak installed on my Fedora 32 machine, either... I'm not sure how to troubleshoot this. Maybe running the flatpak from a terminal would let you see some sort of warnings/errors related to this?

Or maybe even running directly:

`yelp ~/.local/share/flatpak/app/org.gnome.GTG/current/active/files/share/help/C/gtg`

...and seeing if you encounter the problem there?

**Comment by 1player** [comment]
Can't reproduce with `yelp /var/lib/flatpak/app/org.gnome.GTG/current/active/files/share/help/C/gtg`

But running the flatpak from the shell, this pops up on the misbehaving pages:

```
(WebKitWebProcess:21): Gdk-ERROR **: 23:50:53.677: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 207 error_code 2 request_code 151 (GLX) minor_code 34)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

**Comment by 1player** [comment]
Might be an upstream issue: https://bugs.webkit.org/show_bug.cgi?id=199666
