### ISSUE TITLE
Icon does not show in KDE Plasma panel

### ISSUE THREAD

**Issue by digitalethics** [getting-things-gnome/gtg#423]
No icon is shown in the panel (KDE Plasma) when using the GTG Flatpak.

**Comment by Neui** [comment]
Does this still apply? There v0.5 was released in the meantime.
With #651 it looks like it works (but pinning is/was broken).
I found out that the wrong icon is displayed, but I fixed it in master (#657, not in v0.5 unfortunately).

**Comment by nekohayo** [comment]
Closing the ticket as it is presumed to be solved, and if @digitalethics can reproduce the issue in the latest git version or the 0.6 release (whenever it comes out) he can reopen this ticket if needed.
