### ISSUE TITLE
Add option to automatically display closed items in strikethrough format

### ISSUE THREAD

**Issue by digitalethics** [getting-things-gnome/gtg#425]
I feel it is more intuitive to automatically display closed items in strikethrough format to visually distinguish them from open or actionable items. I would prefer to display closed tasks in strikethrough format by default. At least, users should be given the option to enable or disable this (opt-in or opt-out).

**Comment by nekohayo** [comment]
You mean in the task editor, or the task browser (main window)? If the former I agree, if the latter I'd say this would massively clutter up the view, and the whole point is to have clarity when you're looking at what you need to do on a daily basis. This is why the closed tasks were separated out in a bottom pane previously (and now in a view switcher, but that's the same thing conceptually).

**Comment by diegogangl** [comment]
The task editor now displays done tasks with a strike through. Implementing that in the browser would be a bad idea, and as @nekohayo says would lead to clutter (and in the current architecture, even slower performance).
