### ISSUE TITLE
Remove insert emoji icon on the right side of the quick entry panel

### ISSUE THREAD

**Issue by digitalethics** [getting-things-gnome/gtg#426]
The emoji icon looks out of place on the right side of the quick entry panel. I would keep this as clean as possible and move this elsewhere.

**Comment by nekohayo** [comment]
I don't think you can move this / choose a location for it, I think it's probably just the result of enabling the emoji support property in the GtkEntry widget. The only alternative for that feature would be to have an emoji insertion icon in the toolbar of the task editor window I guess, but then wouldn't you consider it to be similarly annoying to you? If so it might make sense for you to make a plugin for your specific usecase...

**Comment by digitalethics** [comment]
> The only alternative for that feature would be to have an emoji insertion icon in the toolbar of the task editor window I guess, but then wouldn't you consider it to be similarly annoying to you?

I guess this would look better and keep the actual quick entry bar clean.

**Comment by nekohayo** [comment]
I doubt we'll be adding an option for the visibility of this thing (or multiple potential locations) and the additional code paths it involves from a maintainership standpoint, so respectfully I will say that this is probably something you can address with a little homebrew plugin on your side :)
