### ISSUE TITLE
GTG only saves opened task editor window states on clean exit; if not closed cleanly, GTG reopens them all on startup

### ISSUE THREAD

**Issue by BazaarMunchkin** [getting-things-gnome/gtg#434]
After each system Reboot, the GTG application will spawn a window for each unfinished task upon first launch. If this is the expected behaviour, perhaps we could consider adding a Setting to disable this behaviour. As the number of tasks increases to any significant size, this creates extra work for the user.

**Installed version:** 0.4.0 from Flatpack
**System:** Pop!_OS 20.04
All of FlatPack system is updated fully.

**Comment by diegogangl** [comment]
Yup, this is a bug. If you log out or power off without closing GTG first, it won't update the list of opened windows. In other words, every time a window is opened it gets added to the list but they are only removed when gtg is closed.

**Comment by BazaarMunchkin** [comment]
> Yup, this is a bug. If you log out or power off without closing GTG first, it won't update the list of opened windows. In other words, every time a window is opened it gets added to the list but they are only removed when gtg is closed.

I appreciate the quick response.  Thank you.

At least I know how to prevent this going forward on my end.

**Comment by thinkerf** [comment]
Tasks still popping up after unexpected shut-down

v0.6-20-g55a1a624-dirty (snap version form Ubunto repository)
Kubuntu 22.04

Why is this functionality even in the program?  At startup, the most I'd want to see is the list of incomplete (Actionable) tasks, sorted by due date.  I would not want to see any tasks pop-up, even if I have them open before.
