### ISSUE TITLE
Symbolic toolbar icons

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#44]
Followup to the 4-years-old https://bugs.launchpad.net/gtg/+bug/500873

The current toolbar icons pretty much all look alike, they have almost the same shapes. See the "Make Icon Silhouettes Distinct" section in https://developer.gnome.org/hig-book/unstable/icons-design.html.en

Back then I suggested changing the icons. Now, the answer is even simpler: just use standard symbolic icons like the rest of GNOME applications. I can probably provide a patch for that when you're done porting to GTK 3.

You could simply use standard stock GTK icons for this:
- gtk.STOCK_NEW for creating a new task
- gtk.STOCK_OK for marking a task as "done"
- gtk.STOCK_CANCEL for marking a task as "not to be done anymore"

And thus it will be better integrated (theme-able), etc.

**Comment by izidormatusov** [comment]
Additional resources:
- http://www.pygtk.org/pygtk2reference/gtk-stock-items.html
- https://developer.gnome.org/gtk3/stable/gtk3-Stock-Items.html
