### ISSUE TITLE
GTG: added to NixOS (licenses?)

### ISSUE THREAD

**Issue by oyren** [getting-things-gnome/gtg#445]
Getting Things Gnome was added to the [NixOS repository](https://github.com/NixOS/nixpkgs/pull/94686). But we are not sure which license is the right one, see:

https://github.com/NixOS/nixpkgs/pull/94686#discussion_r465532946

Also (liblarch) https://github.com/NixOS/nixpkgs/pull/94686#discussion_r465532349

Could somebody clarify it?

**Comment by oyren** [comment]
Thanks.

**Comment by diegogangl** [comment]
BTW, liblarch's license is LGPL 3
