### ISSUE TITLE
Advice on Relative dates

### ISSUE THREAD

**Issue by zeddo123** [getting-things-gnome/gtg#455]
Hi everyone,

I am working on the repetition/recurring tasks and would like your input on somethings.
As many have recommended that when the task(recurring) is set to done or dismiss it should become closed and another one should be duplicated with the next date, I need to have a way of figuring out the correct next date from the due date and not the current day.

To illustrate:
In the Date Object, the tomorrow method adds one delta-time to today(). For this reason, I cannot use this object to get things done.
```python
def tomorrow(cls):
        """ Return date for tomorrow """
        return Date(datetime.date.today() + datetime.timedelta(1))
```
Should I modify the Date class or make a new object that would only deal with relative dates?

PS: I am following [this](https://github.com/getting-things-gnome/gtg/issues/169) opened issue to implement the feature.

**Comment by diegogangl** [comment]
Hi @zeddo123, welcome!

You can also add `Date` objects and timedeltas to get the next day: `due_date + datetime.timedelta(1)`. 

You have to be careful about fuzzy dates though (now, soon, someday). I think these should stay the same way they are. You can check for them with `due_date.is_fuzzy()`. 

However, if you find yourself adding timedeltas like that many times then it might be best to add a classmethod to `Date`. Something like `next_day(number_days)`, so you can pass 1 for tomorrow.

Looking forward to your work!

**Comment by diegogangl** [comment]
BTW, it would be better if we kept discussions about this feature in the other issue so everything is in one place.

**Comment by zeddo123** [comment]
Hi,

That's what I was thinking about however **where should I process the date** to know how many days to add because as far as I know there is no method that does that. Furthermore, when the user puts a literal date, I decided to put the next date as next occurence of the day and month.

Sorry of opening a new issue.

**Comment by diegogangl** [comment]
> Sorry of opening a new issue.

No problem :)

> That's what I was thinking about however where should I process the date to know how many days to add

Not sure if I understood this 100% but, you can calculate how many days to add when the task is closed or dismissed which happens here: https://github.com/getting-things-gnome/gtg/blob/master/GTG/core/task.py#L248 .

**Comment by zeddo123** [comment]
Hi,
I was wondering whether it should be put all in [here]( https://github.com/getting-things-gnome/gtg/blob/master/GTG/core/task.py#L248) or call a method from the date object.

Anyway, I made several methods in date to mimic the methods that parse the date but for my needs.

**Comment by diegogangl** [comment]
> I was wondering whether it should be put all in here or call a method from the date object.

Yeah, a method in Date would be better. It could also be a method in Task if it's very specific

**Comment by diegogangl** [comment]
Closing this one since we are already on a PR
