### ISSUE TITLE
Add sync with Google Tasks

### ISSUE THREAD

**Issue by ondra05** [getting-things-gnome/gtg#459]
I have Google Tasks on my phone. GNOME To-Do (that semi-dead app) can do sync with it, but GTG doesn't. I am using the latest flathub version (0.4). I would appreciate that thing, because GTG is much better than To-Do.

**Comment by nekohayo** [comment]
Actually a duplicate of issue #164, and last time I heard Google is killing Google Tasks... if it is not being deprecated by Google somehow, then someone needs to come forward and resurrect & update the plugin for this (see issue 164).
