### ISSUE TITLE
 GTG sometimes creates drag and drop "ghosts"

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#47]
Initially filed at https://bugs.launchpad.net/gtg/+bug/1260858

This is just something I've noticed once in a while, when I'd dragging tasks around in GTG's browser view, I'd later get a "ghost" of the drag operation being released... the same issue that Pitivi had.
- See https://bugzilla.gnome.org/show_bug.cgi?id=695894 for a complete description.
- See https://git.gnome.org/browse/pitivi/commit/?id=d5bd8dc0 for the one-liner fix in Pitivi.

As your case might be different, you should ask the #gtk+ people on irc.gnome.org for help with this if you're stuck.

**Comment by diegogangl** [comment]
This might have been a Gtk bug, can't reproduce here in the future anymore

**Comment by nekohayo** [comment]
Haven't noticed this issue with the 0.4 final release either!
