### ISSUE TITLE
Dark theme text color issue on tasks with due date

### ISSUE THREAD

**Issue by Alexmitter** [getting-things-gnome/gtg#476]
In case a dark theme is used, the text is set to a white colour as normal, but in case of a task with due date that gets coloured in bright yellow, the text should be dark again to be readable like it is done correctly at "@SOMETHING" tags in tasks.
![image](https://user-images.githubusercontent.com/6940479/94785899-969ec300-03d0-11eb-8b26-f993a9809625.png)
![image](https://user-images.githubusercontent.com/6940479/94785935-a3bbb200-03d0-11eb-96ca-70e95edf93b2.png)

**Comment by diegogangl** [comment]
Is this in Master or 0.4? We have a dark mode toggle in master that refreshes these colors appropriately

**Comment by Alexmitter** [comment]
@diegogangl I run 0.4, if this is fixed in Master, please close.
