### ISSUE TITLE
Racy crash when closing the task editor immediately after editing the task title / summary

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#48]
Initially filed at https://bugs.launchpad.net/gtg/+bug/1256740

Sometimes, when you open an existing task for editing and rapidly change the title before pressing the "Escape" key to close and save the changes, GTG will crash.

ABRT caught the traceback and various debug information downstream here: https://bugzilla.redhat.com/show_bug.cgi?id=1036445

It happens when you press the Escape key after changing the title.
- You need to have a list of tasks in your main window - you don't need to be in the "all tasks" view or to have workview toggled off, but maybe having more tasks can help trigger the bug. FWIW, I have 83 tasks in workview (267 total), of which ~20 are in a "foo" tag.
- To reproduce, I can simply open an existing task, change the end of the title by typing something really fast and then IMMEDIATELY press Escape to save+close. Once in a while (not everytime) it crashes doing so.

**Comment by diegogangl** [comment]
Can you still trigger this in master?

**Comment by diegogangl** [comment]
Can't trigger in master at all. Re-open if you are fast enough :D
