### ISSUE TITLE
Evaluate integrating ulogme to quantify productivity

### ISSUE THREAD

**Issue by digitalethics** [getting-things-gnome/gtg#485]
I recently came across Andrej Karpathy's older blog post on [Quantifying Productivity](https://karpathy.github.io/2014/08/03/quantifying-productivity/). He wrote [ulogme](https://github.com/karpathy/ulogme) to track and visualize his computer activity. It would be great to integrate some or all of these features into GTG.

**Comment by nekohayo** [comment]
Isn't this the same thing as _Hamster_ (whose plugin in GTG recently got resurrected)?
