### ISSUE TITLE
Implement habit tracker

### ISSUE THREAD

**Issue by digitalethics** [getting-things-gnome/gtg#486]
The best habit tracking app on Android is [Loop Habit Tracker](https://loophabits.org/). It would be great to add similar habit tracking functionality to GTG.

![loop habit tracker](https://user-images.githubusercontent.com/57445091/95843596-2be27580-0d48-11eb-829f-841a2022c35e.png)

![features](https://user-images.githubusercontent.com/57445091/95843824-6fd57a80-0d48-11eb-8a1c-7d211f4b6449.png)

**Comment by nekohayo** [comment]
Hi! When I look at the screenshot above I see habits and "goals", not unique tasks. In some respects you could do this with GTG's newly implemented repeating tasks feature (issue #169), but I personally think they would clutter up your view. I think the point of GTG is having clarity about what absolutely needs to be done and by when, with unique actionable tasks.

What I see in the screenshot above looks cool and I can imagine the appeal for it, however I tend to think that this would actually be better-served by having a dedicated simplistic GNOME app just for this; it would make the separation much cleaner and the user interface could be built specifically for that usecase. It would probably be fairly easy for someone to implement that as a learning project, too. With that in mind, I think I'll consider this out of scope for GTG, sorry!
