### ISSUE TITLE
No module named 'GTG'

### ISSUE THREAD

**Issue by danjde** [getting-things-gnome/gtg#50]
Hi staff,
I'm using Ubuntu 14.04 and daily gtg,
running gtg obtain: bash: /usr/bin/gtg: permission denied

so make it runnable:

chmod +x /usr/share/gtg/GTG/gtg
chmod +x /usr/share/gtg/GTG/gtcli
chmod +x /usr/share/gtg/GTG/gtg_new_task

now obtain: gtg
Traceback (most recent call last):
  File "/usr/bin/gtg", line 57, in <module>
    from GTG import _
ImportError: No module named 'GTG'

the python3-xdg version is:

dpkg -l |grep python3-xdg
ii python3-xdg 0.25-4 all Python 3 library to access freedesktop.org standards

thanks

**Comment by tomspur** [comment]
It seems this is a problem with the PPA. Could you try to install liblarch with pip [1] and see if it works?

[1] `pip3 install --user -e git+git://github.com/getting-things-gnome/liblarch.git#egg=liblarch`

**Comment by khurshid-alam** [comment]
@izidormatusov Can you please build python3-liblarch with latest gtg in daily build PPA? Thanks.

**Comment by nekohayo** [comment]
As we are a new team taking over the maintainership of this project and the Python 3 migration was done a while ago already, it is difficult to guess if this problem still applies to the current development version. Furthermore, I do not have sufficient time and knowledge about packaging, and I do not run Ubuntu.

Please try out the git version and see if it improved anything or if the issue remains intact and is still relevant today.

Regarding the mentions of a PPA, if someone wants to bother maintaining a PPA, feel free to get involved to do that.

Alternatively, there is a Flatpak of the 0.3.1 stable version that exists thanks to @bilelmoussaoui and he once successfully packaged the git version.

**Comment by diegogangl** [comment]
This doesn't happen when running from the Flatpak, or using `./gtg.sh` in the git repo
