### ISSUE TITLE
Include git commit version in the about window

### ISSUE THREAD

**Issue by Neui** [getting-things-gnome/gtg#503]
I would suggest adding some kind of info like what git revision (possibly use `git describe` which currently outputs `v0.4-223-ge330d27d`) is being used, so that when an development version is installed from git, you can see what commit it is. This would make it easier to determine what development version you're on and how far you're behind.

Possibly the `GTG/gtg.in` file could be used to set the variable, since it is processed anyway (`.in`).

I'd suggest adding this to the about window, since the version is listed there, and the `--version` command.

**Comment by frainz-de** [comment]
Hi, I'm using this issue to get a feel for the gtg code. As far as I understand, gtg.in is the only python file in the project, that's templated using meson's configure_file. The version and all the other meta information is in core/info.py. To get the commit id, we could use [vcs_tag()](https://mesonbuild.com/Reference-manual.html#vcs_tag) and turn info.py into a template as well.
