### ISSUE TITLE
can't change date

### ISSUE THREAD

**Issue by WhilelM** [getting-things-gnome/gtg#505]
version v0.4-229-g34a7acdd

Can't no more define or change date on tasks.

> Traceback (most recent call last):
>   File "/home/whilelm/opt/gtg/.local_build/install/lib/python3.7/site-packages/GTG/gtk/browser/main_window.py", line 1089, in on_set_due_tomorrow
>     self.update_due_date(None, "tomorrow")
>   File "/home/whilelm/opt/gtg/.local_build/install/lib/python3.7/site-packages/GTG/gtk/browser/main_window.py", line 1079, in update_due_date
>     due_date = Date.parse(new_due_date)
>   File "/home/whilelm/opt/gtg/.local_build/install/lib/python3.7/site-packages/GTG/core/dates.py", line 448, in parse
>     return Date(result)
>   File "/home/whilelm/opt/gtg/.local_build/install/lib/python3.7/site-packages/GTG/core/dates.py", line 103, in __init__
>     self._parse_init_value(value)
>   File "/home/whilelm/opt/gtg/.local_build/install/lib/python3.7/site-packages/GTG/core/dates.py", line 111, in _parse_init_value
>     self._cached_date = date
> NameError: name 'date' is not defined

**Comment by Neui** [comment]
You can try the PR #506 by using (assuming `origin` is this repo, which is the default if you cloned from here):

    git fetch origin pull/506/head; git checkout FETCH_HEAD

And then test. To revert back, `git checkout master` should be enough.
