### ISSUE TITLE
Subtask ID construction visible when showing description preview

### ISSUE THREAD

**Issue by Neui** [getting-things-gnome/gtg#507]
1. In the settings, activate description preview
2. Create a (parent) task
3. Create a child task
   Alternative: Open the parent task editor and write `- Subtask` in the task editor (checkbox should appear)
4. Open the parent task editor to update the preview
   (Not needed when doing the alternative route)

Result is that the internal `{! task-id !}` (or `<subtask>task-id</subtask>` in older tasks) is being shown, which is useless (the subtask is right below it).

![Image demonstrating the problem](https://user-images.githubusercontent.com/1196130/97784706-b4fb0880-1ba0-11eb-9abb-37b906e0cd77.png)

The expected behaviour is not to display that (not even its title).

**Comment by diegogangl** [comment]
This is fixed in the file format v2 branch (commit aa4970e1b6dccca6a00b5b44e4252c2b7ee835ed). It's not easily fixable in master because it's sort of in-between formats.

**Comment by nekohayo** [comment]
Is that the same thing I'm seeing here? Testing with the "bryce" dataset, I simply added a parent task by right-clicking one of the items in the task browser, and typed some stuff in it, and a bunch of tasks started showing up with their content XML markup:

![screenshot](https://user-images.githubusercontent.com/479401/103494159-60277880-4e03-11eb-97bd-7b0efd7c17d8.png)

**Comment by Neui** [comment]
> Is that the same thing I'm seeing here?

I would consider it the same: You see the "internal" data.

**Comment by diegogangl** [comment]
Fixed in master now that the new file format has landed
