### ISSUE TITLE
Adding support for emojis in icons

### ISSUE THREAD

**Issue by radoslaw-gajos** [getting-things-gnome/gtg#527]
Icon support is a great feature, but unfortunately the choice of icons is very limited at the moment. Adding or replacing it with an ability to choose an icon based on emoji would make the choice much wider.

**Comment by Neui** [comment]
You mean #508 ? (So this would be a duplicate of #85 )

**Comment by radoslaw-gajos** [comment]
> You mean #508 ? (So this would be a duplicate of #85 )

Sorry, I didn't see it was already posted!
