### ISSUE TITLE
Tasks pop up when open GTG for first time

### ISSUE THREAD

**Issue by asakura42** [getting-things-gnome/gtg#529]
Some tasks are shown in popup windows when I open gtg for the first time in a session after hard reset. If I close gtg and reopen it, there are no popup windows. I use Archlinux and `gtg-git` from AUR.

**Comment by asakura42** [comment]
Found related bug: https://github.com/getting-things-gnome/gtg/issues/434

**Comment by asakura42** [comment]
I was wrong, that issue is closed, but this bug exists.

**Comment by nekohayo** [comment]
Yes the bug exists in the released 0.4 version but is fixed in the git version, and therefore for the next (0.5) release.
