### ISSUE TITLE
Broken-looking icon names show up after emojis port

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#540]
Not a showstopper by any means, but I'm thinking it would probably look nicer if we didn't attempt to show the old icon names in there, it might be jarring / cause some bug reports to occur upon release:

![icon names artifacts after port to emojis](https://user-images.githubusercontent.com/479401/105052503-f67faf00-5a3d-11eb-96d1-5160410a3237.png)

**Comment by diegogangl** [comment]
Huh that's weird, they should be reset

**Comment by diegogangl** [comment]
I took a look at the code and remembered why I left it like this. We can fix this while versioning in the new file format. So this would be fixed once we land that branch
