### ISSUE TITLE
"open parent" button gets behavior from "add parent"? And deletes the subtask!

### ISSUE THREAD

**Issue by GurvanKervern** [getting-things-gnome/gtg#542]
On Ubuntu 20,04 with the Github version (but I have had this problem of randomly losing subtasks in gtg on other distros/setups, I just noticed how)
In a subtask, click "Open parent" in the task editor and it deletes the task, but leaves the parent alone, apparently with the delete_task() from Requester.py (I tried to add an Exception to see the stack when it happens for more details, but the code checks itself and my modifications are removed before running)

Also in those children tasks the tags inherited from the parent are messed up : truncated, modified, cut, removed the at symbol, and repeated many times, I'm not sure if it is related to the other bug. But the deletion happens even when you corrected the tags before clicking "open parent" so I guess not

**Comment by nekohayo** [comment]
Is this only with the git version, or it also happened with 0.4? I'm clicking that button a bunch of times each day and never encountered data loss (and apparently @zeddo123 has not encountered it with the git version).

If it's specific to the git version on your end @GurvanKervern, and if you are able to reproduce it easily, you could use [git bisect](https://git-scm.com/docs/git-bisect) to identify which commit has introduced the problem?

**Comment by GurvanKervern** [comment]
I think 0.4 was the "stable" version for a long time right? If so I'm pretty sure I had task disappearing on several Debian-based distros (Debian, Mint and Ubuntu), so I suppose 0.4 was in there somewhere, although to be fair I hadn't used gtg for years because of those disappearing tasks, I decided to use it again only one or two months ago and only the git version.

I was about to go to bed but I'll look into git bisect and tell you if I find something that way (but to me this is an ancient problem, I think I reported it in 2009 or 2010, and I have tried gtg on 3-4 different distros as the work view is so practical, I always decide to try it again until I lose some tasks and abandon it again^^)

Regarding the code "regenerating" I was very surprised too, especially since I understand I have the "dev" version, I was ready to look for a script that would checkout the last git commit before runtime or compare checksums with the last official version or something.
It makes more sense that it is not the expected behavior but that means I'll have to find a way to modify the files first. (I modified debug.sh to add set -e without issue, this "regeneration" seemed to apply only to the 2-3 Python files I tried to modify, after seeing this I chmoded u-w, the last time I gave the file to root:root, every time it came back with the same content, rights and owner/group, so I'm guessing the whole Python tree is checked

I have quite a few things to do this week but I'll definitely work on this, I would really love to be able to use gtg as my main todo list :)

**Comment by Neui** [comment]
Reminds me of https://github.com/getting-things-gnome/gtg/issues/496#issuecomment-716230266

But I couldn't reproduce on current master (4a0b81804955cc81781fa5b1f32b920d8d6e6de6). I opened a task, and pressed the "Open Parent" button inside the task editor, which opened the parent task, no deletion.

> I tried to add an Exception to see the stack when it happens for more details, but the code checks itself and my modifications are removed before running

Where are you editing? On the git version (where you execute `./launch.sh`), it'll "install"/copy the files from the GTG folder (in the root directory of this repository) into the `.local_build` folder, so changes inside `.local_build` (may) get overwritten.

> I think 0.4 was the "stable" version for a long time right?

0.3 was the "stuck" version, 0.4 was the revival.

**Comment by GurvanKervern** [comment]
Ho I was modifying in .local_build, since I saw they were the files used at runtime, I thought there was only a first install. I'll try to add a pdb statement or exception in ./GTG, that should make things much easier :)

Yes, the bug I see seems very similar to #496 except when I click on the button the child task editor gets closed automatically, I don't need to do it manually, but the rest looks very similar.

**Comment by GurvanKervern** [comment]
Well I added my ipdb line but somehow the behavior doesn't happen right now, I'll add a backtrace as soon as I can get one

(I noticed a little annoyance surely unrelated to this bug but anyway : when you open a subtask in the task editor with Ctrl+E the focus is lost and goes back to the "general window", when using Ctrl+Enter however the focus is on the new window as expected)

**Comment by nekohayo** [comment]
@GurvanKervern:
* Yeah, ignore the hidden ".local_build" folder, as this is where meson copies the code and everything else on the fly when you launch.sh, that's not where you should do your changes, the gtg/ folder is where you should experiment and then the changes will be copied :)
* See if you can reproduce the issue with the standard "screenshots" data sample, by running `./launch.sh -d -s "screenshots"`? And if you can find a way to trigger the issue with that (you might have to delete the local tmp/ folder every now and then to reset that data to its default state), with some step by step repro instructions (or maybe you could record a tiny cropped 10fps webm screencast with a tool such as vokoscreen), we could see how you manage to trigger this problem...

**Comment by GurvanKervern** [comment]
> @GurvanKervern:
> 
>     * Yeah, ignore the hidden ".local_build" folder, as this is where meson copies the code and everything else on the fly when you launch.sh, that's not where you should do your changes, the gtg/ folder is where you should experiment and then the changes will be copied :)
> 
>     * See if you can reproduce the issue with the standard "screenshots" data sample, by running `./launch.sh -d -s "screenshots"`? And if you can find a way to trigger the issue with that (you might have to delete the local tmp/ folder every now and then to reset that data to its default state), with some step by step repro instructions (or maybe you could record a tiny cropped 10fps webm screencast with a tool such as vokoscreen), we could see how you manage to trigger this problem...

I will :) For now I'm still waiting for the problem to re-occur but gtg has been good the last few days :)

**Comment by diegogangl** [comment]
@GurvanKervern  Hi, have you noticed this issue again?

**Comment by GurvanKervern** [comment]
> @GurvanKervern Hi, have you noticed this issue again?

Not yet, but to be honest I haven't used gtg much in the last two weeks. I have added the pdb.set_trace call in (at least one of) the function that seems responsible, so when it pops up again I'll have a backtrace to put here :)

**Comment by nekohayo** [comment]
No news from @GurvanKervern, will presume the issue never resurfaced in the end. If it does occur with the current git version or the 0.6 release (being released this week), feel free to provide updated info to reopen the issue.
