### ISSUE TITLE
2 tasks references 1 subtask when using "Add a Parent task..." in main browser

### ISSUE THREAD

**Issue by Neui** [getting-things-gnome/gtg#545]
Not sure if intentional, but I noticed while testing that when creating a new parent task via "Add a Parent task..." menu item when right-clicking, the old parent task contents still references the sub task.
Using current master.
I've also noted that trying to open the "old" task doesn't replace the task editor like it normally does, but opens a new one.

https://user-images.githubusercontent.com/1196130/105258732-aa8e5080-5b8a-11eb-9cd2-437a7daaa93d.mp4

**Comment by zeddo123** [comment]
Yeah I was able to reproduce this bug, and it's not the behaviour intended. I suspect the task editor, or at least not `on_add_parent` as we are clearly removing the child from its parent.

https://github.com/getting-things-gnome/gtg/blob/4a0b81804955cc81781fa5b1f32b920d8d6e6de6/GTG/gtk/browser/main_window.py#L992
https://github.com/getting-things-gnome/gtg/blob/4a0b81804955cc81781fa5b1f32b920d8d6e6de6/GTG/gtk/browser/main_window.py#L1004

I did some debugging, and I am seeing the task being removed from its parent:
 
![debug](https://user-images.githubusercontent.com/34837535/105360650-1dceab80-5bf9-11eb-9e1a-dcb546eb9c93.png)

**Comment by zeddo123** [comment]
I was able to reproduce the same bug using the hold and drop method. From the very surface level investigation of the TaskView, I'm not seeing the subtasks (that have be removed outside the task editor) being removed from the TaskView; Only those that have been deleted from the task editor. As I haven't really dived in the editor code, I'm tagging @diegogangl.


https://user-images.githubusercontent.com/34837535/106524549-00e08500-64e3-11eb-8d30-d63e0aa537a8.mp4

**Comment by diegogangl** [comment]
Removing a subtask from the content is easy now: `self.content.replace(f'{tid}', '')`.
The only issue is figuring out where to do this, since `remove_child` doesn't seem to be called when dragging and dropping (I'm guessing that's inside liblarch).
