### ISSUE TITLE
Turn on G_ENABLE_DIAGNOSTIC in debug.sh/launch.sh for deprecation warnings by default

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#549]
The `G_ENABLE_DIAGNOSTIC` env variable, if set to a non-zero value, "enables diagnostic messages, like deprecation messages for GObject properties and signals."

So `G_ENABLE_DIAGNOSTIC=1 ./launch.sh` 

We should probably make that the default behavior of our launch/debug script, so that we can catch deprecations early rather than nearly 9 years later like in 541 ;)

**Comment by Neui** [comment]
This is from https://developer.gnome.org/glib/2.64/glib-running.html

Does it also work for methods? It says it is only for properties and signals, but in the linked issue `Gdk.cairo_set_source_color` is a method. Running with it doesn't reveal that method is still being used (I confirmed it that it runs via a debugger).

**Comment by nekohayo** [comment]
Oooh, this is what you meant, I hadn't really understood by the "does it work for methods" question you had... so if this doesn't work (from what you've seen), is there some checking tool that we could use to warn us about this?

**Comment by Neui** [comment]
In PyGObject I found an [`deprecated`](https://gitlab.gnome.org/GNOME/pygobject/-/blob/0a16082c3e092fdccf5499172a4b9dec07aa383d/gi/overrides/__init__.py#L210-217) annotation that uses [`warnings.warn`](https://docs.python.org/3/library/warnings.html) to warn. You can use [`PYTHONWARNINGS`](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONWARNINGS) to enable them. With `PYTHONWARNINGS=once` I got it:

```
gtg/lib/python3.8/site-packages/gi/overrides/__init__.py:333: DeprecationWarning: Gdk.color_parse is deprecated
  ret = method(*args, **kwargs)
gtg/.local_build/install/lib/python3.8/site-packages/GTG/gtk/browser/main_window.py:487: DeprecationWarning: Gtk.Widget.get_state is deprecated
  is_maximized = widget.get_window().get_state() & mask == mask
gtg/.local_build/install/lib/python3.8/site-packages/GTG/gtk/browser/cell_renderer_tags.py:171: DeprecationWarning: Gdk.cairo_set_source_color is deprecated
  Gdk.cairo_set_source_color(gdkcontext, my_color)
```

There is also `PYTHONWARNINGS=default` we could use ("Warn once per call location").
