### ISSUE TITLE
Sometimes, setting the start date in the task editor can shift the due date even if the startDate is before the dueDate

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#552]
This doesn't happen everytime so I'm not sure exactly what triggers this, but _sometimes_ GTG shifts the duedate even if the chosen startdate was _before_ the duedate (I presume GTG normally shifts the due date if the start date is after the duedate, which is OK to me):

https://user-images.githubusercontent.com/479401/106006844-a6c76600-6083-11eb-8ddc-66bc9970658b.mp4

In that case it shouldn't touch the due date, that's dangerous; the app is shifting someone's deadlines without warning, so the person could end up missing their deadlines.

**Comment by zeddo123** [comment]
I happened upon the same bug, but it's from a different cause (maybe related).

When selecting the start date and moving around in the calendar, if you move past the already selected due date and comes back to prior date, the due date will shift even though the actual start date is before the due date. Hope I was clear.


https://user-images.githubusercontent.com/34837535/106527235-3b4c2100-64e7-11eb-8f45-932219c72fcf.mp4
