### ISSUE TITLE
Unable to search for tasks using tags

### ISSUE THREAD

**Issue by DonQuixoteI** [getting-things-gnome/gtg#573]
Searching for tasks using tag(s) is not working in the development version. Nothing can be found applying tag in the search field. The search result is always empty.

The other types of search (words, dates etc.) are working as expected.

![list-with-tag-money](https://user-images.githubusercontent.com/20640208/110609313-65030280-818d-11eb-916b-c9a5015829cf.png)
![search-for-tag-money](https://user-images.githubusercontent.com/20640208/110609317-659b9900-818d-11eb-8f79-c2eb978f7b47.png)

**Comment by DonQuixoteI** [comment]
That was a simple example. In reality, I would like to search more complex cases, like @money @to_pay !before 2021-04-01

Removing "@" from the search does not work for me. The list remains empty.

![search-for-word-money](https://user-images.githubusercontent.com/20640208/110622997-7e5f7b00-819c-11eb-96da-c011ded19fba.png)

**Comment by DonQuixoteI** [comment]
The latest release (0.4) is able to search tags, but I prefer the development version. Thanks for the great app!

**Comment by nekohayo** [comment]
Probably a small regression introduced by Diego's file format changes that touches tags a lot. Thanks for reporting this and for keeping an eye out on potential other issues!

**Comment by DonQuixoteI** [comment]
Excellent! Thank you very much for fixing issue so quickly.

**Comment by diegogangl** [comment]
No prob! :D
