### ISSUE TITLE
Recurring status of tasks is lost after GTG restart

### ISSUE THREAD

**Issue by morhe-blip** [getting-things-gnome/gtg#578]
Tasks that are marked as recurring lose this property after GTG restart.

Reproduce:
Create new task, set as recurring, restart GTG. Task has lost Recurring status.

Happens with current master
commit 60be39b6d6f0f9acf7d94c0f6e129883f2c3eaab (HEAD -> master, origin/master, origin/HEAD)

But I am quite sure it also happened before.

**Comment by zeddo123** [comment]
Hi, yeah I was able to reproduce the bug and I'm working on it.
Thank you for reporting. :smiley:

**Comment by morhe-blip** [comment]
You're welcome :smiley: 

Thanks for working on it so promptly
