### ISSUE TITLE
Include all files that can be translated (POTFILES.in)

### ISSUE THREAD

**Issue by Neui** [getting-things-gnome/gtg#580]
Since now we're close to release, I suggested to be a good time to update the translation files, which was done in 60be39b6d6f0f9acf7d94c0f6e129883f2c3eaab.

However, I noticed that not all strings are available for translation.
As of now I found that the developer console plugin isn't marked to be translatable, but can be fixed by adding the following lines to `po/POTFILES.in`:

```
GTG/plugins/dev_console.gtg-plugin.desktop
GTG/plugins/dev_console/console.py
GTG/plugins/dev_console/utils.py
```

But that doesn't make sure that every translatable string is being considered.
Either we should just include every python file, or have some script to update that file.

(Note that for some reason if I regenerate the PO(T) files I get entries about `@APP_ID@` isn't in current master; Is this being removed manually or..?)

**Comment by diegogangl** [comment]
Maybe we should include every python file in `gtk/` and `plugins/`. I don't think the dev console has any translatable strings tho

**Comment by Neui** [comment]
> I don't think the dev console has any translatable strings tho

Actually it does: https://github.com/getting-things-gnome/gtg/blob/41d55257c55a84aab81bf0dbf095d5b16d03bfce/GTG/plugins/dev_console/console.py#L117-L126

**Comment by diegogangl** [comment]
ohh the welcome message, right. The whole thing should be translatable actually, I'll get that fixed
