### ISSUE TITLE
Settings window takes too long to open

### ISSUE THREAD

**Issue by Neui** [getting-things-gnome/gtg#591]
I tried to open the settings window, and it took multiple minutes until it appeared (didn't timed it, but I'd say 5 minutes). GTG was unresponsive during that time. Using v0.4-358-gf1e96d31 (10 days ago, so it could be possible some other fix implicitly fixed it).

Since the tasks gets expanded, it could be refreshing the view for some reason.

**Comment by diegogangl** [comment]
I tested this with the bryce set but it didn't take that long, and it didn't expand the tasks. Can you post a screen of your settings?

**Comment by Neui** [comment]
I tried out a bit with bryces dataset on current master. I disabled colors and enabled description previews (and each change caused it to freeze for some time), and enabled dark mode (since I am using a dark theme, forgot whenever it freezed).

It seems it only happens on the first open of the settings dialog, further ones are fast.

**Comment by diegogangl** [comment]
Is it still happening with the latest master?

**Comment by Neui** [comment]
It now got fixed. I guess 16eeb75ed80c889f7e45055741c7ed1cd9772c88 was the fix, which is similar what I thought it was happening behind the scenes, but had some problems getting the profiler to work (to find it).
