### ISSUE TITLE
Tasks always gets expanded on refresh

### ISSUE THREAD

**Issue by Neui** [getting-things-gnome/gtg#592]
Previously, if I remember correctly, it'll remember what tasks were collapsed and what not (at least in the open-view).
Now, for some time this doesn't work anymore, they always get expanded after what it seems a refresh (like passing midnight).
This is annoying if you've got many subtasks that are done far in the future, but don't want to clutter your open view.
Using v0.4-358-gf1e96d31 (10 days ago, so it could be possible some other fix implicitly fixed it).

**Comment by Neui** [comment]
Doesn't seem to be completely fixed. I collapsed most tasks, but now looking at it they're expanded again. Some are still collapsed (I think the same ones when I initially started GTG). Using current master, 28ca417ddc4d1ae06c50e8adf38ba3765746c97e.

**Comment by diegogangl** [comment]
hmm it should be saving them before restoring. Maybe there's a race condition with the config saving?

**Comment by Neui** [comment]
Just as a side note, GTG was running without being restarted. Also, toggling the dark mode option in the settings expands everything again. Looking at the commit which supposedly fixes the issues (which is only in the settings, not just when doing nothing), maybe it is because of the timer refreshing (`refresh_all_views`)?

**Comment by diegogangl** [comment]
Yup, I did the same thing with the dev console to check `refresh_all_views()` :D
We'll have to add the same code to those uses of `refresh_all_views()`
