### ISSUE TITLE
flatpak gtg : Gtk-Message: 09:54:10.809: failed to load module appmenu-gtk-module

### ISSUE THREAD

**Issue by tykayn** [getting-things-gnome/gtg#593]
since a few days i cannot run GTG, i don't know why.
here is the error i get from CLI.

```
 flatpak run org.gnome.GTG 
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

Gtk-Message: 09:54:10.809: Failed to load module "appmenu-gtk-module"
Gtk-Message: 09:54:10.809: Failed to load module "appmenu-gtk-module"
Gtk-Message: 09:54:10.993: Failed to load module "appmenu-gtk-module"
Traceback (most recent call last):
  File "/app/bin/gtg", line 62, in <module>
    from GTG.gtk.application import Application
  File "/app/lib/python3.7/site-packages/GTG/gtk/application.py", line 35, in <module>
    from GTG.core.datastore import DataStore
  File "/app/lib/python3.7/site-packages/GTG/core/datastore.py", line 43, in <module>
    class DataStore():
  File "/app/lib/python3.7/site-packages/GTG/core/datastore.py", line 52, in DataStore
    def __init__(self, global_conf=CoreConfig()):
  File "/app/lib/python3.7/site-packages/GTG/core/config.py", line 192, in __init__
    self._conf = open_config_file(self._conf_path)
  File "/app/lib/python3.7/site-packages/GTG/core/config.py", line 86, in open_config_file
    config.read(config_file)
  File "/usr/lib/python3.7/configparser.py", line 696, in read
    self._read(fp, filename)
  File "/usr/lib/python3.7/configparser.py", line 1014, in _read
    for lineno, line in enumerate(fp, start=1):
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x99 in position 0: invalid start byte

```

 flatpak --version
Flatpak 1.6.5

 lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

i have gtk3-nocsd already installed with apt, and libgtk3-nocsd.so.0 si present and owned by root.
 ll /usr/lib/x86_64-linux-gnu/libgtk3-nocsd.so.0
-rwSr--r-- 1 root root 26K mars   3  2018 /usr/lib/x86_64-linux-gnu/libgtk3-nocsd.so.0

but i did not touched this file before, no idea how flatpak cannot run gtg anymore.
also, i have gimp installed with flatpak and it works just fine. there are the only two flatpaks i have.

**Comment by diegogangl** [comment]
Sounds like something went wrong with your config file. What are the contents of `~/.var/app/org.gnome.GTG/config/gtg.conf` ?

**Comment by tykayn** [comment]
i have `no file ~/.var/app/org.gnome.GTG/config/gtg.conf but i have`
~/.var/app/org.gnome.GTG/config/gtg/gtg.conf

and it contains somme gibberish stuff:
åF·ya'0?sñÑlšÉr#ï3[sœ=ÏmšÉr#ï3[sœ=ÏmšÉr#ï3[sœ=ÏmšÉr#ï3[sœ=ÏmšÉr#ï3[sœ=ÏmšÉr#ï3[sœ=ÏmšÉr#ï3[sœ=ÏmšÉr#ï3[sœ=ÏmšÉr#ï3[sœ=ÏmšÉr#ï3[sœ=ÏmšÉr#ï3[sœ=ÏmšÉr#ï3[sœ=ÏmšÉr#ï3[sœ=ÏmšÉr#ï3[sœ=ÏmšÉr#ï3[sœ=ÏmšÉr#ï3[sœ=ÏmšÉr#ï3[sœ=ÏmšÉr#ï3[sœ=ÏmšÉr#ï3[sœ=ÏmšÉr#ï3[sœ=ÏmšÉr#ï3[sœ=ÏmšÉr#ï3[sœ=ÏmšÉr#ï3[sœ=ÏmšÉr#ï3[s

**Comment by diegogangl** [comment]
Yup, that file got messed up somehow. Just delete it and gtg will make a new with the default config. I don't think there's anything in GTG that can break a file like that though. Did you have any issues with your HDD?

**Comment by tykayn** [comment]
noice, it works!
i have nextcloud syncing this folder, could come from that.
anyway deleting this file makes it work, thanks :)
‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by diegogangl** [comment]
Awesome!
