### ISSUE TITLE
Regression: after using complex saved searches, unable to save simple searches in git version

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#600]
This works in 0.4, and used to work in the  git version until recently (I think).

If I search for "the" (or any other word), save it, close the app... on startup that saved search is gone. It never made it into `gtg_data.xml`

**Comment by diegogangl** [comment]
:thinking: Can't reproduce here

**Comment by nekohayo** [comment]
Happens with complex searches, when you have something this in your data file:

![foo](https://user-images.githubusercontent.com/479401/113031390-a5d2b380-915c-11eb-898c-f9009a04145b.png)

So with the "screenshots" dataset, it's basically:

1. Create and save a search for `@errands !or @money` and for `@travels !or @stuff2pay`
2. Restart the app
3. Search for "the" and try to save the search
4. Restart the app
5. Notice the search for "the" is absent from the UI and the data file.

**Comment by zeddo123** [comment]
Yep can confirm, this happens to me on master.
