### ISSUE TITLE
Links to local documents dont work

### ISSUE THREAD

**Issue by gsupreeth** [getting-things-gnome/gtg#615]
Links to local documents don't do anything when you click on them.

1. Drag and drop a file onto a task note. GTG creates a link.
2. Click on the link doesn't do anything.

BTW, web URLs work perfectly.

Tested on Linux Mint, GTG 0.5

I created an account to log this in. I'll report other issues if I come across them. Thank you for resurrecting this project. I have warm memories of the original.

**Comment by nekohayo** [comment]
I wonder if URIs are handled by `xdg-open` (or portals), and if they are not, if they should (if that would fix this)

**Comment by diegogangl** [comment]
Seems to be a flatpak problem, because the git version can open files fine. It prints an "file not found" error, even though the path is correct.

**Comment by nekohayo** [comment]
Ah then it's the sandboxing going on. Either this is something to be solved through portals, or wider permissions for everyone, or users tweaking the permissions on their end using [flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal) (?), or a case of wontfix/can'tfix...

**Comment by diegogangl** [comment]
Fixed in master

**Comment by yash-fn** [comment]
As an add on, what are your guys' thoughts about gtg directly importing files internally rather than via links, which would require user to maintain files externally? If external file is changed/moved/etc it can disrupt link. To prevent problem of disk space, it could perhaps utilize hard links if files are present on same filesystem.

**Comment by Neui** [comment]
> As an add on, what are your guys' thoughts about gtg directly importing files internally rather than via links, which would require user to maintain files externally? If external file is changed/moved/etc it can disrupt link. To prevent problem of disk space, it could perhaps utilize hard links if files are present on same filesystem.

Sounds similar to #477
