### ISSUE TITLE
GTG 0.5 doesn't launch when there were dots (periods) in tag names, leading to tag duplication in gtg_data.xml

### ISSUE THREAD

**Issue by MarvinMep** [getting-things-gnome/gtg#616]
Earlier today GTG was working well, but at the end of the day it just started to refuse to open. I tried it on the terminal and got this message:

> flatpak run org.gnome.GTG -d
Gtk-Message: 20:46:19.412: Failed to load module "xapp-gtk3-module"
GNOME keyring not found, passwords will be not stored after restarting GTG
2021-04-08 20:46:19,642 - DEBUG - application:set_logging:587 - Debug output enabled.

Running GTG 0.5 on Debian Bullseye, GNOME 3.38.4, X.Org 1.20.10, flatpak 1.10.2-1.

**Comment by diegogangl** [comment]
Hi, sounds like a problem in your sytstem. Do you have xapp-gtk3 installed?
If you have libxapp installed, maybe something is messing with your enviroment variables?
https://forum.manjaro.org/t/failed-to-load-module-xapp-gtk3-module/46039/3

**Comment by MarvinMep** [comment]
> Hi, sounds like a problem in your system. Do you have xapp-gtk3 installed?
> If you have libxapp installed, maybe something is messing with your enviroment variables?
> https://forum.manjaro.org/t/failed-to-load-module-xapp-gtk3-module/46039/3

I removed libxapp (it was as dependency on another package, which I also removed), and the message still appears. I Installed it again and the message persists.

Anyway, I tried other flatpak apps, they all show the same message (actually, they "fail to load canberra-gtk-module" too), but  they all run normally.

Now I believe the problem was never xapp-gtk3-module.

**Comment by MarvinMep** [comment]
Turns out that the issue really wasn't the xapp-gtk3-module.

I removed GTG and installed it again. Now the debug option started to work properly and I could see that there was an error in my gtg_data.xml.

I used to have a tag with a dot in its name, "ruas.rio". After the last upgrade, GTG refused to mark tasks with dots in the tag name. Trying to solve the problem I renamed that tag (several times) ending up with the tag "ruas" instead of "ruas.rio". It seems that GTG messed up the gtg_data.xml. 

After seeing on debug the errors "IndexError: tag ruas was already in the datastore" and "AttributeError: 'NoneType' object has no attribute 'get_config'", I opened the gtg_data.xml and there were several tags only with name (partial names of other tags) and id. I deleted those lines, and everything got back to normal.

Now, I don't know if the tag with/without dot is another issue to file.

**Comment by diegogangl** [comment]
That's weird, I wonder why the debug didn't throw anything the first time. I can see the dot issue now, the dot was only considered a separator if it was followed by a space. That changed in this version because we use `\w` in the regex

**Comment by MarvinMep** [comment]
> That's weird, I wonder why the debug didn't throw anything the first time.

I think we'll never know why. 🤷

>  I can see the dot issue now, the dot was only considered a separator if it was followed by a space. That changed in this version because we use `\w` in the regex

So the impossibility to use dots in tags names isn't an issue, is a new rule.

I don't think this issue is related with #621 as mentioned by @seraph, because I have neither libxapp nor python3-xapp installed on my system and everything works fine now (even the app icon), despite the messages on terminal.

I believe the real issue here is more related to #605 (in combination with the dot in tag), so I believe we can close this one here.

**Comment by diegogangl** [comment]
Closing this in favor of the other issues then, thanks for reporting!
