### ISSUE TITLE
Compatibility with GNOME Builder: `bwrap: execvp gtg: No such file or directory` when running GTG from Builder

### ISSUE THREAD

**Issue by severin-lemaignan** [getting-things-gnome/gtg#622]
### Dev environment:

- Ubuntu 20.04
- Builder 3.38.2

### Steps to reproduce:

- launch Builder
- clone the github GTG repo (cloned at 68305160b6)
- Builder asks to install the Gnome 40 runtimes; they successfully download + install
- Pressing the 'Run' button triggers the installation of all the Python3 dependencies (as execpted)
- However execution ultimately fails with `bwrap: execvp gtg: No such file or directory`

Note that `gtg` runs well if started from the command-line with `launch.sh`. As such, this issue is purely a Gnome Builder integration issue. Please let me know if you think it should be reported to the Gnome Builder issue tracker instead.

**Comment by diegogangl** [comment]
I can build fine with master, running Fedora 33. Maybe it's an issue with the flatpak version?

**Comment by nekohayo** [comment]
I'm marking this as a low hanging fruit to encourage packaging-savvy or potential new contributors to contribute a fix for this, otherwise I think it's unlikely to be addressed in the near future.
