### ISSUE TITLE
Calendar picker widget to select the monthly or yearly recurrence date always default to September 2020

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#637]
When I open the task editor for a task that was never set to recurring before, and want to set it to repeating **monthly**, or **yearly** (at a specific date), it always shows me the calendar picker widget defaulting to September 20, 2020:

![Screenshot from 2021-04-20 10-19-16](https://user-images.githubusercontent.com/479401/115412246-23209f80-a1c2-11eb-82d5-4fbbee00b316.png)

...which makes no sense, until you see that every task in the file format defaults to having this:

```
      <recurring enabled="false">
        <term>None</term>
        <updated_date>9999-12-30T00:00:00</updated_date>
      </recurring>
```

Why does it have those lines of fake data if it doesn't even use recurrence, shouldn't those be added only when used? In any case, the date is invalid, and the code shouldn't use it.

More generally, I think the recurring task's date picker should use the month of the task's current due date (if set) or the current month as a fallback.

**Comment by Neui** [comment]
Looks like it was hardcoded to September 2020 in the ui file: https://github.com/getting-things-gnome/gtg/blob/4bd89aa55cb15b5cd077afd5fc08c2718ef51528/GTG/gtk/data/task_editor.ui#L516-L517

A grep for "year_calender" and "month_calender" doesn't show any results (except of that UI file of course), so the code to update the calendar simply needs yet to be added.

The fake data thing should go to a separate issue.

**Comment by zeddo123** [comment]
Oh my bad, I haven't noticed the date being hardcoded. I'll look into the the fake data.
