### ISSUE TITLE
Flatpak version failing to find custom cursor theme

### ISSUE THREAD

**Issue by santiagocezar** [getting-things-gnome/gtg#647]
Version 0.5 from Flathub doesn't launch when using a custom cursor theme installed by the user. It does work after giving the app permission to read ~/.icons, or by moving the cursor to $XDG_DATA_DIRS (but then it doesn't work in every other host application).

This is the application log

```
Gdk-Message: 11:52:13.791: Unable to load hand2 from the cursor theme
Traceback (most recent call last):
  File "/app/bin/gtg", line 79, in <module>
    from GTG.gtk.application import Application
  File "/app/lib/python3.8/site-packages/GTG/gtk/application.py", line 28, in <module>
    from GTG.gtk.browser.main_window import MainWindow
  File "/app/lib/python3.8/site-packages/GTG/gtk/browser/main_window.py", line 35, in <module>
    from GTG.gtk.browser import quick_add
  File "/app/lib/python3.8/site-packages/GTG/gtk/browser/quick_add.py", line 27, in <module>
    from GTG.gtk.editor.taskview import TAG_REGEX
  File "/app/lib/python3.8/site-packages/GTG/gtk/editor/taskview.py", line 54, in <module>
    class TaskView(Gtk.TextView):
  File "/app/lib/python3.8/site-packages/GTG/gtk/editor/taskview.py", line 78, in TaskView
    CURSOR_HAND = Gdk.Cursor.new(Gdk.CursorType.HAND2)
TypeError: constructor returned NULL
```

After building the Flatpak using latest commit (`2208e62` when writing this issue), the app does work, but it uses a fall-back cursor theme that's missing many cursor sprites. 

![shot1](https://user-images.githubusercontent.com/48573316/116162775-d7438e00-a6cc-11eb-8aca-c6014def27d4.png)

When hovering a link it displays the previous cursor sprite, instead of a 👆...
![shot2](https://user-images.githubusercontent.com/48573316/116151268-c68a1c80-a6ba-11eb-98fd-7cf63af1a7db.png)

and it throws many exceptions when moving the mouse (that are catched by a try-except block)
```
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/GTG/gtk/editor/taskview.py", line 616, in on_mouse_move
    cursor = Gdk.Cursor.new_for_display(window.get_display(),
TypeError: constructor returned NULL
``` 

I think adding a `--filesystem=/home/$USER/.icons/:ro` in the flathub manifest could solve this issue

**Comment by nekohayo** [comment]
Possibly fixed by the merged pull request 658? Ideally we would need some way for @santiagocezar to test this (or maybe they know how to build a flatpak on their end)?

**Comment by santiagocezar** [comment]
It does work now! Here is a screenshot:
![Screenshot_20210711_195929](https://user-images.githubusercontent.com/48573316/125212266-89c5ce80-e282-11eb-856a-c1e2b724d7c1.png)

**Comment by tonylom3** [comment]
Hello, I have the same issue and it wasn't clear from the comments what the actual fix was.

Thanks,
-Tony
