### ISSUE TITLE
Keyboard shortcut to focus sidebar

### ISSUE THREAD

**Issue by tetrahedon7** [getting-things-gnome/gtg#648]
Like the one that places focus on the Quick Add Entry field. It could come useful for people like me who switch between projects a lot, to add tasks and such, and hence need to switch between task-list and sidebar frequently (it takes a shift-tab-tab-tab to do that currently). Thanks

**Comment by diegogangl** [comment]
Cool idea!

**Comment by niconil** [comment]
i suggest <Ctrl>B to place focus on sidebar (side_B_ar)

see PR #678
