### ISSUE TITLE
Quick entry does not recognize translated string for "due" (german translation)

### ISSUE THREAD

**Issue by morhe-blip** [getting-things-gnome/gtg#652]
I found some strange behaviour of the quick entry field (commit c53bf0ee73bfec9c87570f7f9afdbd6ea9e5ff5a). I will open a separate issue for each observation. If this is wrong, feel free to put them into one issue.

Description:
Using the quick entry (with german translation) the keyword "fällig" does not create a task with this mentioned due date. However if using "due", it works.

Reproduction:
Create a task "Test tags:test fällig:2021-04-30" via quick entry, it creates a task "Test fällig:20" with the tag test (which I inserted for finding the tasks afterwards).
The trimming of the date is another issue mentioned separately.

If this is just a stupid issue because "due" is not intended to be used translated in quick entry (which kind of is the same with "tags" I think), close it.

**Comment by Neui** [comment]
> I found some strange behaviour of the quick entry field (commit c53bf0e).

Do you mean since that commit or was that the commit you just tested on?

> If this is just a stupid issue because "due" is not intended to be used translated in quick entry (which kind of is the same with "tags" I think), close it.

Showing a german interface but then not accepting german input is in my opinion at least wrong.
It is supposed to be translated (when I looked at the code last time), and it worked before when I tested the german translation, so this is a valid regression.

**Comment by morhe-blip** [comment]
It is the commit I tested this on. I think, that I saw this behaviour before, but I did not test it at that time.
