### ISSUE TITLE
Gamify does not count subtasks that were marked as done by using the checkbox inside parent task

### ISSUE THREAD

**Issue by morhe-blip** [getting-things-gnome/gtg#654]
Description and reproduction:

Create a task with one or more subtasks. Tick the checkbox inside the parent tasks description. The task is marked as done, however the counter is not increased.

If the subtasks are marked as done via right-click or Ctrl-D, it works.

**Comment by zeddo123** [comment]
I was able to reproduce it. It's probably that both ways to mark a task as done have different signals.
