### ISSUE TITLE
Too many DBus error messages

### ISSUE THREAD

**Issue by tkdchen** [getting-things-gnome/gtg#66]
Version: devel

When cannot connect to Tomboy and Gnote, Gnote and Tomboy backend reports too many error messages with same content. This would bother users.

In my laptop, running GTG from master branch, Tomboy backend will report 4 connection error messags, and then 32 errors if try to enable again.

As of writing this issue, I did not get time to look into the implementation, have no idea why this happens. If it does, by design, it would be improved to reduce the number of error messages. For instance, only one message when the first time of trying to connect.

**Comment by izidormatusov** [comment]
Can you provide more context? What error messages do you get?

**Comment by nekohayo** [comment]
Presumably if the requested info has not been provided in 4 years, this is not happening. Reopen if the current development version still is affected, particularly if you can provide a patch.
