### ISSUE TITLE
GTG not opening 

### ISSUE THREAD

**Issue by mattro200** [getting-things-gnome/gtg#667]
Hello!
When trying to launch GTG via launcher, it does not open, no error given. When launching via terminal I receive the following message and GTG does not open: 

> Gtk-Message: 12:27:18.679: Failed to load module "appmenu-gtk-module"
> GNOME keyring not found, passwords will be not stored after restarting GTG

Currently on version .5 on Pop_OS 20.10
I've restarted as well as uninstall/reinstalled the flatpak with no change. 
Any suggestions on what to try next?
Thanks in advance!
Matthew

**Comment by Neui** [comment]
Probably there is already GTG running in the background but in a hung state, and starting gtg will redirect to the backgrounded process. Try `flatpak kill org.gnome.GTG` if you're running with flatpak, or kill an `python3` process that has `gtg` in the command line.
Then re-run GTG from the terminal for any error messages.

You may also look into #616 and #629.

**Comment by nekohayo** [comment]
@mattro200, did you manage to get it working? Did it turn out to be related to cursor themes like issue #647 maybe?

**Comment by nekohayo** [comment]
Closing as no further information was provided.
