### ISSUE TITLE
Columns can get hidden outside the bounds of the window

### ISSUE THREAD

**Issue by cauebs** [getting-things-gnome/gtg#669]
I was using GTG on a 1080p output, and the Due column was at the far right. When I moved the window to a "768p" output, the column was completely hidden, and scrolling horizontally is not possible.

Possible fixes:
- adding a horizontal scrollbar to this view;
- constraining columns' position by automatically resizing to fit inside the window bounds.

**Comment by Neui** [comment]
Yep, can confirm. If you expand the name column so the columns get hidden, if you pay attention to the quick add entry at the bottom, you'll see that it'll also "expand" (the emoji-icon then also gets hidden). This appears to me to be a widget expanding thing and that is where I would start looking fixing the bug.
