### ISSUE TITLE
Few questions about current development of GTG

### ISSUE THREAD

**Issue by khurshid-alam** [getting-things-gnome/gtg#67]
1. When will gtk3 port of GTG land on Ubuntu? The version for Utopic & Vivid are still  on 0.3.1.
   AFAIK it was scheduled for 0.3.2 (https://launchpad.net/gtg/+milestone/0.3.2) but Gnome wiki says 3.1.

2. Does daily build ppa use GTK-3 port? It doesn't look like it does. It should be updated from git master. It saves us from the trouble of compiling it by ourselves.

3. @NimitS1 said on many bug-reports on launchpad that, there would be complete rework of GTG backend/syncronization services (read RTM). Has the rework started yet? What is the roadmap?

    RTM is my favorite backend service, but on Trusty, Utopic it is broken because of this bug:      https://bugs.launchpad.net/gtg/+bug/1286495. @PawanHegde prepared a patch for it, but it was rejected by @NimitS1 . I tested the patch, after applying it sync with RTM relatively works well...at least from GTG->RTM. So may be it can be merged for 3.1.

4. `python-evolution` has been depreciated (as gnome-python-desktop is NOT active anymore). So it can not be synced with evolution-date-server. What is the developer's view on this? 

5. Any future plan to include a new sync-service like Todoist (https://en.todoist.com/)?

Thanks.

**Comment by izidormatusov** [comment]
Hi, sorry for late answer.

Original plan was to release gtk3 port of GTG as 0.3.2. For various reason it didn't happen. We're going to skip that release. @jakubbrindza works on making GTG to adhere to GNOME 3 design principles as his GSoC project this summer. After summer, we should release GTG 0.4

Daily build PPA uses master branch. Gtk3 port was merged long time ago, so the current version of Daily GTG PPA has it.

I'm not sure what's the state of rework of synchronization services. @NimitS1 didn't come back to me with the result of the project. In general, support of synchronization in GTG is not great currently.

Evolution synchronisation was originally planned to be returned to GTG after porting it to gtk3. However, it took us too much time (GTG is developed by volunteers doing it in their free time) and python-evolution is deprecated. I couldn't find any support for gobject introspection for evolution, so synchronization with evolution is not possible any more.

If you are still interested in synchronization with Todoist, please create a separate issue.

**Comment by khurshid-alam** [comment]
Thanks for clearing things up. I will open a new issue with todoist.
