### ISSUE TITLE
README Dependencies command for Debian 10 (buster) backports small change

### ISSUE THREAD

**Issue by odoood** [getting-things-gnome/gtg#679]
Small change for code under Dependencies section:

```
echo 'deb http://deb.debian.org/debian buster-backports main' | sudo tee /etc/apt/sources.list
```

should use `-a` option for `tee` to avoid overwriting `sources.list`:

```
echo 'deb http://deb.debian.org/debian buster-backports main' | sudo tee -a /etc/apt/sources.list
```

**Comment by RoneoOrg** [comment]
This issue is **critical** IMHO, thanks for the PR

**Comment by nekohayo** [comment]
Hi! I was catching up on two months' worth of mails/notifications today and just saw this, sorry for the delay.
Thank you very much @odoood for reporting this, @neui for providing a fix and @RoneoOrg for counter-checking it too! The documentation fix has now been pushed to master, hopefully preventing potential accidents for people looking at those instructions.
