### ISSUE TITLE
GTK deprecation warnings

### ISSUE THREAD

**Issue by shtrom** [getting-things-gnome/gtg#68]
With PyGTK-2.24.0 and gtg from commit 1328f1d, I am getting the following warning on startup:

    /usr/lib/python3.4/site-packages/GTG/gtk/browser/browser.py:87: Warning: The property GtkImageMenuItem:use-stock is deprecated and shouldn't be used anymore. It will be removed in a future version.
      self.builder.add_from_file(GnomeConfig.BROWSER_UI_FILE)
    /usr/lib/python3.4/site-packages/GTG/gtk/browser/browser.py:87: Warning: The property GtkImageMenuItem:always-show-image is deprecated and shouldn't be used anymore. It will be removed in a future version.
      self.builder.add_from_file(GnomeConfig.BROWSER_UI_FILE)
    /usr/lib/python3.4/site-packages/GTG/gtk/browser/browser.py:87: Warning: The property GtkSettings:gtk-menu-images is deprecated and shouldn't be used anymore. It will be removed in a future version.
      self.builder.add_from_file(GnomeConfig.BROWSER_UI_FILE)
    /usr/lib/python3.4/site-packages/GTG/gtk/browser/browser.py:87: Warning: The property GtkToolButton:stock-id is deprecated and shouldn't be used anymore. It will be removed in a future version.
      self.builder.add_from_file(GnomeConfig.BROWSER_UI_FILE)
    /usr/lib/python3.4/site-packages/GTG/gtk/browser/browser.py:87: Warning: The property GtkMisc:xpad is deprecated and shouldn't be used anymore. It will be removed in a future version.
      self.builder.add_from_file(GnomeConfig.BROWSER_UI_FILE)
    /usr/lib/python3.4/site-packages/GTG/gtk/browser/browser.py:87: Warning: The property GtkImage:stock is deprecated and shouldn't be used anymore. It will be removed in a future version.
      self.builder.add_from_file(GnomeConfig.BROWSER_UI_FILE)
    /usr/lib/python3.4/site-packages/GTG/gtk/browser/browser.py:87: Warning: The property GtkEntry:secondary-icon-stock is deprecated and shouldn't be used anymore. It will be removed in a future version.
      self.builder.add_from_file(GnomeConfig.BROWSER_UI_FILE)
    /usr/lib/python3.4/site-packages/GTG/gtk/browser/browser.py:87: Warning: The property GtkImageMenuItem:accel-group is deprecated and shouldn't be used anymore. It will be removed in a future version.
      self.builder.add_from_file(GnomeConfig.BROWSER_UI_FILE)
    /usr/lib/python3.4/site-packages/GTG/gtk/browser/browser.py:87: Warning: The property GtkImageMenuItem:image is deprecated and shouldn't be used anymore. It will be removed in a future version.
      self.builder.add_from_file(GnomeConfig.BROWSER_UI_FILE)
    /usr/lib/python3.4/site-packages/GTG/gtk/editor/calendar.py:46: Warning: The property GtkSettings:gtk-button-images is deprecated and shouldn't be used anymore. It will be removed in a future version.
      self.__builder.add_from_file(GnomeConfig.CALENDAR_UI_FILE)
    /usr/lib/python3.4/site-packages/GTG/plugins/urgency_color/urgency_color.py:204: Warning: The property GtkAlignment:top-padding is deprecated and shouldn't be used anymore. It will be removed in a future version.
      'preferences.ui'))
    /usr/lib/python3.4/site-packages/GTG/plugins/urgency_color/urgency_color.py:204: Warning: The property GtkAlignment:bottom-padding is deprecated and shouldn't be used anymore. It will be removed in a future version.
      'preferences.ui'))
    /usr/lib/python3.4/site-packages/GTG/plugins/urgency_color/urgency_color.py:204: Warning: The property GtkAlignment:left-padding is deprecated and shouldn't be used anymore. It will be removed in a future version.
      'preferences.ui'))
    /usr/lib/python3.4/site-packages/GTG/gtk/preferences.py:85: Warning: The property GtkMisc:ypad is deprecated and shouldn't be used anymore. It will be removed in a future version.
      builder.add_from_file(ViewConfig.PREFERENCES_UI_FILE)
    /usr/lib/python3.4/site-packages/GTG/gtk/preferences.py:85: Warning: The property GtkAlignment:yalign is deprecated and shouldn't be used anymore. It will be removed in a future version.
      builder.add_from_file(ViewConfig.PREFERENCES_UI_FILE)
    /usr/lib/python3.4/site-packages/GTG/gtk/plugins.py:139: Warning: The property GtkTreeView:rules-hint is deprecated and shouldn't be used anymore. It will be removed in a future version.
      builder.add_from_file(ViewConfig.PLUGINS_UI_FILE)

Then, when I try to edit a task's description, I get an additional warning:

    /usr/lib/python3.4/site-packages/GTG/gtk/editor/editor.py:63: Warning: The property GtkContainer:resize-mode is deprecated and shouldn't be used anymore. It will be removed in a future version.
      self.builder.add_from_file(GnomeConfig.EDITOR_UI_FILE)

I'm not sure if this is related, but GTG hangs after this warning (though
sending a KeyboardInterrupt with a ^C wakes it up).

**Comment by izidormatusov** [comment]
Properties that are still in the code even after #144 is merged:

 - [ ] use-stock
 - [ ] stock-id
 - [ ] xpad
 - [ ] ypad
 - [ ] stock
 - [ ] top-padding
 - [ ] bottom-padding
 - [ ] left-padding
 - [ ] xalign
 - [ ] yalign
 - [ ] rules-hint

deprecated widgets:

 - [ ] GtkImageMenuItem
 - [ ] GtkAlignment

**Comment by jakubbrindza** [comment]
None of these issues should be present in the latest dev version of GTG anymore. All of them were resolved in #144 and #155 .

Therefore I believe we can close this bug. If you find something, though, please comment, I'll fix it.
