### ISSUE TITLE
"Remove icon" is problematic

### ISSUE THREAD

**Issue by zareami10** [getting-things-gnome/gtg#682]
Edit a tag and and add an icon/emoji to it. Then edit it again to remove the icon. Everything looks good at this point. But restart GTG and now all the icons you removed are back again.

In other words, I can not remove icons from tags in 0.5.

**Comment by Neui** [comment]
Can reproduce in v0.5 but not in git master. [Bisect](https://git-scm.com/docs/git-bisect) points me to https://github.com/getting-things-gnome/gtg/commit/4bd89aa55cb15b5cd077afd5fc08c2718ef51528 being the version it fixed that bug.

So for v0.5 you need to edit the data file manually, by closing GTG completely, opening `gtg_tasks.xml` (`~/.local/share/gtg/gtg_tasks.xml`, or `~/.var/app/org.gnome.GTG/data/gtg/gtg_tasks.xml` for flatpak) in an normal plain-text editor, find an line starting with `<tag` that has the name in the same line with `name="the_tag_name"`, and then delete the `icon="🕷"` on the same line, save and start GTG again.

Also, if you're there, it can be a good point to make a backup of that file in case GTG doesn't load any more. (Note that if that happens, you need to kill the python3 process manually unfortunately)

**Comment by nekohayo** [comment]
Closing as duplicate, as indeed the issue was fixed in the future version.
