### ISSUE TITLE
FR: links to files don't open

### ISSUE THREAD

**Issue by yash-fn** [getting-things-gnome/gtg#694]
It appears that while I can import file links into the app via drag and drop, they don't open the link within app. Cumbersome to manually translate links. Ideal if option to open file links via default file browser/etc. Maybe also option to import attachments and handle them internally? Experimenting using this app with .ora rasters of handwritten notes to manage complex tasks.

**Comment by Neui** [comment]
I think this is a duplicate of #615

**Comment by yash-fn** [comment]
Oh my bad. you are right.
