### ISSUE TITLE
Does this program use gtk-2.0?

### ISSUE THREAD

**Issue by eggbean** [getting-things-gnome/gtg#702]
I use a GNOME theme that only has gtk-3.0 support (AdMin). I use the dark/slim variant but when using gtg the title bars appear full size and white. Therefore it is not using the gtk-3.0 theme.

I don't know a lot about theming, so I am asking if this program use gtk-2.0, as as far I can see from the documentation it's supposed to be using gtk-3.0?

**Comment by Neui** [comment]
Yes, gtg is using gtk3. Not sure why it bugs out, will need to test later.
Just a guess: Does toggling the dark mode in the settings do anything? It should enable the dark variant of the theme, if available if I remember correctly.

**Comment by Neui** [comment]
I tried the theme and I couldn't really reproduce it. The [admin-gtk3-light-slimmer-vertex](https://github.com/nrhodes91/AdMin) (and -osx) at most had the "brigthest" titlebar among the dark variants, but isn't bright white as you seem to indicate.

What I've noticed that when GTG is in developer mode, that theme makes the header bar darker, at most: (top is GTG in dev, bottom is `gtk3-demo` without the dev style)

![GTG in dev mode and gtk3-demo with a bit brigther titlebar](https://user-images.githubusercontent.com/1196130/131399573-a3040a49-200e-4bd2-b344-c247a68706b4.png)

About the last thing in my comments (x11-forwarding): It uses the default Ubuntu theme "Yaru", which uses dark titlebars, but makes then explicitly makes it bright when the application is using developer styles (which looks out of place and thus what I thought is buggy...)

Can you try to start GTG with the `GTK_DEBUG=interactive` envionment variable? Assuming you have GTG installed locally (not flatpak), then use `GTK_DEBUG=interactive gtg`, or `flatpak run --env=GTK_DEBUG=interactive org.gnome.GTG` (untested) when using flatpak.

An additional window should open. Go to the visual tab and see what the current theme is. If it looks correct there, try clicking on the bullseye thing at the top left, click on the header bar, and select "CSS-Nodes" in the drop-down menu and check the `background-*` properties what they are. The origin-column also gives the line in the CSS file you could look into why it is using that property.

For me it looks like that with the admin-gtk3-light-slimmer-vertex theme in non-dev GTG (that debug window still uses the default theme which is Yaru, ignore about that):
![debugger window showing the css nodes for the headerbar](https://user-images.githubusercontent.com/1196130/131401008-34243c54-2c8a-4435-b7df-5d2f384672d7.png)

**Comment by nekohayo** [comment]
If you are using the Flatpak version, that's due to Flatpak sandboxing apps from your wider system's themes/files; see https://www.linuxuprising.com/2018/05/how-to-get-flatpak-apps-to-use-correct.html

**Comment by eggbean** [comment]
Thank you for the replies. And yes, I am using the flatpack version. I am using Pop!_OS and it seems that there are no apt packages from the upstream Debian/Ubuntu repositories. That clears that up. Cheers.
