### ISSUE TITLE
[Feature Request] Sticky notes

### ISSUE THREAD

**Issue by VaZark** [getting-things-gnome/gtg#714]
Are there any plans to add a sticky notes functionality for tasks?

One way to do it would be to ensure that the sticky notes window can be just the current task window with the header bar hidden and the actions bar fading in on selecting the task. 

Do you think it will be easy to implement as a plugin or does it requires changes to the core application?

**Comment by diegogangl** [comment]
This can be done through the plugin system. You could add an option to the right click menu to pop a task into a sticky note. Then you'd have to create a `Gtk.Window` yourself, put a textview (or taskview) in it and fill it with the task contents.

**Comment by nekohayo** [comment]
This ticket is a bit unfocused, so let's close this in favor of:

* #948 
* #974
