### ISSUE TITLE
Change shortcut for dismiss task

### ISSUE THREAD

**Issue by VaZark** [getting-things-gnome/gtg#715]
`Ctrl + I` is practically the universal format for italics. So anytime I reach for italics (out of habit), I end up dismissing the task by accident. It would be more intuitive to use `Ctrl + Shift + D` as _Dismiss_ since `Ctrl + D` is used already for _Done_ because they perform similar actions

**Comment by koleesch** [comment]
My fix for this issue.. https://github.com/getting-things-gnome/gtg/pull/736
