### ISSUE TITLE
Fix/update the tasks anonymization script to match the new file format

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#733]
For issues that require samples of very complex/heavy task files to trigger them, it would be nice if I could turn my current task file into an anonymized version that could become part of the sample datasets for testing alongside the "Bryce" one. I think this would probably be the only way for devs to encounter (hopefully reliably) issues like #595 and #724.

The file to fix is `scripts/anonymize_task_file.py`

Ideally it should be able to find even flatpaked data files, but in the meantime if it requires specifying a manual file path as the argument (like `./anonymize_task_file.py input.xml anonymized_output.xml` ) then that would already make it useful as a stopgap.

Currently, if you try to use that script with a file with the 0.5 file format, you get this traceback:

```
  File "scripts/./anonymize_task_file.py", line 110, in <module>
    main()
  File "scripts/./anonymize_task_file.py", line 106, in main
    anonymize(xmlfile, outputfile)
  File "scripts/./anonymize_task_file.py", line 52, in anonymize
    contentnode = contentnode[0].childNodes[0]
IndexError: list index out of range
```

**Comment by diegogangl** [comment]
The best solution IMO would be to incorporate this into an export plugin. That way we can ask users to export their tasks through GTG, rather than running a script
