### ISSUE TITLE
Heavy CPU usage 

### ISSUE THREAD

**Issue by mizzunet** [getting-things-gnome/gtg#738]
![image](https://user-images.githubusercontent.com/10193999/145927026-bc7ea829-edb8-4008-86f5-279ee9ad0bf8.png)

While doing absolutely nothing. I only have 4 tasks
This happens when GTG opened at startup by SwayWM config like,
```
exec gtg
```
Opening normally does not seem to have this issue.

Version: v0.5-127-ga523934a

**Comment by mizzunet** [comment]
I think it was due to [Anancy](https://github.com/Nefelim4ag/Ananicy), I uninstalled it once and rebooted. 

No issue now

**Comment by mizzunet** [comment]
Unfortunately, it's still happening

**Comment by diegogangl** [comment]
Does it still happen when starting on boot only or always?

**Comment by mizzunet** [comment]
Only if it's started by SwayWM config which executes once logged in.

Not in any other scenarios.

**Comment by mizzunet** [comment]
I installed `gtg-git` package, now it's gone.

Not sure if it will in the future
