### ISSUE TITLE
Tags do not support some non-english characters. Like "Ö"

### ISSUE THREAD

**Issue by johannesgunnar** [getting-things-gnome/gtg#74]
Bug experienced in Getting Things GNOME! 0.3.1 from the Ubuntu Software Center.

When creating new tasks with new tags, some non english characters break the tags and make the tag only contain the letters up to the said problem letter.

I've tested with most, if not all, special Icelandic characters, but for some reasons the only one that I've found to break tags is "Ö".

For example, the tag @Tölvan becomes @T.

![screenshot from 2014-11-23 15 41 58](https://cloud.githubusercontent.com/assets/2924543/5158071/91d8aac8-7328-11e4-9866-4bfb02fb3930.png)

**Comment by johannesgunnar** [comment]
forgot about this issue and for some reasons didn't see the notification when you posted this. Sorry about that.

Oddly enough, when I reinstalled GTG and tried it out, that error was not there anymore. And I can't seem to reproduce it. Although I guess it's not needed, I am going to paste the output of those two commands here just in case. But I guess you can mark this issue as closed for now.

```
locale
LANG=is_IS.UTF-8
LANGUAGE=is:en
LC_CTYPE="is_IS.UTF-8"
LC_NUMERIC=is_IS.UTF-8
LC_TIME=is_IS.UTF-8
LC_COLLATE="is_IS.UTF-8"
LC_MONETARY=is_IS.UTF-8
LC_MESSAGES="is_IS.UTF-8"
LC_PAPER=is_IS.UTF-8
LC_NAME=is_IS.UTF-8
LC_ADDRESS=is_IS.UTF-8
LC_TELEPHONE=is_IS.UTF-8
LC_MEASUREMENT=is_IS.UTF-8
LC_IDENTIFICATION=is_IS.UTF-8
LC_ALL=
```

```
python --version
Python 2.7.6
```

**Comment by rivaldi8** [comment]
I haven't been able to reproduce it with your setting either. Maybe there was something wrong temporarily that has been fixed.

**Comment by izidormatusov** [comment]
As suggested, closing this issue.
