### ISSUE TITLE
ctrl+shift+p after startup/filter change throws uncaught exception

### ISSUE THREAD

**Issue by Neui** [getting-things-gnome/gtg#753]
After startup or changing filters, nothing will be selected and ctrl+shift+p to create a new parent will throw an uncaught exception. This means the "crash" dialog comes up, but since it is not fatal you can still continue using GTG.

```
Traceback (most recent call last):
  File ".local_build/install/lib/python3.8/site-packages/GTG/gtk/application.py", line 338, in add_parent
    if self.browser.have_same_parent():
  File ".local_build/install/lib/python3.8/site-packages/GTG/gtk/browser/main_window.py", line 1385, in have_same_parent
    first_task = self.req.get_task(selected_tasks[0])
IndexError: list index out of range
```

Found out because I wanted to look if pressing that shortcut in an taskeditor window would create an parent task of that task.

**Comment by diegogangl** [comment]
Found another bug while fixing this one, if you change panes the selected tasks are cleared in the UI but not in `browser.get_selected_tasks()` ¯\\_(ツ)_/¯
