### ISSUE TITLE
Deleting tasks by mistake is too easy

### ISSUE THREAD

**Issue by mihaelacr** [getting-things-gnome/gtg#76]
I started using gtg recently. The UI is quite nice and I started adding more and more tasks to it (some of them quite urgent).

However, right now I just pressed by mistake Delete, and there is no confirmation pop up and no way of retrieving my tasks. I just lost some important tasks that I had to do. One should be able to easily undo the deletion of tasks.

**Comment by izidormatusov** [comment]
There is a pop up before deleting any task.
