### ISSUE TITLE
Meson 0.61.1 incompatible with Meson 0.60.2

### ISSUE THREAD

**Issue by zeddo123** [getting-things-gnome/gtg#768]
When I try running gtg with `./launch.sh`, meson v0.61 complains:
```bash
Running the development/debug version - using separate user directories
Your data is in the 'tmp' subdirectory with the 'default' dataset.
-----------------------------------------------------------------------
ninja: Entering directory `.local_build'
[0/1] Installing files.

ERROR: Build directory has been generated with Meson version 0.60.2, which is incompatible with the current version 0.61.1.
FAILED: meson-install
/usr/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
```

**Comment by Neui** [comment]
Not sure if we can really fix this in our side, since it seems to be more of a Meson problem. `rm -rf .local_build` should make it work again (by generating the build folder with your current version of Meson)

**Comment by zeddo123** [comment]
>rm -rf .local_build should make it work again (by generating the build folder with your current version of Meson)

okey dokey. I'll close the issua.
