### ISSUE TITLE
Version tags

### ISSUE THREAD

**Issue by Kayvlim** [getting-things-gnome/gtg#77]
Is there any way I can find the version 0.3.1 in the repository other than trying to correlate the logs with it?

I read in http://gtg.readthedocs.org/en/latest/releases/v0.3.1.html that version 0.3.1 was released at 24/11/2013, so it looks like the corresponding commit was f29aa263d0be51d1744eba6f9b48c46d631df341 , but there should be a tag pointing to it.

By the way, I'm looking for this version because Debian's GTG is quite unstable. Is this a known problem?

Thanks!

**Comment by izidormatusov** [comment]
Fixed both 0.3.1 tag and the rest of tags: https://github.com/getting-things-gnome/gtg/releases

Thanks for noticing it!
