### ISSUE TITLE
Problem with opening GTG after installing Hamster plugin

### ISSUE THREAD

**Issue by Shahin-rmz** [getting-things-gnome/gtg#770]
Hello,
I could install the gtg and open it and work with it.
after syncing with my nextcloud (for first time), the tasks could successfully sync.
The problem is, after playing around, and installing plugins, the app crashed and never opened.
This is the error which I got when opening.

`
Context: Activation
None
Dev GTG: gtg v0.5-160-ged8000de
CPython 3.8.10 (default, Nov 26 2021, 20:14:08)   [GCC 9.3.0]
GTK 3.24.20, GLib 2.64.2
PyGLib 3.36.0, PyGObject 3.36.0
Linux-5.13.0-28-generic-x86_64-with-glibc2.29
`

Also the log file shows the following error:

`
org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.Hamster was not provided by any .service file
`
how can I disable a plugin from source code?
it seems like gnome hamster is not working.

**Comment by Neui** [comment]
Try this: Open `${XDG_CONFIG_HOME:-$HOME/.config}/gtg/gtg.conf` (or `~/.var/app/org.gnome.GTG/config/gtg/gtg.conf` when using the flatpak version) in an plain text editor, and find `[plugins]`, and under it remove `hamster` from `enabled =` (possibly with a comma if you had enabled multiple plugins), start GTG. Make sure GTG is closed (no process running).

**Comment by Shahin-rmz** [comment]
@Neui Thank you so much.
The app opens now.
do you have any idea how can I enable the plugins the right way?

**Comment by Neui** [comment]
You need to have Hamster installed to use the Hamster plugin, but it seems the plugin makes GTG "crash" when it doesn't find Hamster (which is indeed a bug that should be fixed)

**Comment by Shahin-rmz** [comment]
actually the gnu.Hamster is already installed (and works with Flatpack instance of GTG). Maybe the path can not be recognized.

**Comment by nekohayo** [comment]
I suppose this is a duplicate of issue #683, essentially, and possibly related to PR #676.

**Comment by piotrzientarski** [comment]
GTG does not have permission to access the D-Bus session bus, I turned it on in Flatseal and now GTG is talking to Hamster.
