### ISSUE TITLE
Nose is unmaintained and we need to switch [RFC]

### ISSUE THREAD

**Issue by diegogangl** [getting-things-gnome/gtg#773]
According to the Nose website:

> Nose has been in maintenance mode for the past several years and will likely cease without a new person/team to take over maintainership. New projects should consider using [Nose2](https://github.com/nose-devs/nose2), [py.test](http://pytest.org/), or just plain unittest/unittest2.

https://nose.readthedocs.io/en/latest/

Well this has certainly happened, nose doesn't work anymore with Python 3.10. Fedora has already switched to it in 35, so I just got hit by this. Making the tests run with Python 3.9 while 3.10 is the default makes the `gi` module fail for some reason, so that's also not an option.

The question is whether we should switch to Nose2 (easier?) or move to Pytest (nicer?). Or use something different altogether

**Comment by Neui** [comment]
I am not really in the python ecosystem, so I don't really have a preference (yet). Pytest has a page about [using nose tests](https://docs.pytest.org/en/latest/how-to/nose.html) which could make it easier to migrate, but looking at [nose2 vs nose differences](https://docs.nose2.io/en/latest/differences.html#nose2-is-not-nose) it seems nose2 may just (mostly) work with our existing tests (haven't really dealt with them yet).

I have a small (paused) [python project myself](https://github.com/Neui/python-glib-log-bridge), but looking at the test I mainly just use `unittest` it seems, and I think I just ran whatever `setup.py test` (or something like that?) does...

**Comment by diegogangl** [comment]
> Pytest has a page about [using nose tests](https://docs.pytest.org/en/latest/how-to/nose.html) which could make it easier to migrate

That's a great find! They even have a migration script, might try that out later
