### ISSUE TITLE
./launch.sh just opens in it's own directory

### ISSUE THREAD

**Issue by Shahin-rmz** [getting-things-gnome/gtg#774]
Hello,
With the help of the community I could manage to install the right versionn of the GTG and make it work.
However, if I wanted to open the GTG from the desktop, with terminal, simply it is not possible.
Just tried different methods, and all didn't work properly.
`bash /path/to/file/launch.sh`
`. /path/to/file/launch.sh`
etc.
Also tried to open debug.sh which also didn't work properly.
how is it possible?
as a noob pythonist, I can help making plugins. (have made some projects so far).
would be thankful if you could tell me what is the solution of opening `launch.sh` file and documentation regarding making plugins.
Best

**Comment by Neui** [comment]
`launch.sh` uses the current working directory to create the folder containing the isolated GTG data. So you want to `cd` into the repo first: `bash -c 'cd path/to/repo && ./launch.sh'`.

If you want to use a dev copy locally as your main thing, then create a new empty directory, `meson path/to/the/repo --prefix=~/.local/ && ninja && ninja install`, which installs it into your local user folder (and have stuff such as a menu entry).
You need to `ninja install` in that folder again to update your local copy.

**Comment by Neui** [comment]
For plugins you want to take a look at the [GTG/plugins](GTG/plugins) directory (for the existing plugins) and the [Plugin Development Guide](https://github.com/getting-things-gnome/gtg/blob/master/docs/contributors/plugin%20development%20guide.md) document. Note that the `.gtg-plugin.desktop` is just a symlink to the corresponding `.gtg-plugin` to make translation work for the plugin metadata.

**Comment by Shahin-rmz** [comment]
`bash -c 'cd path/to/repo && ./launch.sh'`.

this command was exactly what I wanted.
just wanted a shortcut in my task manager wo launch gtg from desktop easily.
made a bash script with that command and put it in task manager.
Thanks.
will defenitely read the [Plugin development guide](https://github.com/getting-things-gnome/gtg/blob/master/docs/contributors/plugin%20development%20guide.md). 
have some ideas to have pomodoro connected with gtg to increase my (and community) productivity.
Best.
