### ISSUE TITLE
Gamify plugin tracebacks when trying to change the number of daily tasks

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#782]
This is what I got the first time I tried to bump the number of daily tasks, in the git version:

```python-traceback
Traceback (most recent call last):
  File "GTG/plugins/gamify/gamify.py", line 411, in on_preferences_changed
    ui_mode = int(self.get_ui_mode_combo_value())
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

Strangely, in subsequent tries, it didn't seem to traceback. Maybe something to do with saving stuff?

**Comment by diegogangl** [comment]
Probably want to set the `GtkComboBox:id-column` prop when loading
https://docs.gtk.org/gtk3/method.ComboBox.get_active_id.html

**Comment by zeddo123** [comment]
For some reason, I was using `set_entry_text_column` to set the ui mode combobox which didn't really set the item. I've changed to `set_active`.
