### ISSUE TITLE
Gamify substracts 1 when marking a task as not to be done (dismissing), and when reopening a task that was dismissed

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#783]
Marking a task as done (`Ctrl+D`) increases the daily tasks counter by 1, however:

* Dismissing a task (`Ctrl+i`) _substracts_ 1 from the counter; shouldn't it leave the counter untouched?
* "Reopening" a task substracts 1 from the counter, which is correct if the closed task was a closed "done" task, but if it was a closed "dismissed" task then you're creating a point deficit, whereas it should probably be neutral instead? (currently, combined with the other issue above, this means you can actually -2 the total if you dismiss a task and then undismiss it)

I'm just guessing that these are bugs rather than intended behavior :)

**Comment by zeddo123** [comment]
> I'm just guessing that these are bugs rather than intended behavior :)

Kinda. I was planning to add these features in the next version (of Gamify) but I completely forgot. I'll add them now that I have some free time.
