### ISSUE TITLE
Slow startup with lists "bigger than 500 positions"?

### ISSUE THREAD

**Issue by user82622** [getting-things-gnome/gtg#788]
With lists bigger than around 500 positions the flatpak takes forever to start on fedora 32, 33, 34, 35. At a certain point it is no starting at all, the debug option is not showing any useful output, it just stops at a random:
```
xxxx-xx-xx xx:xx:xx,xxx - DEBUG - task:add_child:687 - adding child xxx to task xxx

```

**Comment by nekohayo** [comment]
@user82622 could this be issue #903? I will assume so.
