### ISSUE TITLE
Cannot change tag name

### ISSUE THREAD

**Issue by tkdchen** [getting-things-gnome/gtg#79]
I have lots of tags and would like to change some tags' name, for example from work to Work. There is already a dialog to allow to edit a tag and the name is editable. But, whatever I modify the name, it has no effect, the original tag name does not get changed.

**Comment by Zeg31** [comment]
Same problem here.

My workaround: 
- use View/Tags Sidebar
- select tag "work"
- select all tasks (ctrl + a)
- rightClick + Modify Tags
- use "!work Work" for change work to Work

**Comment by diegogangl** [comment]
There's a UI for this in Master but no code (yet)

**Comment by nekohayo** [comment]
When I saw this ticket I was a bit confused as to what the isuse is. Is it just that it doesn't work when the word is the same but the CaSiNg is different? Or that the tag gets renamed but "all the tasks that had the old tag don't get automatically retagged" (which would be quite a bit more tricky to implement)?

**Comment by diegogangl** [comment]
If you right click a tag in the sidebar and select "edit tag", there's a text input for the name. But it doesn't do anything because it's not plugged into any code.

**Comment by diegogangl** [comment]
This was fixed recently, but I forgot about this issue :)
