### ISSUE TITLE
NameError: name 'new_root' is not defined

### ISSUE THREAD

**Issue by Kuphi** [getting-things-gnome/gtg#796]
I installed gtg 0.6 (current master) on Ubuntu 22.04 without issues.
I then installed Ubuntu 21.10 because I had other issues with Ubuntu 22.04. I copied my gtg folder to Ubuntu 21.10 and tried to run ./launch.sh without success because I forgot to install the dependencies.

Now I discarded the old folder and installed gtg anew. I get the following error:

`**Context:** Startup

```python-traceback
Traceback (most recent call last):
  File "/home/username/gtg/.local_build/install/lib/python3.9/site-packages/GTG/gtk/application.py", line 111, in do_startup
    datastore.register_backend(backend_dic)
  File "/home/username/gtg/.local_build/install/lib/python3.9/site-packages/GTG/core/datastore.py", line 444, in register_backend
    backend.this_is_the_first_run(None)
  File "/home/username/gtg/.local_build/install/lib/python3.9/site-packages/GTG/backends/backend_localfile.py", line 162, in this_is_the_first_run
    root = firstrun_tasks.generate()
  File "/home/username/gtg/.local_build/install/lib/python3.9/site-packages/GTG/core/firstrun_tasks.py", line 362, in generate
    root = xml.skeleton()
  File "/home/username/gtg/.local_build/install/lib/python3.9/site-packages/GTG/core/xml.py", line 343, in skeleton
    new_root.set('appVersion', '0.6')
NameError: name 'new_root' is not defined
```

**Software versions:**
* GTG (debug version) v0.5-213-g86e89533
* CPython 3.9.7 (default, Sep 10 2021, 14:59:43)   [GCC 11.2.0]
* GTK 3.24.30, GLib 2.68.4
* PyGLib 3.40.1, PyGObject 3.40.1
* Linux-5.16.10-051610-generic-x86_64-with-glibc2.34`

How can I fix it? Thanks!

**Comment by Neui** [comment]
This is because very recently and accidentally pushed a faulty change. I fixed in the new PR, but this only happens on a first run (when GTG doesn't find an `gtg_data,xml`, so it would be the first run of the application), so if you have existing data, put them inside the `tmp/default/xdg/...` folders.
Note that `./launch.sh` uses the `tmp` dir inside the repository, so if that is where you have stored your data and just deleted it, then you've got a problem.

**Comment by Kuphi** [comment]
> This is because very recently and accidentally pushed a faulty change. I fixed in the new PR, but this only happens on a first run (when GTG doesn't find an `gtg_data,xml`, so it would be the first run of the application), so if you have existing data, put them inside the `tmp/default/xdg/...` folders. Note that `./launch.sh` uses the `tmp` dir inside the repository, so if that is where you have stored your data and just deleted it, then you've got a problem.

Thank you! I applied your change and it's fixed :)
https://github.com/getting-things-gnome/gtg/pull/797/commits/1e141386532b8380fa1b5bfaef8a65eec31ce42d
