### ISSUE TITLE
Dots are treated as part of a tag while commas are not

### ISSUE THREAD

**Issue by kocio-pl** [getting-things-gnome/gtg#807]
Forked from https://github.com/getting-things-gnome/gtg/issues/793#issuecomment-1046144111

It's an interesting question how GTG should treat commas, dots and other punctuation marks at the end of a tag, because task description can be simply a sentence. Currently it looks strange to me that dots get included as part of the tag.

**Comment by diegogangl** [comment]
If you are doing web dev you could have tags for different websites: `@gtg.com`, `@some.other.xyz`. The dot can also be used as a word separator, like the underscore and others. `@home_stuff`, `@home.stuff` or `@home-stuff`. Commas aren't so useful for that. We could tweak the regex to discard a dot at the end though
