### ISSUE TITLE
Wrong tag icon instead of "blush"

### ISSUE THREAD

**Issue by kocio-pl** [getting-things-gnome/gtg#817]
Current git version on Ubuntu 20.04.

Selecting this icon ("blush"? 3 row, 4 item) in tag properties gives different, simplified "smiley":

![Zrzut ekranu z 2022-02-26 01-50-27](https://user-images.githubusercontent.com/5439713/155822195-582beb89-d37f-4d53-9925-b1d44670db32.png)

**Comment by diegogangl** [comment]
lmao, sorry :p

Yeah, I can confirm this happens with blush and also with the brush emoji (search for paint). It doesn't happen in a text editor, so it might be related to either Gtk labels or something we're doing with the label
