### ISSUE TITLE
Allow more flexible time for recurring tasks

### ISSUE THREAD

**Issue by kocio-pl** [getting-things-gnome/gtg#820]
It would be nice to allow flexible periods between recurring tasks, like for example "2 weeks", "3 months" or "4 years". Currently we have only 1 day/month/year available - with the exception of 2 days.

**Comment by zeddo123** [comment]
Hi,
Thanks for opening an issue. Hopefully we'll be having a rewrite of the core in the 0.7 version that will add more complex options for recurring tasks.

#627
