### ISSUE TITLE
Hide special tags

### ISSUE THREAD

**Issue by kocio-pl** [getting-things-gnome/gtg#825]
I'm not sure what is the use of showing special tags in tag list browser, I guess they should be hidden here:

![Zrzut ekranu z 2022-02-27 08-00-18](https://user-images.githubusercontent.com/5439713/155872035-2ca55015-597a-482f-b37b-d1cb91ef2b8b.png)

**Comment by diegogangl** [comment]
Definitely a bug

**Comment by kocio-pl** [comment]
It's good to remember to also hide saved searches, which look like `@__SAVED_SEARCH_$name` tag.
