### ISSUE TITLE
CalDav on Flatpak

### ISSUE THREAD

**Issue by Jules-Bertholet** [getting-things-gnome/gtg#841]
The CalDav backend isn't available on the latest Flathub release (0.6) because the Python `caldav` dependency isn't available. It would be great if this feature was made available in the Flathub build.

**Comment by kocio-pl** [comment]
I also see that export plugin dependencies are not visible from flatpak version, even if they are visible and work with git version after using this:

https://github.com/getting-things-gnome/gtg#solving-dependencies-for-plugins-optional

That looks like a general dependency problem.

**Comment by diegogangl** [comment]
Sorry about that, just pushed an updated flatpak

**Comment by kocio-pl** [comment]
CalDAV problem seems to be fixed, but export plugin dependencies are still not visible.

**Comment by nekohayo** [comment]
The remainder of the issue here (as per @kocio-pl's comment) is issue #784.
