### ISSUE TITLE
Replace the limited set of tag icons by emojis

### ISSUE THREAD

**Issue by tkdchen** [getting-things-gnome/gtg#85]
It would be a nice feature to allow to specify a custom icon for a tag.

**Comment by vrutkovs** [comment]
This is already supported in 0.3.x - see 'Click to set icon' button
![tag editor](https://lh5.googleusercontent.com/-U9XmCzB--0Q/UJmV9wPkxII/AAAAAAAAAFM/byDjXKqhcvc/w800-h800/gtg-0.3-tag-editor.png)

**Comment by tkdchen** [comment]
@vrutkovs  cannot select other icons from file system except the fixed set of icon listed by "Click To Set Icon"

**Comment by vrutkovs** [comment]
@tkdchen ah, yes, that would be a nice feature. At least updating a current list of available icons would be nice

**Comment by izidormatusov** [comment]
This is outside of the scope of 0.4 milestone that we would release after summer.

**Comment by nekohayo** [comment]
I would like to see the oldschool icons support replaced by GTK3's emojis support. It would be much nicer-looking, more portable, and reduce the amount of stuff we need to ship with the app. Patches welcome!

**Comment by nekohayo** [comment]
A tiny nitpick for @diegogangl in commit 18cfd501b:
* The 10% opaque default label icon is very hard to see in a light theme?
* The "Remove icon" button label is not marked as translatable, I think?
