### ISSUE TITLE
tagging task twice can lead to untag task

### ISSUE THREAD

**Issue by patipatini** [getting-things-gnome/gtg#87]
Steps to reproduce :
- create a new task
- edit the new task
- enter "@mysupertag" in description in order to tag task -> the tag is colored in yellow (as expected)
- continue editing, then enter **again** "@mysupertag" in description -> the second tag is colored in yellow while the first is uncolored (as expected ? Maybe _this_ is the cause of the bug)
- at this point, if I close the task editor, all is ok : even if first tag is not colored, the second one is, thus the task is correctly tagged with @mysupertag
- but if I keep editing the task, and I erase the second tag, the first tag is not colored in yellow again
- if I close the task editor now, the task contains @mysupertag in description BUT IS NOT TAGGED !

The bug is fixed if I open again the task editor : at the opening, the remaining tag is colored in yellow again (I supposed that the description is parsed again)... But as it IS possible to have a @mysupertag in a task description without having this task tagged "mysupertag", this remains a problem.

**Comment by nekohayo** [comment]
Ah yes, I've often encountered this bug in the stable series such as 0.3.1. I don't know if it affects the git version (would be nice if someone can test it carefully).

Patches welcome, and since it's not a release blocker, I'm changing the milestone and labels accordingly.

**Comment by diegogangl** [comment]
Not happening in Master
