### ISSUE TITLE
FYI - Hamster plugin bugs config file

### ISSUE THREAD

**Issue by phnv** [getting-things-gnome/gtg#883]
GTG simply  wouldn't start after I closed it.

this is the log message:

```
\**Context:** Activation
```python-traceback
None```

**Software versions:**
* Getting Things GNOME! v0.6
* CPython 3.9.9 (main, Nov 10 2011, 15:00:00)   [GCC 11.2.0]
* GTK 3.24.33, GLib 2.70.5
* PyGLib 3.42.0, PyGObject 3.42.0
* Linux-5.4.0-107-generic-x86_64-with-glibc2.33
```

1 - I tried deleting the gtg_data.xml file to bring back the default file and it wouldn't run either. 

2 - So i did the same to the gtg.config file. And it worked, however as expected it reseted all configs, including plugins. 

3 - I tried to debug the gtg.config file by testing each field... turns out *deleting hamster from enabled plugins at gtg.config solves the issue*

Probably some deeper compatibility problems there since the plugin wouldn't work anyway. Hope I saved someone some time and tears ;)

**Comment by Neui** [comment]
Also see https://github.com/getting-things-gnome/gtg/issues/770#issuecomment-1030678522 (same solution)

**Comment by phnv** [comment]
Ops total duplicate, hanks for pointing that out!
It seems though I can't delete the issue just close it.
