### ISSUE TITLE
Make task windows of type "utility" and transient_for the main window

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#89]
GTG creates standard window types for all open tasks. Instead, they should do this:

```
window.set_transient_for(the_main_window)
window.set_type_hint(Gdk.WindowTypeHint.UTILITY)
```

This will allow window managers like GNOME Shell (and its extensions) to properly understand that those windows are part of that application and should be grouped/attached together in overview mode; it can also help extensions such as "Window blur effects" figure out that it shouldn't blur out things within the same application.

**Comment by shtrom** [comment]
:+1:

**Comment by shtrom** [comment]
That said, I'm not sure whether open task windows should be modal (not sure if it's the same as transient, here) to the main window, as one might want to have a few task windows open, and still be able to interact with the task list.

Also, I note that, with 8415e62, Gnome Shell already groups the windows together when Alt+Tabbing.

**Comment by nekohayo** [comment]
This has been fixed, actually.
