### ISSUE TITLE
Choosing @ or # for tags

### ISSUE THREAD

**Issue by Nico7as** [getting-things-gnome/gtg#898]
Hi,

Apple added tag support to its ToDo app, but it uses the # instead of GTG's @ 

Would it be much work to had a choice between # and @ to make a tag?

That would be very useful for people using iPhones, like me.

PS : I use Nextcloud to store my tasks, and it also uses Tags, but I can't figure how...
I'm not sure Nextcloud understands GTG Tag system.
It'd be great to have a common system.

**Comment by Neui** [comment]
Related: #238

**Comment by diegogangl** [comment]
Hi @Nico7as , could you share these ideas on #238, so we have everything in one place?
Closing this as duplicated in the meantime
