### ISSUE TITLE
GTG hangs/freeze when trying to show the new/edit task dialog.

### ISSUE THREAD

**Issue by shtrom** [getting-things-gnome/gtg#90]
I've noticed this issue on three ArchLinux machines, two recently installed, with the gtg-git package (which I maintain) [0]. I already mentioned this issue in #68, but I have some more details.

Much more often than not, when I try to bring the task-edition dialog (to edit an existing one, or to create a new one), gtg freezes before showing the dialog. The only way to unfreeze it is to send it a SIGINT, either with Ctrl+C on the console, or killall -INT. This happens with:
 * any recent version of gtg-git
 * fvwm or Gnome 3
 * Remember the Milk sync backend
   * accented characters in some tasks' title or description

[0] https://aur.archlinux.org/packages/gtg-git/

**Comment by dunnodun** [comment]
Have the exact same issue. But it seems like the project is completely dead :(
