### ISSUE TITLE
gtg does not detect gnome keyring whereas it is running

### ISSUE THREAD

**Issue by symphorien** [getting-things-gnome/gtg#902]
gtg prints the following warning on startup:
`GNOME keyring not found, passwords will be not stored after restarting GTG`

but I know for sure that gnome keyring is running: evolution uses it, and the process is running
```
symphor+    2206  0.0  0.0 458692  6476 ?        SLl  mai31   0:01 /nix/store/rl1l21v8n2r9lqcksvs41ghafannv7yw-gnome-keyring-40.0/bin/gnome-keyring-daemon --daemonize --login
symphor+   54208  0.0  0.0   6444   688 ?        S    juin01   0:00 /nix/store/a5p60sx0v825bq8brhyxl5kyxvvfnvlm-openssh-9.0p1/bin/ssh-agent -D -a /run/user/1000/keyring/.ssh
symphor+  333467  0.0  0.0 223608  2696 pts/6    R+   15:11   0:00 grep keyring
```

could it be due to a missing dependency?

Software versions:

    Getting Things GNOME! 0.6.0
    CPython 3.9.13 (main, May 17 2022, 14:19:07) [GCC 11.3.0]
    GTK 3.24.34, GLib 2.72.1
    PyGLib 3.42.1, PyGObject 3.42.1
    Linux-5.15.41-x86_64-with-glibc2.34

**Comment by Neui** [comment]
Looking at the [implementation](https://github.com/getting-things-gnome/gtg/blob/v0.6/GTG/core/keyring.py), it seems either `libsecret` is missing, or the Introspection (GIR) files are missing for libsecret. It unfortunately isn't mentioned in the readme, this should be added there.

To check the more exact error you get, you can activate the developer console plugin, then open the developer console (via the menu top right), then type:
```python
import gi; gi.require_version('Secret', '1'); from gi.repository import Secret
```

If nothing appears (other than the `>>>` prompt), it should have worked. If not, an error should be visible.

**Comment by symphorien** [comment]
Thanks, libsecret was the missing dependency.

As a downstream packager, it would be nice if meson reported these optional dependencies as not found explicitely like git here:
```
The Meson build system
Version: 0.61.2
Source dir: /build/source
Build dir: /build/source/build
Build type: native build
Project name: gtg
Project version: 0.6.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program python3 found: YES (/nix/store/553d7c4xcwp9j1a1gb9cb1s9ry3x1pi9-python3-3.9.13/bin/python3)
WARNING: Python files installed by Meson might not be found by python interpreter.
 This warning can be avoided by setting "python.platlibdir" option.
WARNING: Python files installed by Meson might not be found by python interpreter.
 This warning can be avoided by setting "python.purelibdir" option.
Configuring prefix-gtg.sh using configuration
Configuring gtg using configuration
Configuring local-gtg using configuration
Program git found: NO
Configuring info.py using configuration
Configuring org.gnome.GTG.appdata.xml.in using configuration
Configuring org.gnome.GTG.desktop.in using configuration
Configuring org.gnome.GTG.service using configuration
Program xgettext found: YES (/nix/store/qcxh9dg5cmnr22bipmfw0igi6wn8s7s6-gettext-0.21/bin/xgettext)
Program itstool found: YES (/nix/store/h8v7qrnvaacs0a9f68l8h9m6hcqiipc9-itstool-2.0.6/bin/itstool)
Program msgmerge found: YES (/nix/store/qcxh9dg5cmnr22bipmfw0igi6wn8s7s6-gettext-0.21/bin/msgmerge)
Program msgfmt found: YES (/nix/store/qcxh9dg5cmnr22bipmfw0igi6wn8s7s6-gettext-0.21/bin/msgfmt)
Build targets in project: 71
```

Also it would be nice to have an explicit message on stderr (this is the case of missing caldav python module).

I'm leaving this open for this missing message, but feel free to close.
