### ISSUE TITLE
Pending Caldav Issues

### ISSUE THREAD

**Issue by samyak-jain** [getting-things-gnome/gtg#909]
I just started using gtg with caldav for sync and I started noticing a bunch of issues. Tasks that I had added would suddenly get deleted and subtasks would not get synced correctly. After doing some digging, it looks like these are known issues: https://github.com/getting-things-gnome/gtg/pull/525#issuecomment-942461968
and 
https://github.com/getting-things-gnome/gtg/issues/892

I would suggest maybe marking the sync service as experimental until we can figure out a solution to these. I haven't worked with the codebase before, so if someone more familar with the codebase knows where to start, I would be happy to contribute fixes for these myself. 
I was lucky enough to have a backup of all the tasks that gtg deleted for me, however I can imagine it being pretty frustrating if gtg ended up deleting your tasks that you spent a lot of time writing.

**Comment by samyak-jain** [comment]
Hey @diegogangl. Thanks! Your work on PR #894 looks great and I'm really excited for it. I have a few questions. After this PR, will the Caldav backend need to be rewritten? Will the updated caldav backend be part of this PR or will someone else have to tackle it once you're done with this? Do you know how far off we are from working on these issues? (not asking for any commitment, of course. Just want a rough idea). 

Asking these questions since if the backend system will be undergoing only minor changes and if the PR is still too far out, it might be worth just fixing them now and then porting them over to the new system.

**Comment by madhums** [comment]
Any idea when caldav backend can start working? Or what needs to happen in order to get this to work? I am happy to chip in and spend hours working on this if anyone is willing to guide me and point in the right direction.

**Comment by diegogangl** [comment]
Hi @madhums, we need to get #894 merged (we're pretty close!) and then start fixing the backend. I already did a good portion of the work, but some parts might need to be rewritten to fit the new core.

**Comment by madhums** [comment]
Any idea when the latest version will be released to the stores? (It still points to version 0.6 which is a year old)

![Screenshot from 2024-02-27 11-12-53](https://github.com/getting-things-gnome/gtg/assets/123815/f12077d9-bb30-41d8-8b64-0b02770b8028)

**Comment by nekohayo** [comment]
When all (or as much as possible) of the "regression"-labelled and/or "0.7-targetted" issues mentioned in #737 are fixed. With some luck and lots of community involvement, this can happen pretty quickly, I would think.
