### ISSUE TITLE
Tasks created from emails with `%` signs can corrupt the config file, preventing GTG from starting

### ISSUE THREAD

**Issue by mokilcde** [getting-things-gnome/gtg#914]
Hi!

I edit the close date from a few entries. After about ten tasks it crash regulary

**Context:** Global generic exception

```python-traceback
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/GTG/gtk/browser/main_window.py", line 1065, in on_edit_done_task
    self.app.open_task(tid)
  File "/app/lib/python3.9/site-packages/GTG/gtk/application.py", line 565, in open_task
    self.config.set("opened_tasks", open_tasks)
  File "/app/lib/python3.9/site-packages/GTG/core/config.py", line 177, in set
    self._section[option] = value
  File "/usr/lib/python3.9/configparser.py", line 1262, in __setitem__
    return self._parser.set(self._name, key, value)
  File "/usr/lib/python3.9/configparser.py", line 1204, in set
    super().set(section, option, value)
  File "/usr/lib/python3.9/configparser.py", line 894, in set
    value = self._interpolation.before_set(self, section, option,
  File "/usr/lib/python3.9/configparser.py", line 402, in before_set
    raise ValueError("invalid interpolation syntax in %r at "
ValueError: invalid interpolation syntax in '606fd67a-05e9-4660-a903-2c8ec57216eb,0C4A208C-CF0B-45CF-868C-D5A8609564A9,0653765c-f5d4-4b7f-9903-0065bb258940,9b05a6c5-81e3-4fe5-a70d-3b569f65409c,33d9760d-2e07-4ae4-9c02-1fcdaeb46325,6d73c6d4-8c0f-4154-af3b-dd1af6fdea04,881157127.1182460.1621111335197.JavaMail.payoops@pol-pr-app06.paylater.unzer.com,8cca0b40d3eb5e0b82362e565081138b59f8594e,445b8669e55a7e09862a468bc325a8a2d1f97514,583bddaf-2cf5-437c-ac52-37250c85a68b,8b89f90e88852c0ecad9a5d7ab215f1259a496c3,893dc9334edecf3aea4711a03bd89ce259f09cd3,9d5f49239ddf96b44d2d6f6af711a04324e1eb2f,f2c7906d-7fe2-40b7-a358-f8d82a575f9e,e74197c6855b687db0254222a74988ae4f2bcb5b,36611b24c7d2ee9ab48707765241a7f9a5077543,3c7856aa084de69c2470a87a45896b63e9608aff,d348f38f7edd72e985ef56c017b2a8d1fc497c47,421837532fb3ead8fadb41633937c0cc20fe548c,6f9896c750afb042bb3eab9cbb04ba5cae624aed,b8525090-e3bc-eb20-a8c6-06b8a82d3b1d@schlossgut-hauzendorf.de,7802bf327b474224ca5e0bd5fa1bcfc4bc709d8a,2f1941bd13a3c59c5ea7bf20e3f288bec655cf0f,48046b796988758780d41e44c15aa255afdfd8e8,59bec5da654a3e8ea27fb4c7b57d6dcbb0473414,4ef67c3703bcc8c9c0732fff8936896ca601b6f1,303d700e3787a924ad7e2008d6847ea8277eb432,a6062616cad15fab9b54aeb1f0d76d4a581faf0b,48aac70d30c8457eb506c21164a6b59f276645ca,300d06e9e4344ec9b9078501093503e3%40reg-ufr.bayern.de' at position 1250
```

**Software versions:**
* Getting Things GNOME! v0.6
* CPython 3.9.9 (main, Nov 10 2011, 15:00:00)   [GCC 11.3.0]
* GTK 3.24.34, GLib 2.70.5
* PyGLib 3.42.1, PyGObject 3.42.1
* Linux-5.19.0-rc4-amd64-x86_64-with-glibc2.33

**Comment by nekohayo** [comment]
How are you editing those dates, exactly? You say "close date", but I don't remember the GUI having any part where you can set that. Are you editing the XML by hand or something? If so, what are the values before and after?

**Comment by nekohayo** [comment]
Furthermore, when looking at the output above, which seems like it was supposed to be GTG task ID hashes, you have a couple of weird things in there, like domain names, purely numeric strings combined with email addresses and domain names, etc. It becomes quite obvious if you split that line by commas:

```
606fd67a-05e9-4660-a903-2c8ec57216eb,
0C4A208C-CF0B-45CF-868C-D5A8609564A9,
0653765c-f5d4-4b7f-9903-0065bb258940,
9b05a6c5-81e3-4fe5-a70d-3b569f65409c,
33d9760d-2e07-4ae4-9c02-1fcdaeb46325,
6d73c6d4-8c0f-4154-af3b-dd1af6fdea04,
881157127.1182460.1621111335197.JavaMail.payoops@pol-pr-app06.paylater.unzer.com,
8cca0b40d3eb5e0b82362e565081138b59f8594e,
445b8669e55a7e09862a468bc325a8a2d1f97514,
583bddaf-2cf5-437c-ac52-37250c85a68b,
8b89f90e88852c0ecad9a5d7ab215f1259a496c3,
893dc9334edecf3aea4711a03bd89ce259f09cd3,
9d5f49239ddf96b44d2d6f6af711a04324e1eb2f,
f2c7906d-7fe2-40b7-a358-f8d82a575f9e,
e74197c6855b687db0254222a74988ae4f2bcb5b,
36611b24c7d2ee9ab48707765241a7f9a5077543,
3c7856aa084de69c2470a87a45896b63e9608aff,
d348f38f7edd72e985ef56c017b2a8d1fc497c47,
421837532fb3ead8fadb41633937c0cc20fe548c,
6f9896c750afb042bb3eab9cbb04ba5cae624aed,
b8525090-e3bc-eb20-a8c6-06b8a82d3b1d@schlossgut-hauzendorf.de,
7802bf327b474224ca5e0bd5fa1bcfc4bc709d8a,
2f1941bd13a3c59c5ea7bf20e3f288bec655cf0f,
48046b796988758780d41e44c15aa255afdfd8e8,
59bec5da654a3e8ea27fb4c7b57d6dcbb0473414,
4ef67c3703bcc8c9c0732fff8936896ca601b6f1,
303d700e3787a924ad7e2008d6847ea8277eb432,
a6062616cad15fab9b54aeb1f0d76d4a581faf0b,
48aac70d30c8457eb506c21164a6b59f276645ca,
300d06e9e4344ec9b9078501093503e3%40reg-ufr.bayern.de
```

So what's going on, how did that kind of stuff end up in there?

**Comment by mokilcde** [comment]
I have another task with do strange thing:

I create this task in evolution. I got a mail and create a task from
them. That is the reason for the mail address.

**Context:** Global generic exception

```python-traceback
Traceback (most recent call last):
  File "/app/lib/python3.9/site-
packages/GTG/gtk/browser/main_window.py", line 1065, in
on_edit_done_task
    self.app.open_task(tid)
  File "/app/lib/python3.9/site-packages/GTG/gtk/application.py", line
565, in open_task
    self.config.set("opened_tasks", open_tasks)
  File "/app/lib/python3.9/site-packages/GTG/core/config.py", line 177,
in set
    self._section[option] = value
  File "/usr/lib/python3.9/configparser.py", line 1262, in __setitem__
    return self._parser.set(self._name, key, value)
  File "/usr/lib/python3.9/configparser.py", line 1204, in set
    super().set(section, option, value)
  File "/usr/lib/python3.9/configparser.py", line 894, in set
    value = self._interpolation.before_set(self, section, option,
  File "/usr/lib/python3.9/configparser.py", line 402, in before_set
    raise ValueError("invalid interpolation syntax in %r at "
ValueError: invalid interpolation syntax in
'8af318c0cffeabab4a1788f802454bda8d2396f1,dd7e22c163d4e4ce4b5aec44be393
c8a07364d48,e4d129ff18e79affdb83bd7824b76628db9430cd,300d06e9e4344ec9b9
078501093503e3%40reg-ufr.bayern.de' at position 155
```

**Software versions:**
* Getting Things GNOME! v0.6
* CPython 3.9.9 (main, Nov 10 2011, 15:00:00)   [GCC 11.3.0]
* GTK 3.24.34, GLib 2.70.5
* PyGLib 3.42.1, PyGObject 3.42.1
* Linux-5.19.0-rc4-amd64-x86_64-with-glibc2.33



On Sun, 2022-07-10 at 07:01 -0700, Jeff wrote:
> Furthermore, when looking at the output above, which seems like it
> was supposed to be GTG task ID hashes, you have a couple of weird
> things in there, like domain names, purely numeric strings combined
> with email addresses and domain names, etc. It becomes quite obvious
> if you split that line by commas:
> 606fd67a-05e9-4660-a903-2c8ec57216eb,
> 0C4A208C-CF0B-45CF-868C-D5A8609564A9,
> 0653765c-f5d4-4b7f-9903-0065bb258940,
> 9b05a6c5-81e3-4fe5-a70d-3b569f65409c,
> 33d9760d-2e07-4ae4-9c02-1fcdaeb46325,
> 6d73c6d4-8c0f-4154-af3b-dd1af6fdea04,
> ***@***.***
> app06.paylater.unzer.com,
> 8cca0b40d3eb5e0b82362e565081138b59f8594e,
> 445b8669e55a7e09862a468bc325a8a2d1f97514,
> 583bddaf-2cf5-437c-ac52-37250c85a68b,
> 8b89f90e88852c0ecad9a5d7ab215f1259a496c3,
> 893dc9334edecf3aea4711a03bd89ce259f09cd3,
> 9d5f49239ddf96b44d2d6f6af711a04324e1eb2f,
> f2c7906d-7fe2-40b7-a358-f8d82a575f9e,
> e74197c6855b687db0254222a74988ae4f2bcb5b,
> 36611b24c7d2ee9ab48707765241a7f9a5077543,
> 3c7856aa084de69c2470a87a45896b63e9608aff,
> d348f38f7edd72e985ef56c017b2a8d1fc497c47,
> 421837532fb3ead8fadb41633937c0cc20fe548c,
> 6f9896c750afb042bb3eab9cbb04ba5cae624aed,
> ***@***.***,
> 7802bf327b474224ca5e0bd5fa1bcfc4bc709d8a,
> 2f1941bd13a3c59c5ea7bf20e3f288bec655cf0f,
> 48046b796988758780d41e44c15aa255afdfd8e8,
> 59bec5da654a3e8ea27fb4c7b57d6dcbb0473414,
> 4ef67c3703bcc8c9c0732fff8936896ca601b6f1,
> 303d700e3787a924ad7e2008d6847ea8277eb432,
> a6062616cad15fab9b54aeb1f0d76d4a581faf0b,
> 48aac70d30c8457eb506c21164a6b59f276645ca,
> 300d06e9e4344ec9b9078501093503e3%40reg-ufr.bayern.de
> So what's going on, how did that kind of stuff end up in there?
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>

-- 
CU  
         
  Michael
          
-- 
    ,''`.   
   : :' :   Michael Ott 
   `. `'    e-mail: michael at k-c13 dot org
     `-

Gem. Par. 28 Abs. 4 Bundesdatenschutzgesetz widerspreche ich derNutzung
sowie der Weitergabe meiner personenbezogenen Daten für Zwecke der
Werbung sowie der Markt- oder Meinungsforschung.
