### ISSUE TITLE
No handbook available in Help

### ISSUE THREAD

**Issue by nomiSFI** [getting-things-gnome/gtg#918]
When installing GTG with "flatpak install org.gnome.GTG.flatpakref" there is no handbook visible in Help (Hilfe), the page is just empty.

Linux 5.4.0-42-generic #46-Ubuntu SMP
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=20
DISTRIB_CODENAME=ulyana
DISTRIB_DESCRIPTION="Linux Mint 20 Ulyana"
NAME="Linux Mint"
VERSION="20 (Ulyana)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20"
VERSION_ID="20"

Best regards
Frank

**Comment by ernestum** [comment]
I have the same issue. Additionally, my computer freezes for about half a minute when I open the help page :grimacing:

**Comment by nekohayo** [comment]
This is weird, it works here; do you get any errors when running the flatpak from the terminal?

**Comment by ernestum** [comment]
I did this:
```zsh
~ ➤ /usr/bin/flatpak run --branch=stab~ ➤ /usr/bin/flatpak run --branch=sta~ ➤ /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=gtg --file-forwarding org.gnome.GTG
Gtk-Message: 10:47:15.113: Failed to load module "xapp-gtk3-module"
```
Note: the error message was displayed on startup. Not when I opened the help dialog.

**Comment by nomiSFI** [comment]
Have not used GTD in a while, run /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=gtg --file-forwarding org.gnome.GTG just as ernestum wrote and everthing works.

**Comment by Gnomasz** [comment]
The issue **still occurs** for me while and after running GTG with `/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=gtg --file-forwarding org.gnome.GTG` in a terminal. Opening the Help shows a blank page (screenshot) and an error in the terminal:
```
(WebKitWebProcess:46): Gdk-WARNING **: 11:19:57.251: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 201 error_code 2 request_code 151 (GLX) minor_code 34)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```
Running the same command after setting GDK_SYNCHRONIZE=1 gave the same results. I've tried running GTG with `--gdk-debug misc`, but I get `Unknown option --gdk-debug`. Am I doing it wrong (`usr/bin/flatpak run --branch=stable --arch=x86_64 --command=gtg --file-forwarding org.gnome.GTG --gdk-debug misc`), or does it mean my GTK+ is not configured for debug?

# Installation information
## Package
```
~$ flatpak info org.gnome.GTG

Getting Things GNOME! - Personal tasks and TODO-list items organizer

          ID: org.gnome.GTG
         Ref: app/org.gnome.GTG/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 0.6
     License: GPL-3.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 8.7 MB
     Runtime: org.gnome.Platform/x86_64/41
         Sdk: org.gnome.Sdk/x86_64/41

      Commit: 15ee065eb228d31a1b20376d1486e281a81456956e0b1c79e996d9bf744c3de8
      Parent: 286857f5d6032c21865dd85860ca9e68434ae2473977f45588cdc99233f2326c
     Subject: Revert "Update runtime to GNOME 42" (fc7a823b)
        Date: 2022-05-27 23:45:34 +0000
```
## System information
- Kernel: 5.10.0-23-amd64 x86_64 bits: 64 compiler: gcc v: 10.2.1 
- Desktop: Cinnamon 5.6.8 
- tk: GTK 3.24.24 wm: muffin dm: LightDM
- Distro: LMDE 5 Elsie base: Debian 11.2 bullseye 
- Flatpak 1.10.8
- System languages: Polish, American English (the issue occurs on both)

Flatpak version is old, but it prints no errors while opening Help in GTG that has been opened with `flatpak run -- verbose`.
![GTG help](https://github.com/getting-things-gnome/gtg/assets/58573071/d4caa74e-23a7-4915-ae57-d83501589d72)
