### ISSUE TITLE
crash when using data file from 0.3.1

### ISSUE THREAD

**Issue by paulgear** [getting-things-gnome/gtg#920]
I recently upgraded from Ubuntu 20.04 to 22.04, and gtg 0.3.1 seems to have been removed from their repos. I cloned from git, added the dependencies, and I can run the default data set no problem.  However, when I run `./scripts/import_tasks_from_local.sh`, it doesn't work:

1. If I just leave the data files where they are, the uuid-named XML file gets copied into `tmp/default/xdg/data/gtg/`, but none of my previous tasks show up in the list
2. If I copy the uuid-named XML file over the top of `gtg_data.xml`, gtg crashes with the following traceback on startup:

**Context:** Startup

```python-traceback
Traceback (most recent call last):
  File "/home/paulgear/src/getting-things-gnome/gtg/.local_build/install/lib/python3/dist-packages/GTG/gtk/application.py", line 111, in do_startup
    datastore.register_backend(backend_dic)
  File "/home/paulgear/src/getting-things-gnome/gtg/.local_build/install/lib/python3/dist-packages/GTG/core/datastore.py", line 459, in register_backend
    source.initialize(connect_signals=False)
  File "/home/paulgear/src/getting-things-gnome/gtg/.local_build/install/lib/python3/dist-packages/GTG/core/datastore.py", line 816, in initialize
    self.backend.initialize()
  File "/home/paulgear/src/getting-things-gnome/gtg/.local_build/install/lib/python3/dist-packages/GTG/backends/backend_localfile.py", line 136, in initialize
    self.datastore.load_tag_tree(self.tag_tree)
  File "/home/paulgear/src/getting-things-gnome/gtg/.local_build/install/lib/python3/dist-packages/GTG/core/datastore.py", line 232, in load_tag_tree
    for element in tag_tree.iter('tag'):
AttributeError: 'NoneType' object has no attribute 'iter'
```

**Software versions:**
* GTG (debug version) v0.6
* CPython 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]
* GTK 3.24.33, GLib 2.71.3
* PyGLib 3.42.1, PyGObject 3.42.1
* Linux-5.15.0-43-generic-x86_64-with-glibc2.35

**Comment by diegogangl** [comment]
Did you try renaming the uuid file to `gtg_tasks.xml`? Also don't forget to copy `tags.xml` and `project.xml` (if it exists)
If it's called `gtg_data` gtg won't run the 0.3 versioning

**Comment by paulgear** [comment]
> Did you try renaming the uuid file to `gtg_tasks.xml`? Also don't forget to copy `tags.xml` and `project.xml` (if it exists) If it's called `gtg_data` gtg won't run the 0.3 versioning

Yes, that's how the above crash happens.  If I don't move or copy the uuid file to `gtg_tasks.xml`, gtg proceeds with the default dataset as if I had never run `scripts/import_data_from_local.sh`.

**Comment by diegogangl** [comment]
But did you also copy `tags.xml`? 
(sorry for the delays -_-)

**Comment by paulgear** [comment]
> But did you also copy `tags.xml`? (sorry for the delays -_-)

Yep, that's handled automatically by `scripts/import_data_from_local.sh`, and I confirmed that it's there and looks correct.  If I don't copy/rename the uuid file over `gtg_tasks.xml`, it seems like it never realises a conversion is needed.  Here are the last lines on standard output before the GUI shows:

```
Installing /home/paulgear/src/getting-things-gnome/gtg/docs/user_manual/C/figures/workview.png to /home/paulgear/src/getting-things-gnome/gtg/.local_build/install/share/help/C/gtg/figures
2022-08-18 07:04:57,582 - ERROR - datastore2:save:152 - Error renaming temp file '/home/paulgear/src/getting-things-gnome/gtg/tmp/default/xdg/data/gtg/gtg_data.xml__'
2022-08-18 07:05:00,656 - WARNING - adaptive_button:do_forall:279 - Got error in for but it should've stay valid: AttributeError("'AdaptiveFittingWidget' object has no attribute '_children'")
2022-08-18 07:05:00,667 - ERROR - datastore2:save:152 - Error renaming temp file '/home/paulgear/src/getting-things-gnome/gtg/tmp/default/xdg/data/gtg/gtg_data2.xml__'
```

**Comment by diegogangl** [comment]
Could you try deleting `tmp/default/xdg/config`?

**Comment by paulgear** [comment]
> Could you try deleting `tmp/default/xdg/config`?

No difference, sorry. :cry:

**Comment by diegogangl** [comment]
Could you send me the tags and projects files to dnicolas@gmail.com? You can change the names of the tags if you want to anonymize it a bit (unfortunately our anonymize script only works with the new xml files).

**Comment by paulgear** [comment]
It's got pretty much my whole life in it, including data about work clients, so that's not really an option.  I'll take some time trying to get up to speed with the codebase and see what I can work out.

**Comment by diegogangl** [comment]
I meant only the `tags.xml` and `projects.xml` files (not the tasks). No problem though, let me know if you have any questions o/

**Comment by paulgear** [comment]
Ah, sorry - I misunderstood.  Here are the files, with tags anonymised.
[gtg-files.zip](https://github.com/getting-things-gnome/gtg/files/9413438/gtg-files.zip)

**Comment by paulgear** [comment]
OK, so I got my development environment sorted out enough (thanks to dgangl & Neui on IRC/Matrix) to launch it in the VS Code debugger and dug into the code.  Here's what I worked out:

1. When `versioning.py:is_required()` is called, it hard-codes the old filename as `gtg_tasks.xml`, and the new file is passed in as `gtg_data.xml` (both with a `DATA_DIR` prefix).  This doesn't work because:
    - the old files in my case (copied into place by `scripts/import_tasks_from_local.sh`) are `projects.xml`, `tags.xml`, and _`UUID`_`.xml`
    - new file is already present because the backend startup saves it (see `datastore2.py:first_run()`)

2. `versioning.py:is_required()` and `backend_localfile.py:this_is_the_first_run()` independently hard-code the old file as `gtg_tasks.xml`.  After reviewing the other code in `versioning.py`, I came to the conclusion that it really is about XML conversion (and probably should be renamed to that effect) rather than the decision to run the conversion or not.

3. `backend_localfile.py` has two different blocks of near-identical code, in `this_is_the_first_run()` and `initialize()`, and the latter runs after the former, so there really isn't any need for the second copy of it.

4. Even if we start with the correct local file, there seems to be no logic that opens up `projects.xml` to find the name of the UUID file where the tasks are stored.

So I've created a branch which fixes these issues and has allowed me to successfully convert my data file (which was created by version 0.3.1-4 on Ubuntu 20.04).  I'll submit a PR to link it with this issue shortly.

**Comment by ao2** [comment]
Thanks a lot the the explanation and your fixes @paulgear 

However even after reading the messages here and applying the fixes proposed in https://github.com/getting-things-gnome/gtg/pull/933  to `v0.6`, I was still having problems converting files from 0.3

The difference between `gtg_tasks.xml` and `gtg_data.xml` was not immediate to me, but most importantly I was expecting the new fixes to be able to process `projects.xml`.

However it turned out that the `find_old_uuid_path()` function is not able to process correctly the path set by `./scripts/import_tasks_from_local.sh` in `projects.xml` because it is not absolute, but relative to the location where `import_tasks_from_local.sh` was run.

So let me document here how I managed to get it work, and leave  a "*scriptorial*" which might be useful to someone else:

```sh
#!/bin/sh

set -eu

rm -rf tmp/

# Copy old local data
./scripts/import_tasks_from_local.sh 

# Clean it up
rm -rf tmp/default/xdg/data/gtg/backup/
rm tmp/default/xdg/data/gtg/projects.xml.*
UUID_XML=$(cat tmp/default/xdg/data/gtg/projects.xml | grep backend | sed -e 's/^.*path="\([^"]*\)".*$/\1/g' | head -1)
eval rm '${UUID_XML:-ERROR}.*'

# Remove config to trigger a "first run" which will perform the data format
# conversion.
#
# We could have just stripped `first_run = False` in `backends.conf` but let's
# take the chance to have a clean config.
rm -rf tmp/default/xdg/config/gtg/

# If `gtg_tasks.xml` was not there this would be enough to convert 0.3 files,
# in theory.
#
# However `./scripts/import_tasks_from_local.sh` sets a weird path for the
# UUID file in `tmp/default/xdg/data/gtg/projects.xml` which is neither
# absolute nor relative to DATADIR, but relative to the location where
# `./scripts/import_tasks_from_local.sh` was run.
#
# This might work for `launch.sh` purposes but it breaks the assumptions made
# in `find_old_uuid_path()` resulting in never running the format conversion
# code.


# Copying over the UUID file to `gtg_tasks.xml` would work, but I have no idea
# whether that file name was used in any version between 0.3 and 0.6 or if it is
# only used as a conversion mechanism.
#cp "$UUID_XML" tmp/default/xdg/data/gtg/gtg_tasks.xml

# So I decided to adjust the path in UUID_XML instead which seemed more
# "proper".
sed -e "s@${UUID_XML}@${PWD}/${UUID_XML}@g" -i tmp/default/xdg/data/gtg/projects.xml
```
Maybe `./scripts/import_tasks_from_local.sh` could be extended to explicitly "prepare" for format conversion, or maybe https://github.com/getting-things-gnome/gtg/commit/8d2632b6522300f82a630e6a5d1d3f5f5c3443c8 could be fixed to also handle the path set by `./scripts/import_tasks_from_local.sh`` in `projects.xml`.
