### ISSUE TITLE
GTG crashed at start -  Debian 11 regular release

### ISSUE THREAD

**Issue by Nebdaker** [getting-things-gnome/gtg#932]
GTG v0.6 installed from flathub.org/
Crashed every time on Debian 11 regular release after first successful start

**Context:** Activation

```python-traceback
None```

**Software versions:**
* Getting Things GNOME! v0.6
* CPython 3.9.9 (main, Nov 10 2011, 15:00:00)   [GCC 11.3.0]
* GTK 3.24.34, GLib 2.70.5
* PyGLib 3.42.2, PyGObject 3.42.2
* Linux-5.10.0-18-amd64-x86_64-with-glibc2.33

**Comment by Nebdaker** [comment]
Crash due to plugins not compatible with packages list on regular Debian 11 library.
Problem solved deactivating all the plugin after new install of GTG. 
Remark : to make it work first uninstall GTG with " $ flatpak uninstall org.gnome.GTG " and remove manually the config files located on " ~/.var/app/org.gnome.GTG "

**Comment by LuigiWriter** [comment]
As you may guess this problem with the same crash info is still an alive on on Ubuntu 18.04

Crash info
**Context:** Activation
```python-traceback

```python-traceback
None```

**Software versions:**
* Getting Things GNOME! v0.6
* CPython 3.9.9 (main, Nov 10 2011, 15:00:00)   [GCC 11.3.0]
* GTK 3.24.34, GLib 2.70.5
* PyGLib 3.42.2, PyGObject 3.42.2
* Linux-5.4.0-135-generic-x86_64-with-glibc2.33

hardinfo System Profiler 
-Computer-
4 Processors		: Intel(R) Core(TM) i5 CPU       M 580  @ 2.67GHz
Memory			: 3819MB (2202MB used)
Machine Type		: Notebook
Operating System	: Ubuntu 18.04.6 LTS
-Display-Res.		: 3286x1080 pixels
Kernel		        : Linux 5.4.0-97-generic (x86_64)
Version		        : #110~18.04.1-Ubuntu SMP Mon Jan 17 20:50:31 UTC 2022
C Library		    	: GNU C Library / (Ubuntu GLIBC 2.27-3ubuntu1.4) 2.27
Distribution		: Ubuntu 18.04.6 LTS

**Comment by nekohayo** [comment]
Hi @Nebdaker, seeing this report today, I am left wondering what it might be about, as there is no traceback and the description is a bit unclear. Could your issue have been one of the other issues already reported here, namely one of the three pinned issues at the top of the [issues](https://github.com/getting-things-gnome/gtg/issues) page?

Otherwise we will need more precise information to understand what causes this.

**Comment by LuigiWriter** [comment]
Hi @Nebdaker, It seems the Problem with GTG crashes and the absence of tracebacks to give you any clue, at least in my case, was Ubuntu Studio 22.04.1. 
I was asked to upgrade to 22.10 but the provided widget kept failing. 
After a clean install of 22.10 Ubuntu Studio, I have had no more crashes of any sort. I do not miss that little red frowning face in the status bar at all. 
FYI: Checking Ask.Ubuntu and launchpad.net I find the only complaints about Debuginfod is about including code. Replies indicate that is a future feature. 
Being no expert in this, I would first suspect, without evidence to the contrary, that any reports of crashes with no tracebacks would be from 22.04.1 users. I hope this information helps in those cases.
