### ISSUE TITLE
Pasting task content can lead to untagged tasks

### ISSUE THREAD

**Issue by patipatini** [getting-things-gnome/gtg#94]
Steps to reproduce :
- Ctrl+N to create a new task
- paste following text in task description :

> @tag1, @tag2, @tag3
> Task description
- notice that the tags aren't coloured in yellow
- without further edition close task editor → the task is not tagged with either tags

This is similar to bug #87 : the problem  is fixed if I open again the task editor, but it IS possible to have a @mysupertag in a task description without having this task tagged "mysupertag".

**Comment by diegogangl** [comment]
Fixed by the shiny new taskview :rocket:
