### ISSUE TITLE
New instance of not opening existing xml files

### ISSUE THREAD

**Issue by LuigiWriter** [getting-things-gnome/gtg#944]
Experienced same problem as 
 GTG crashed at start - Debian 11 regular release 932 
but during v0.5 and running out of time to try troubleshooting the situation I dropped back to Ubuntu's 03.1-4 which at least functioned

Seeing that v0.6 is out I decided to try again and got the crash described in 
https://github.com/getting-things-gnome/gtg/issues/932 
I decided to try Nebdaker's solution. It fixed the crash problem, but now GTG opens without my tasks, only with the "Getting started" task list and option for opening a new task.

His solution involved deactivating all the plugins after new install of GTG.
Specifically these steps.
1. uninstalled GTG with " $ flatpak uninstall org.gnome.GTG " 
2. remove manually the config files located on " ~/.var/app/org.gnome.GTG "
3. I requested whether it was individual files, or the file folders in /.var/app/org.gnome.GTG/config
4. May have picked the wrong option and deleted the folders glib-2.0, gtg, ibus and yelp. But since none of the .conf files seem to point to a data storage path I will depend on your expertise.
5. Down loaded  org.gnome.GTG.flatpakref
        from    https://flathub.org/apps/details/org.gnome.GTG
6. Installed v0.6 using Ubuntu "Application installer"
7. Now it opens but does not load the xml files " ~/.var/app/org.gnome.GTG " or its sub-folders.
8. Instead I get the "Getting started with GTG"
9. I looked for a file > open menu command but none available
10. The Plugin options are listed but none are checked. 
11. The folders glib-2.0, gtg, ibus and yelp have been recreated with the formatting files backends.conf, gtg.conf and tasks.conf. 
12. I checked and the following files; gtg_data.xml, gtg_tasks.xml, projects.xml, tags.xml  dated yesterday exist in " .var/app/org.gnome.GTG/data/gtg ": where I assume the Ubuntu Flathub verson stored them. 
13. I copied the xml files into " ~/.var/app/org.gnome.GTG " closed and reopened GTG and still got just the "getting started" list. 
14. I opened the gtg_tasks.xml in Kate and confirmed that my seemingly infinite list of tasks still exist within it.
15. Have copied the files created earlier to a backup drive.
16. Clicked [Mark as Done] on the "Getting Started . . ." task, and am left with only "My new task" in the task list.

This puzzles me as the readme.md file states "If you are running the Flatpak package version, those directories are all in ~/.var/app/org.gnome.GTG/ (or something similar)" and there reside the files. 

I am at this point without any ideas of how to proceed, and would appreciate any help or ideas you might have. As I have just done with the GnuCash crew I am willing to perform any procedures or tests you ask of me. I really do not want to have to drop back to Ubuntu Universe GTG 03.1-4.

hardinfo System Profiler Information
-Computer-
4 Processors		: Intel(R) Core(TM) i5 CPU       M 580  @ 2.67GHz
Memory			: 3819MB (2202MB used)
Machine Type		: Notebook
Operating System	: Ubuntu 18.04.6 LTS
-Display-Res.		: 3286x1080 pixels
Kernel		        : Linux 5.4.0-97-generic (x86_64)
Version		        : #110~18.04.1-Ubuntu SMP Mon Jan 17 20:50:31 UTC 2022
C Library		    	: GNU C Library / (Ubuntu GLIBC 2.27-3ubuntu1.4) 2.27
Distribution		: Ubuntu 18.04.6 LTS

**Comment by LuigiWriter** [comment]
I have fixed this. The problem was Ubuntu's distro version was storing the files in the  
 ~/.local/share/gtg/backup/ directory. 
The tags, projects and task xml files were no longer saved after 2022-07-04.
		The only file being backed up after that was
		gtg_data.xml.bak.x
	So finding the most recent copy in the .local directory and moving it to the  
         ~/.var/app/org.gnome.GTG/data/gtg/backup/
      Then following my revision of Bertrand Rousseau's original, from 2012-05-06 I was able to get v0.6 to open the only file it needed, my backup copy of gtg_data.xml

I confirmed that tags, projects and task xml files were no longer needed by moving them to another directory and reopening GTG v0.6

I have opened the following bug report containing the procedure I followed below.
The backup file full path and name needs to be changed in README.md and added to Help.

Open:
~/.var/app/org.gnome.GTG/data/gtg/backup/
This is an example of the files you are looking for.

gtg_data.xml.bak.0				
gtg_data.xml.bak.1				
gtg_data.xml.2022-12-11.bak		

Note: 	The file titles like these are no longer used:
		ea8d1d10-0a33-4ae7-aa34-fb85f7556e16.xml.bak.0

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
How to restore a backup:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1.	Make a copy of the whole 
	~/.var/app/org.gnome.GTG/data/gtg/ including /backup/ folders and files before doing anything!
	This preferably on a USB thumb-drive or other dis-connectable storage device.

2.	Open:
	~/.var/app/org.gnome.GTG/data/gtg/
	Move to Trash: 
		gtg_data.xml

	Leaving ".directory" in place. [not sure its function but its presence did not pose a problem]

3.	In 
	~/.var/app/org.gnome.GTG/data/gtg/backup/
	Pick a file matching:
		gtg_data.xml.bak.0				
			or 
		gtg_data.xml.2022-12-11.bak		

4.	Copy it to:
	~/.var/app/org.gnome.GTG/data/gtg/
	
5.	Rename it to: 
		gtg_data.xml

6.	Restart Getting Things GNOME!
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Example process (in a shell):
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1.	cd ~/.var/app/org.gnome.GTG/data/gtg/
2.	rm gtg_data.xml
3.	mv ~/.var/app/org.gnome.GTG/data/gtg/backup/gtg_data.xml.bak.0 ~/.var/app/org.gnome.GTG/data/gtg/gtg_data.xml.bak.0
4.	mv gtg_data.xml.bak.0 gtg_data.xml

Note: 	I am not sure more than mv /gtg/backup/gtg_data.xml.bak.0 /gtg/gtg_data.xml.bak.0 
		is needed in step 3. My command line competency is very limited. 
		
You may have to try several backup files until finding a good one.

I [Luigi] have only tested this with the following system and ask others to confirm the above or let me know of needed changes.

-Computer-
4 Processors		: Intel(R) Core(TM) i5 CPU       M 580  @ 2.67GHz
Memory			: 3819MB (2202MB used)
Machine Type		: Notebook
Operating System	: Ubuntu 18.04.6 LTS
-Display-Res.		: 3286x1080 pixels

Operating System
Kernel		        : Linux 5.4.0-97-generic (x86_64)
Version		        : #110~18.04.1-Ubuntu SMP Mon Jan 17 20:50:31 UTC 2022
C Library		    	: GNU C Library / (Ubuntu GLIBC 2.27-3ubuntu1.4) 2.27
Distribution		: Ubuntu 18.04.6 LTS

**Comment by nekohayo** [comment]
Reading this, I am a bit confused, it seems you upgraded from a super ancient (0.3.x) version from Ubuntu to the latest 0.6 version in Flathub, and are asking about documenting the backup folder.... but the folder paths are _already_ documented in the README.md file that shows up at the root of this repository here... so it seems there is nothing actionable to be done here.
