### ISSUE TITLE
Tip on Fastmail's CalDAV server location for syncing tasks

### ISSUE THREAD

**Issue by ShinyDog2636** [getting-things-gnome/gtg#945]
I apologize, this is not an _issue_ but a solution to an issue I had. While the Fastmail web interface does not show tasks, it does support syncing tasks with Getting Things GNOME

The url for the CALDAV server is
`https://caldav.fastmail.com/dav/principals/user/user@example.com/`

**Comment by madhums** [comment]
Thank you for this. I wonder if there's any mobile apps that can pull in and synchronise this data?  Does anyone know?

**Comment by nekohayo** [comment]
You could use [DAVx⁵](https://f-droid.org/packages/at.bitfire.davdroid/) on the mobile side, I think.
