### ISSUE TITLE
Tags removed from a task's title sometimes don't get removed from the task itself

### ISSUE THREAD

**Issue by patipatini** [getting-things-gnome/gtg#95]
Steps to reproduce
- create a task with a tag @mynewtag in title (this bug is easier to notice if the tag is a fresh new one, but the bug exists even for already existing tags)
- task is created, @mynewtag appears on the side panel (containing the freshly created task)
- edit task, and remove @mynewtag from title
- task remains in @mynewtag instead of being removed from it

Unless issue:87 and issue:94, the bug cannot be fixed by editing the task...

**Comment by tomspur** [comment]
With which version did you reproduce this? I wasn't able to reproduce this with the current master.

**Comment by patipatini** [comment]
Hi Thomas,

gtg --version
GTG (Getting Things GNOME!) 0.3.1

On Debian GNU/Linux 8.0 (jessie)

Regards,
Philippe

**Comment by izidormatusov** [comment]
I've installed the version 0.3.1 from debian and I wasn't able to reproduce it, given the steps. Could you provide us with something that is not in the steps to reproduce?

**Comment by patipatini** [comment]
I don't know if that helps but I'm using XFCE.
Which piece of additional information would you need ?
Would a video of the bug be useful ?

**Comment by izidormatusov** [comment]
Yes, video of reproducing the bug would be helpful.

**Comment by patipatini** [comment]
While trying to reproduce the bug, I noticed it only appears when I use 
the "Ctrl+N" shortcut (which opens a new window), and not if I use the 
quick add/search bar, maybe that's why you can't reproduce it ?

Attached is a video of the bug. I will try to upload a better video 
later (as this one unexpectedly blinks which make it difficult to 
watch...), but you can already figure out the problem.

**Comment by izidormatusov** [comment]
Thanks for the video. I'm still unable to reproduce it :/ However, I've noticed, that GTG stops recognising your tag after a while: `@mysupertag` loses its yellow background. You can see it in your video around 0:35. What happened there? Did you do anything special?

**Comment by patipatini** [comment]
Did not do anything special for that, it happens sometimes, I'll try to 
grab a video to illustrate this.

**Comment by nekohayo** [comment]
I've encountered this bug many times in my normal usage with 0.3.x, but I never paid attention to what exactly causes it. @patipatini, if you could figure out the exact triggers for this, it would still be appreciated.

The workaround when this happens is to edit the task's tags with Ctrl+T (the "right-click -> Modify Tags..." contextual menu).

**Comment by nekohayo** [comment]
Also, maybe this is influenced by whether the tag is selected in the sidebar at the time of the removal, and if the task is the "last one of that tag"?

**Comment by diegogangl** [comment]
Not happening in master anymore
