### ISSUE TITLE
ICS/CalDAV support

### ISSUE THREAD

**Issue by shtrom** [getting-things-gnome/gtg#96]
This is a two pronged issue. The main motivation is to sync VTODOs objects from a remote CalDAV server. In this sense, this issue is just a duplicate of [0].

However, it can be chopped up into
1. Read VTODOs from a collection of local ICS files;
2. Sync them to a remote CalDAV server.

Besides making the implementation potentially easier, this separation would also allow to use separate syncing mechanisms (e.g., untitaker/vdirsyncer), or share the local task list between multiple applications (much in the same way as a Maildir directory can be shared between email clients, e.g., untitaker/watdo). Actually (though I understand it would be a much bigger job), perhaps GTG should use VTODOs as its local storage backend.

[0] https://bugs.launchpad.net/gtg/+bug/1248108

**Comment by nekohayo** [comment]
Closing as nobody has stepped forward to implement this. If you still want to see this happen, please contribute code (or bring in someone who can) to the project for the purpose of reopening this ticket.

**Comment by thomaskuntzz** [comment]
(For reference) Has been brought up again in #407 with an associated PR #419 🙂
