### ISSUE TITLE
ModuleNotFoundError: No module named 'GTG'

### ISSUE THREAD

**Issue by ksdrummer** [getting-things-gnome/gtg#973]
Hi, 

gtg won't open anymore. I'm on archlinux up to date and last few updates include gnome 44 and python 3.11.3.
I use gtg 0.6-6 from the AUR.

```
$ gtg
Traceback (most recent call last):
  File "/usr/bin/gtg", line 85, in <module>
    from GTG.core import info
ModuleNotFoundError: No module named 'GTG'
```

Am I the only one ?

(Anyway thanks for this amazing piece of software, really love it !)

**Comment by azmeuk** [comment]
Archlinux recently updated python to python 3.11 so that might cause some troubles with previously installed AUR python packages.
Did you try to remove then reinstall the `python-liblarch python-caldav gtg` packages?

**Comment by ksdrummer** [comment]
Hi, no I didn't then but I just did it now and the problem is solved. Thanks for the suggestion !
