### ISSUE TITLE
Ignore @ for tags if part of an URL (such as Mastodon user/posts links)

### ISSUE THREAD

**Issue by Poslovitch** [getting-things-gnome/gtg#987]
URLs that contain an `@` (mainly from social media platforms, such as one of these for Mastodon: https://wikis.world/@Poslovitch/111121879906550235) and that are pasted in a task's title or description causes the part of the URL after the `@` to be interpreted as a tag (e.g. `@Poslovitch/111121879906550235`).

This is, at least for me, unwanted behavior.

**Comment by kocio-pl** [comment]
One should tweak `TAG_REGEX` variable:

https://github.com/getting-things-gnome/gtg/blob/master/GTG/gtk/editor/taskview.py#L46

Currently it is set as:
```python
\B\@\w+(\.*[\-\w+\+\%\$\\(\)\[\]\{\}\^\=\/\*])*
``` 
and simple check on https://regex101.com/ confirms the problem.

**Comment by kocio-pl** [comment]
Replacing ```\B``` with negative lookbehind assertion ```(?<!\/)``` seems to do the trick, but more testing should is welcome.

**Comment by kocio-pl** [comment]
`(?<!\/|\w)` in place of `\B` works even better, because it skips not only https://wikis.world/@Poslovitch/111121879906550235 , but also http://username:password@host.example.com (with any word character before @, not just slash).

**Comment by nekohayo** [comment]
I have no idea if there are automated tests for the regexes, but if there aren't, there should be, indeed!

**Comment by kocio-pl** [comment]
I don't see such test in https://github.com/getting-things-gnome/gtg/blob/master/tests/core/test_tag.py nor https://github.com/getting-things-gnome/gtg/blob/master/tests/core/test_tag2.py (I'm not even sure why there is two and they are named like that). I'm waiting for #1036 to be merged, I hope I can make some regex tag tests then.
